Description of CalcMC
CalcMC
PURPOSE
Additional function that computes the global mass of the jth segments.
SYNOPSIS
function mc=CalcMC(Human_model,j)
DESCRIPTION
 Additional function that computes the global mass of the jth segments.
   INPUT
   - Human_model: osteo-articular model (see the Documentation for the
   - j: current solid
   OUTPUT
   - mc: total mass of the solids
________________________________________________________
 Licence
 Toolbox distributed under GPL 3.0 Licence
________________________________________________________
 Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
 Georges Dumont
________________________________________________________
CROSS-REFERENCE INFORMATION
This function calls:
CalcMC Additional function that computes the global mass of the jth segments.
This function is called by:
CalcCoM Function that computes the global center of mass position.
CalcMC Additional function that computes the global mass of the jth segments.
SOURCE CODE
function mc=CalcMC(Human_model,j)
% Additional function that computes the global mass of the jth segments.
%
%   INPUT
%   - Human_model: osteo-articular model (see the Documentation for the
%   - j: current solid
%   OUTPUT
%   - mc: total mass of the solids
%________________________________________________________
%
% Licence
% Toolbox distributed under GPL 3.0 Licence
%________________________________________________________
%
% Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
% Georges Dumont
%________________________________________________________
if j==0
    mc=0;
else
    mc=Human_model(j).m*(Human_model(j).p+Human_model(j).R*Human_model(j).c);
    mc=mc+CalcMC(Human_model,Human_model(j).sister)+CalcMC(Human_model,Human_model(j).child);
end