function [Markers]=Marker_set6(varargin)
% Definition of the markers set used in XSENS
%
%   OUTPUT
%   - Markers: set of markers (see the Documentation for the structure) 
%________________________________________________________
%
% Licence
% Toolbox distributed under GPL 3.0 Licence
%________________________________________________________
%
% Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
% Georges Dumont
%________________________________________________________

s=cell(0);

% TRUNK & HEAD
s=[s;{'RAsis' 'RFWT' {'On';'Off';'On'};...
            'LAsis' 'LFWT' {'On';'Off';'On'};...
            'RPsis' 'RBWT' {'On';'Off';'On'};...
            'LPsis' 'LBWT' {'On';'Off';'On'};...
            'Lumbar' 'Pelvis_L5JointNode' {'Off';'On';'Off'}; ...
            'Thoracic' 'T10' {'Off';'On';'Off'};...
            'RightShoulder' 'RSHO' {'Off';'Off';'On'};...
            'LeftShoulder' 'LSHO' {'Off';'Off';'On'}; ...
            'Neck' 'C7' {'On';'On';'Off'}; ...
            'Sternum' 'STRN' {'Off';'On';'Off'};...
             'Xiphoid' 'CLAV'  {'Off';'Off';'Off'};  }];

Side1={'Right';'Left'};
Side2={'R';'L'};
% Arm
for i=1:2
    s=[s;{  [Side2{i} 'Elbow'] [Side2{i} 'RAD'] {'On';'On';'Off'};...
            [Side2{i} 'Ulna'] [Side2{i} 'WRB'] {'Off';'On';'Off'}; ...
            [Side2{i} 'Radius'] [Side2{i} 'WRA'] {'Off';'Off';'Off'}; ...
            [Side2{i} 'Wrist'] [Side2{i} 'Hand_WristJointNode'] {'Off';'Off';'Off'}; ...
        }];
end

% Leg
for i=1:2
    s=[s;{  %[Side2{i} 'ShankSuperior'] [Side2{i} 'ShankUpper'] {'On';'On';'On'};...
            [Side2{i} 'ShankLateral'] [Side2{i} 'ShankFront'] {'On';'On';'On'};...
            [Side2{i} 'ShankInferior'] [Side2{i} 'ShankRear'] {'On';'On';'On'};...
            %[Side2{i} 'ThighSuperior'] [Side2{i} 'ThighUpper'] {'On';'On';'On'};...
            [Side2{i} 'ThighLateral'] [Side2{i} 'ThighFront'] {'On';'On';'On'};...
            [Side2{i} 'ThighInferior'] [Side2{i} 'ThighRear'] {'On';'On';'On'};...
            [Side2{i} 'Hindfoot'] [Side2{i} 'ANE'] {'On';'On';'On'};...
        %    [Side2{i} 'MidfootLateral'] [Side2{i} 'MidFootLateral'] {'On';'On';'On'}; ...
            [Side2{i} 'Heel'] [Side2{i} 'HEE'] {'On';'On';'On'}; ...
            [Side2{i} 'Toe'] [Side2{i} 'TOE'] {'On';'On';'On'}; ...
        }];
end

Markers=struct('name',{s{:,1}}','anat_position',{s{:,2}}','calib_dir',{s{:,3}}'); %#ok<CCAT1>

end