function [Markers]=Marker_set7(varargin)
% Definition of the markers set used in the IRSST for project: déplacement
% des pieds
%
%   OUTPUT
%   - Markers: set of markers (see the Documentation for the structure)

s=cell(0);

% Trunk
s=[s;{...
    'PROXIP' 'STRN' {'Off';'On';'Off'};...% Processus Xiphoide
    'MANUB' 'CLAV' {'On';'On';'Off'};...
    'T8' 'T8' {'Off';'On';'Off'};...
    'C7' 'C7' {'On';'On';'Off'};...
    'L5' 'Pelvis_L5JointNode' {'Off';'Off';'Off'};...    
    'ANGACRD' 'REAR' {'On';'Off';'On'};...
    'ANGACRG' 'LEAR' {'On';'Off';'On'};...
    'EIASD' 'RFWT' {'On';'Off';'On'};...
    'EIASG' 'LFWT' {'On';'Off';'On'};...
    'EIPSD' 'RBWT' {'On';'Off';'On'};...
    'EIPSG' 'LBWT' {'On';'Off';'On'};...
    'NEZ' 'NEZ' {'Off';'Off';'Off'};...
    'VERTEX' 'VERTEX' {'Off';'On';'On'};...
    }];

Side={'R';'L'};
Side2={'D';'G'};
% Leg
for i=1:2
    Signe=Side{i};
    Signe2=Side2{i};
    s=[s;{['GEX' Signe2] [Signe 'KNE'] {'Off';'Off';'Off'};...
        ['MAE' Signe2] [Signe 'ANE'] {'Off';'On';'Off'};...
        ['MAI' Signe2] [Signe 'ANI'] {'Off';'Off';'Off'};...
        ['GIN' Signe2] [Signe 'KNI'] {'Off';'On';'On'};
        ['TAL' Signe2] [Signe 'HEE'] {'On';'On';'Off'};...
        ['PIEX' Signe2] [Signe 'TAR'] {'Off';'On';'On'};...
        ['BP' Signe2] [Signe 'TOE'] {'Off';'On';'Off'};...
        ['PIIN' Signe2] [Signe 'TARI'] {'Off';'On';'On'};...
        }]; %#ok<AGROW>
end


% Arm
for i=1:2
    Signe=Side{i};
    Signe2=Side2{i};
    s=[s;{['EPI' Signe2] [Signe 'HUM'] {'Off';'Off';'Off'};...
        ['EPE' Signe2] [Signe 'RAD'] {'On';'On';'Off'};...
        ['PEX' Signe2] [Signe 'WRA'] {'Off';'Off';'Off'};...
        ['PIN' Signe2] [Signe 'WRB'] {'Off';'On';'Off'};...
        ['MC2' Signe2] [Signe 'CAR2'] {'Off';'Off';'Off'};...
        ['MC5' Signe2] [Signe 'OHAND'] {'Off';'Off';'Off'};...        
        }]; %#ok<AGROW>   
end

Markers=struct('name',{s{:,1}}','anat_position',{s{:,2}}','calib_dir',{s{:,3}}'); %#ok<CCAT1>

end