Description of btkGetLastFrame
btkGetLastFrame
PURPOSE
BTKGETLASTFRAME Returns acquisition's last frame index.
SYNOPSIS
function lf = btkGetLastFrame(h) %#ok
DESCRIPTION
BTKGETLASTFRAME Returns acquisition's last frame index.
  LF = BTKGETLASTFRAME(H) returns the last frame index of the acquisition.
  The acquistion is represented by the handle H, obtained by the use of a
  btk* function.
CROSS-REFERENCE INFORMATION
This function calls:
btkGetFirstFrame BTKGETFIRSTFRAME Returns acquisition's first frame index.
btkGetPointFrameNumber BTKGETPOINTFRAMENUMBER Returns the number of frames for the points.
btkGetFirstFrame BTKGETFIRSTFRAME Returns acquisition's first frame index.
btkGetPointFrameNumber BTKGETPOINTFRAMENUMBER Returns the number of frames for the points.
btkGetFirstFrame BTKGETFIRSTFRAME Returns acquisition's first frame index.
btkGetPointFrameNumber BTKGETPOINTFRAMENUMBER Returns the number of frames for the points.
This function is called by:
btkCropAcquisition BTKCROPACQUISITION Crop the acquisition and adapt the events' frame/time.
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
btkCropAcquisition BTKCROPACQUISITION Crop the acquisition and adapt the events' frame/time.
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
btkCropAcquisition BTKCROPACQUISITION Crop the acquisition and adapt the events' frame/time.
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
C3dProcessedData Extraction of experimental data in a processed c3d
SOURCE CODE
function lf = btkGetLastFrame(h) %#ok
%BTKGETLASTFRAME Returns acquisition's last frame index.
%
%  LF = BTKGETLASTFRAME(H) returns the last frame index of the acquisition.
%  The acquistion is represented by the handle H, obtained by the use of a
%  btk* function.
%  Author: A. Barré
%  Copyright 2009-2013 Biomechanical ToolKit (BTK).
lf = btkGetFirstFrame(h) + btkGetPointFrameNumber(h) - 1;
% [EOF] btkGetFirstFrame.m