Description of btkGetVersion
btkGetVersion
PURPOSE
V = BTKGETVERSION returns the release number of BTK.
SYNOPSIS
function v = btkGetVersion()
DESCRIPTION
V = BTKGETVERSION returns the release number of BTK.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
btkTransformTDFToViconC3DFile BTKTRANSFORMTDFTOVICONC3DFILE transforms a TDF file (BTS Bioengineering) to a compatible Vicon C3D file.
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
btkTransformTDFToViconC3DFile BTKTRANSFORMTDFTOVICONC3DFILE transforms a TDF file (BTS Bioengineering) to a compatible Vicon C3D file.
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
btkTransformTDFToViconC3DFile BTKTRANSFORMTDFTOVICONC3DFILE transforms a TDF file (BTS Bioengineering) to a compatible Vicon C3D file.
SOURCE CODE
function v = btkGetVersion()
%V = BTKGETVERSION returns the release number of BTK.
%  Author: A. Barré
%   Copyright 2009-2013 Biomechanical ToolKit
v = '0.3.0';