function [BiomechanicalModel] = DynamicCalibration(ModelParameters,AnalysisParameters, BiomechanicalModel)
% Calibration of the inertial parameters
%   Inertial parameters (mass, local position of the center of mass and
%   inertia of each solid) are subject-specific calibrated from motion
%   capture data and force platforms data
%
%   Associated publication:
% 	- Muller, A., Chauwin, M., Pontonnier, C., Dumont, G., 2017. 
%	Influence of Physiological Constraints on a Subject-specific BSIP Calibration. In: Proceedings of the XXVI Congress of the International Society of Biomechanics.
%
%   Based on:
%	-Vaughan, C.L., Andrews, J.G., Hay, J.G., 1982. 
%	Selection of body segment parameters by optimization methods. J. Biomech. Eng. 104, 38–44.
%	-Reinbolt, J.A., Haftka, R.T., Chmielewski, T.L., Fregly, B.J., 2007. 
%	Are patient-specific joint and inertial parameters necessary for accurate inverse dynamics analyses of gait? IEEE Trans. Biomed. Eng. 54, 782–793.
%	-Jovic, J., Escande, A., Ayusawa, K., Yoshida, E., Kheddar, A., Venture, G., 2016.
%	-Humanoid and Human Inertia Parameter Identification Using Hierarchical Optimization. IEEE Trans. Robot. 32, 726–735.
%	-Yeadon, M.R., 1990. the Simulation of Aerial Movement 2. 
%	A Mathematical Inertia Model of the Human Body. J. Biomech. 23, 67–74.
%
%   INPUT
%   - ModelParameters: parameters of the musculoskeletal model, automatically
%   generated by the graphic interface 'GenerateParameters' 
%   - AnalysisParameters: parameters of the musculoskeletal analysis
%   automatically generated by the graphic interface 'Analysis'
%   - BiomechanicalModel: musculoskeletal model
%   OUTPUT
%   - BiomechanicalModel: subject-specific calibrated musculoskeletal model
%________________________________________________________
%
% Licence
% Toolbox distributed under GPL 3.0 Licence
%________________________________________________________
%
% Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
% Georges Dumont
%________________________________________________________

%% Chgt du fichier à traiter
%% Change the name of the file to deal with
AnalysisParameters.filename = {AnalysisParameters.CalibID.filename};

%% Cinématique inverse
%% Inverse kinematics
InverseKinematics(AnalysisParameters, BiomechanicalModel);

%% Efforts extérieurs
%% External forces
ExternalForcesComputation(AnalysisParameters, ModelParameters, BiomechanicalModel);

%% Paramètres géométriques anthropometrique
%% Anthropometric geometric parameters
[BiomechanicalModel.OsteoArticularModel] = FindInitDynParam(BiomechanicalModel.OsteoArticularModel);

%% Calibration
[BiomechanicalModel.OsteoArticularModel] = DynCalibOptimization(ModelParameters, AnalysisParameters, BiomechanicalModel);

end
