Description of GeometricalCalibration
Home > Functions > Calibration > Geometrical > GeometricalCalibration.m
GeometricalCalibration
PURPOSE
Calibration of the geometrical parameters
SYNOPSIS
function [Human_model_calib, calib_parameters, Markers_set] = GeometricalCalibration(OsteoArticularModel, Markers_set, AnalysisParameters)
DESCRIPTION
 Calibration of the geometrical parameters
   Geometrical parameters (limbs length, local markers position and axis
   of rotation) are subject-specific calibrated from motion capture data.
   Associated publication:
    - Muller, A., Germain, C., Pontonnier, C., Dumont, G., 2015.
    A Simple Method to Calibrate Kinematical Invariants: Application to Overhead Throwing. Int. Soc. Biomech. Sport. 2–5.
   Based on:
    - Reinbolt, J.A., Schutte, J.F., Fregly, B.J., Koh, B. Il, Haftka, R.T., George, A.D., Mitchell, K.H., 2005.
    Determination of patient-specific multi-joint kinematic models through two-level optimization. J. Biomech. 38, 621–626.
    - Andersen, M.S., Damsgaard, M., MacWilliams, B., Rasmussen, J., 2010.
    A computationally efficient optimisation-based method for parameter identification of kinematically determinate and over-determinate biomechanical systems. Comput. Methods Biomech. Biomed. Engin. 13, 171–183.
   INPUT
   - OsteoArticularModel: osteo-articular model (see the Documentation for
   the structure);
   - Markers_set: markers set (see the Documentation for the structure);
   - AnalysisParameters: parameters of the musculoskeletal analysis,
   automatically generated by the graphic interface 'Analysis'.
   OUTPUT
   - Human_model_calib: subject-specific calibrated osteo-articular model
   (see the Documentation for the structure);
   - calib_parameters: geometrical calibration results;
   - Markers_set: subject-specific calibrated markers set (see the
   Documentation for the structure).
________________________________________________________
 Licence
 Toolbox distributed under 3-Clause BSD License
________________________________________________________
CROSS-REFERENCE INFORMATION
This function calls:
Rodrigues Computation of the Rodrigues equation
ClosedLoopCalib Non-linear equation used in the geometrical calibration step for closed loops
CostFunctionSymbolicCalib Cost function used for the geometrical calibration step
ErrorMarkersCalib Computation of reconstruction error for the geometrical calibration
OptCalibrationSymbolic Cost function used for the calibration of the geometrical parameters
SymbolicFunctionGeneration_A Generation of symbolic function containing the position of markers according to joint coordinates and geometrical parameters
Add6dof Addition of a 6 dof joint
Get_real_markers_Calibration Extraction of motion data for the geometrical calibration
This function is called by:
CalibrateModelGeneration Generation of the calibrated musculoskeletal model
SOURCE CODE
function [Human_model_calib, calib_parameters, Markers_set] = GeometricalCalibration(OsteoArticularModel, Markers_set, AnalysisParameters)
% Calibration of the geometrical parameters
%   Geometrical parameters (limbs length, local markers position and axis
%   of rotation) are subject-specific calibrated from motion capture data.
%
%   Associated publication:
%    - Muller, A., Germain, C., Pontonnier, C., Dumont, G., 2015.
%    A Simple Method to Calibrate Kinematical Invariants: Application to Overhead Throwing. Int. Soc. Biomech. Sport. 2–5.
%
%   Based on:
%    - Reinbolt, J.A., Schutte, J.F., Fregly, B.J., Koh, B. Il, Haftka, R.T., George, A.D., Mitchell, K.H., 2005.
%    Determination of patient-specific multi-joint kinematic models through two-level optimization. J. Biomech. 38, 621–626.
%    - Andersen, M.S., Damsgaard, M., MacWilliams, B., Rasmussen, J., 2010.
%    A computationally efficient optimisation-based method for parameter identification of kinematically determinate and over-determinate biomechanical systems. Comput. Methods Biomech. Biomed. Engin. 13, 171–183.
%
%   INPUT
%   - OsteoArticularModel: osteo-articular model (see the Documentation for
%   the structure);
%   - Markers_set: markers set (see the Documentation for the structure);
%   - AnalysisParameters: parameters of the musculoskeletal analysis,
%   automatically generated by the graphic interface 'Analysis'.
%   OUTPUT
%   - Human_model_calib: subject-specific calibrated osteo-articular model
%   (see the Documentation for the structure);
%   - calib_parameters: geometrical calibration results;
%   - Markers_set: subject-specific calibrated markers set (see the
%   Documentation for the structure).
%________________________________________________________
%
% Licence
% Toolbox distributed under 3-Clause BSD License
%________________________________________________________
%% Sauvegarde du modèle
Human_model_save=OsteoArticularModel;
%% Ajout ou suppresion de contraintes spécifiées dans AnalysisParameters
%% Taking into account of constraints specified in AnalysisParameters
% k
for i = 1:size(AnalysisParameters.CalibIK.LengthDelete,1)
    [~,~,num_solid] = intersect(AnalysisParameters.CalibIK.LengthDelete{i,1},{OsteoArticularModel.name});
    OsteoArticularModel(num_solid).calib_k_constraint = [];
end
for i = 1:size(AnalysisParameters.CalibIK.LengthAdd,1)
    [~,~,num_solid1] = intersect(AnalysisParameters.CalibIK.LengthAdd{i,1},{OsteoArticularModel.name});
    [~,~,num_solid2] = intersect(AnalysisParameters.CalibIK.LengthAdd{i,2},{OsteoArticularModel.name});
    OsteoArticularModel(num_solid1).calib_k_constraint = num_solid2;
end
% v
for i=1:size(AnalysisParameters.CalibIK.AxisDelete,1)
    [~,~,num_solid] = intersect(AnalysisParameters.CalibIK.AxisDelete{i,1},{OsteoArticularModel.name});
    OsteoArticularModel(num_solid).v = setdiff(OsteoArticularModel(num_solid).v',AnalysisParameters.CalibIK.AxisDelete{i,2}','rows')';
end
for i=1:size(AnalysisParameters.CalibIK.AxisAdd,1)
    [~,~,num_solid] = intersect(AnalysisParameters.CalibIK.AxisAdd{i,1},{OsteoArticularModel.name});
    OsteoArticularModel(num_solid).v = [OsteoArticularModel(num_solid).v AnalysisParameters.CalibIK.AxisAdd{i,2}];
end
% Markers
for i=1:size(AnalysisParameters.CalibIK.MarkersCalibModif,1)
    [~,~,num_solid] = intersect(AnalysisParameters.CalibIK.MarkersCalibModif{i,1},{Markers_set.name});
    Markers_set(num_solid).calib_dir = AnalysisParameters.CalibIK.MarkersCalibModif{i,2};
end
%% Ajout de la liaison 6ddl / adding 6 DOF joint (pelvis to world)
[OsteoArticularModel] = Add6dof(OsteoArticularModel);
s_root=find([OsteoArticularModel.mother]==0); %#ok<NASGU> % numéro du solide root
%% Génération des fonctions symboliques (symbolical function generation)
% Position de chaque marqueur en fonction des coordonnées articulaires
[OsteoArticularModel,nbClosedLoop,~,nb_k,k_map,nb_p,p_map,nb_alpha,alpha_map,A_norm,b_norm]=SymbolicFunctionGeneration_A(OsteoArticularModel, Markers_set);
%% liste des marqueurs à partir du modèle (marker list)
list_markers={};
for i=1:numel(Markers_set)
    if Markers_set(i).exist
        list_markers=[list_markers;Markers_set(i).name]; %#ok<AGROW>
    end
end
nb_markers=size(list_markers,1);
nb_solid=size(OsteoArticularModel,2);  % nb de solides (number of solids)
%% Récupération de la position des marqueurs réels à partir du fichier C3D
%% Real markers position from C3D file
filename = AnalysisParameters.CalibIK.filename(1:end-4);
[real_markers, nb_frame]=Get_real_markers_Calibration(filename,list_markers, AnalysisParameters);
%% Sélection d'un échantillon de frame
%% Selection/choice of frame sample
nb_frame_calib = AnalysisParameters.CalibIK.Frames.NbFrames;
[frame_calib] = AnalysisParameters.CalibIK.Frames.Method(nb_frame_calib, real_markers, list_markers);
calib_parameters.frame_calib = frame_calib;
% Récupération des frames utilisées pour la calibration
% Frame to use for calibration
real_markers_calib=struct;
for i=1:numel(real_markers)
    real_markers_calib(i).name=real_markers(i).name;
    real_markers_calib(i).position=real_markers(i).position(frame_calib,:);
end
%% Positionnement du root
Base_position=cell(nb_frame,1);
Base_rotation=cell(nb_frame,1);
for i=1:nb_frame
    Base_position{i}=zeros(3,1);
    Base_rotation{i}=eye(3,3);
end
%% Initialisations
taille = nb_k+nb_p+nb_alpha;
%Initialisation à 0 de k,p,alpha
k_init=zeros(taille,1);
% Contraintes linéaires pour la cinématique inverse
% linear constraints for inverse kinemeatics
Aeq_ik=zeros(nb_solid);  % initialisation
beq_ik=zeros(nb_solid,1);
for i=1:nb_solid
    if size(OsteoArticularModel(i).linear_constraint) ~= [0 0] %#ok<BDSCA>
        Aeq_ik(i,i)=-1;
        Aeq_ik(i,OsteoArticularModel(i).linear_constraint(1,1))=OsteoArticularModel(i).linear_constraint(2,1);
    end
end
%% Cinématique inverse frame / frame
%% Inverse kinematics
% options = optimoptions(@fmincon,'Algorithm','interior-point','Display','iter-detailed','PlotFcns',@optimplotfval,'TolFun',1e-2,'MaxFunEvals',20000);
options = optimoptions(@fmincon,'Algorithm','interior-point','Display','off','TolFun',1e-2,'MaxFunEvals',20000);
q_value{1}=zeros(nb_solid,nb_frame_calib);
addpath('Symbolic_function')
Rcut=zeros(3,3,max([OsteoArticularModel.KinematicsCut]));   % initialisation de la position et de l'orientation des repères de coupure
pcut=zeros(3,1,max([OsteoArticularModel.KinematicsCut]));
% Création des listes de fonctions utilisées dans le calcul de la fonction
% de coût
% Functions list for computing cost function
list_function=cell(max([OsteoArticularModel.KinematicsCut]),1);
for c=1:max([OsteoArticularModel.KinematicsCut])
    list_function{c}=str2func(sprintf('f%dcut',c));
end
list_function_markers=cell(numel(list_markers),1);
for m=1:numel(list_markers)
    list_function_markers{m}=str2func(sprintf([list_markers{m} '_Position']));
end
l_inf=[OsteoArticularModel.limit_inf];
l_sup=[OsteoArticularModel.limit_sup];
for f=1:nb_frame_calib
    if f == 1      % valeur initiale
        q0=zeros(nb_solid,1);
    else
        q0=q_value{1}(:,f-1);
    end
    ik_function_objective=@(qvar)CostFunctionSymbolicCalib(qvar,k_init,OsteoArticularModel,real_markers_calib,f,list_function,list_function_markers,Base_position{f},Base_rotation{f},Rcut,pcut);
    nonlcon=@(qvar)ClosedLoopCalib(Base_position{f},Base_rotation{f},qvar,k_init,pcut,Rcut,nbClosedLoop); % pas tester
    [q_value{1}(:,f)] = fmincon(ik_function_objective,q0,[],[],Aeq_ik,beq_ik,l_inf,l_sup,nonlcon,options);
end
% Calcul de l'erreur
errorm{1}=zeros(numel(list_markers),nb_frame_calib);
for f=1:nb_frame_calib
    [errorm{1}(:,f)] = ErrorMarkersCalib(q_value{1}(:,f),k_init,OsteoArticularModel,real_markers_calib,f,list_markers,Base_position{f},Base_rotation{f},Rcut,pcut);
end
%% Calibration
% Contraintes d'optimisation pour la calibration (Optimization constraints for calibration)
Aeq_calib=zeros(taille);
beq_calib=zeros(taille,1);
% Contraintes pour k, facteur d'homothétie
ind_k = unique([Markers_set.num_solid]);
for i=1:length(ind_k)
    cur_num_sol=ind_k(i);
    if size(OsteoArticularModel(cur_num_sol).calib_k_constraint) ~= [0 0] %#ok<BDSCA>
        if OsteoArticularModel(cur_num_sol).calib_k_constraint == 0
            Aeq_calib(i,i)=1;
            beq_calib(i,1)=-1;
        else
            %Attention pas encore tester !
            ind_ind_k = ind_k==OsteoArticularModel(cur_num_sol).calib_k_constraint;
            Aeq_calib(i,i)=1;
            Aeq_calib(i,ind_ind_k)=-1;
        end
    end
end
%% Limite de variation des variables (boundaries for setting variation limits)
limit_inf_calib = -ones(taille,1);
limit_sup_calib = ones(taille,1);
g=1;        % nombre de boucles
crit(:,g)=1; % initialisation du critère d'arrêt (stop criteria)
% Optimisation k, p,alpha
% valeurs initiales
kp_opt(:,g)=k_init;
while crit(:,g) > 0.05
    % Optimisation des paramètres géométriques (geometric parameters optimisation)
    pk_function_objective=@(kp)OptCalibrationSymbolic(...
                          q_value{g},kp,...
                          OsteoArticularModel,real_markers_calib,nb_frame_calib,list_function,list_function_markers,Base_position,Base_rotation,Rcut,pcut);
    [kp_opt(:,g+1)] = fmincon(pk_function_objective,kp_opt(:,g),[],[],Aeq_calib,beq_calib,limit_inf_calib,limit_sup_calib,[],options); %#ok<AGROW>
    q_value{g+1}=zeros(size(q_value{g})); %#ok<AGROW>
    % Optimisation des coordonnées articulaires (Articular coordinates optimisation)
    for f=1:nb_frame_calib
        q0=q_value{g}(:,f);
        ik_function_objective=@(qvar)CostFunctionSymbolicCalib(...
            qvar,kp_opt(:,g+1),...
            OsteoArticularModel,real_markers_calib,f,list_function,list_function_markers,Base_position{f},Base_rotation{f},Rcut,pcut);
        nonlcon=@(qvar)ClosedLoopCalib(Base_position{f},Base_rotation{f},qvar,...
            kp_opt(:,g+1),...
            pcut,Rcut,nbClosedLoop);
        [q_value{g+1}(:,f)] = fmincon(ik_function_objective,q0,[],[],Aeq_ik,beq_ik,l_inf,l_sup,nonlcon,options);
    end
    % Calcul du critère d'arrêt (évolution de l'erreur)
    errorm{g+1}=zeros(numel(list_markers),nb_frame_calib); %#ok<AGROW>
    for f=1:nb_frame_calib
        [errorm{g+1}(:,f)] = ErrorMarkersCalib(q_value{g+1}(:,f),kp_opt(:,g+1),...
            OsteoArticularModel,real_markers_calib,f,list_markers,Base_position{f},Base_rotation{f},Rcut,pcut);
    end
    % Calcul du critère d'arret
    crit(:,g+1)=abs(mean(mean(errorm{g+1}))-mean(mean(errorm{g})))/mean(mean(errorm{g}));
    g=g+1; % incrémentation
end
calib_parameters.crit=crit;
calib_parameters.errorm=errorm;
%% Récupération des valeurs de k (matrice colonne) et p(cellules), et alpha
% Normalisé
kp_opt_unormalized=A_norm\(kp_opt(:,end)-b_norm);
calib_parameters.k_calib=k_map*[kp_opt_unormalized(1:nb_k,end); 1];
calib_parameters.p_calib=p_map*kp_opt_unormalized(nb_k+1:nb_k+nb_p,end);
calib_parameters.alpha_calib=alpha_map*kp_opt_unormalized(nb_k+nb_p+1:taille,end)*180/pi; % En degré !
calib_parameters.alpha_calib=...
[calib_parameters.alpha_calib(1:2:length(calib_parameters.alpha_calib)),...
calib_parameters.alpha_calib(2:2:length(calib_parameters.alpha_calib))]; %1ere rotation puis 2e dans la 2e colonne
%% Actualisation du modèle
% Actualiser le modèle avec les valeurs de k et p déterminés précédemment
% (à partir de Human_model_save) : sans 6dof (without 6DOF joint)
%% Model actualisation with obtained k and p values.
Human_model_calib=Human_model_save;
% k_calib %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for i=1:numel(Human_model_save)
    Human_model_calib(i).b=Human_model_save(i).b*calib_parameters.k_calib(OsteoArticularModel(i).mother); % b (k de la mère)
    Human_model_calib(i).c=Human_model_save(i).c*calib_parameters.k_calib(i); % c
    Human_model_calib(i).I=Human_model_save(i).I*calib_parameters.k_calib(i); % I
    for j=1:size(Human_model_save(i).anat_position,1)
        Human_model_calib(i).anat_position{j,2}=Human_model_save(i).anat_position{j,2}*calib_parameters.k_calib(i);
    end
end
% p_calib %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
m=0;
for i=1:numel(Markers_set)
    if Markers_set(i).exist
        m=m+1;
        Human_model_calib(Markers_set(i).num_solid).anat_position{Markers_set(i).num_markers,2} = ...
            Human_model_calib(Markers_set(i).num_solid).anat_position{Markers_set(i).num_markers,2} + ...
            calib_parameters.p_calib((3*(m-1)+1):(3*m),:)*calib_parameters.k_calib(Markers_set(i).num_solid);
    end
end
% alpha_calib %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if nb_alpha
    for j=1:numel(Human_model_save)
        if ~isempty(Human_model_calib(j).v)
            alpha_j=calib_parameters.alpha_calib(j,:)*pi/180;
            Human_model_calib(j).a = Rodrigues(Human_model_calib(j).v(:,2),alpha_j(2))*Rodrigues(Human_model_calib(j).v(:,1),alpha_j(1))*Human_model_calib(j).a;
        end
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Suppression des fonctions symboliques
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
rmpath('Symbolic_function')
rmdir('Symbolic_function','s')
end