Description of Get_real_markers
Get_real_markers
PURPOSE
Extraction of motion data
SYNOPSIS
function [real_markers, nb_frame, Firstframe, Lastframe,f] = Get_real_markers(filename,list_markers, AnalysisParameters)
DESCRIPTION
 Extraction of motion data
   INPUT
   - filename: name of the file to process (character string)
   - list_markers: list of the marker names
   - AnalysisParameters: parameters of the musculoskeletal analysis,
   automatically generated by the graphic interface 'Analysis'
   OUTPUT
   - real_markers: 3D position of experimental markers
   - nb_frame: number of frames
   - Firstframe: number of the first frame
   - Lastrfame: number of the last frame
   - f: acquisition frequency
________________________________________________________
 Licence
 Toolbox distributed under GPL 3.0 Licence
________________________________________________________
 Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
 Georges Dumont
________________________________________________________
CROSS-REFERENCE INFORMATION
This function calls:
filt_data 4-th order Butterworth low pass filter with no phase shift
This function is called by:
InverseKinematicsLM Computation of the inverse kinematics step thanks to a Jacobian matrix
InverseKinematicsOpti Computation of the inverse kinematics step thanks to a sqp optimization method
Get_real_markers_Calibration Extraction of motion data for the geometrical calibration
SOURCE CODE
function [real_markers, nb_frame, Firstframe, Lastframe,f] = Get_real_markers(filename,list_markers, AnalysisParameters)
% Extraction of motion data
%
%   INPUT
%   - filename: name of the file to process (character string)
%   - list_markers: list of the marker names
%   - AnalysisParameters: parameters of the musculoskeletal analysis,
%   automatically generated by the graphic interface 'Analysis'
%   OUTPUT
%   - real_markers: 3D position of experimental markers
%   - nb_frame: number of frames
%   - Firstframe: number of the first frame
%   - Lastrfame: number of the last frame
%   - f: acquisition frequency
%________________________________________________________
%
% Licence
% Toolbox distributed under GPL 3.0 Licence
%________________________________________________________
%
% Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
% Georges Dumont
%________________________________________________________
% Data extraction
[real_markers, nb_frame, Firstframe, Lastframe, f] = AnalysisParameters.General.InputData(filename, list_markers, AnalysisParameters.General.InputDataOptions);
% Filtrage (Filtering)
if AnalysisParameters.General.FilterActive
    for i=1:numel(real_markers)
        real_markers(i).position = filt_data(real_markers(i).position_c3d,AnalysisParameters.General.FilterCutOff,f);
    end
else
    for i=1:numel(real_markers)
        real_markers(i).position = real_markers(i).position_c3d;
    end
end
end