Description of btkReadAcquisition
btkReadAcquisition
PURPOSE
BTKREADACQUISITION Read an acquisition's file (C3D, TRC, ...)
SYNOPSIS
function h = btkReadAcquisition(filename) %#ok
DESCRIPTION
BTKREADACQUISITION Read an acquisition's file (C3D, TRC, ...)
  H = BTKREADACQUISITION(FILENAME) returns the handle H of a biomechanical
  acquisition stored in file FILENAME.  This handle is returned
  as a double and can be only used with the btk* function.
  The release of the memory associated with the handle H can be done automatically
  by Matlab when you use the command 'clear all', or you can use the function
  BTKDELETEACQUISITION.  The use of the function BTKDELETEACQUISITION is greatly
  advised when you are doing batch processing as Matlab does not manage the C++
  memory and an "Out of memory" error could be thrown.
  [H, BYTEORDER] = BTKREADACQUISITION(FILENAME) returns the byte order of the
  file as a string. The known values are:
   - OrderNotApplicable (In the case the file is an ASCII file).
   - IEEE_LittleEndian
   - VAX_LittleEndian
   - IEEE_BigEndian
  [H, BYTEORDER, STORAGEFORMAT] = BTKREADACQUISITION(FILENAME) returns the storage
  format of the file as a string. The known values are:
   - StorageNotApplicable (In the case the file is an ASCII file).
   - Float
   - Integer
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ColorsAnimation Preparing the colors for animation
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
btkTransformTDFToViconC3DFile BTKTRANSFORMTDFTOVICONC3DFILE transforms a TDF file (BTS Bioengineering) to a compatible Vicon C3D file.
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
btkTransformTDFToViconC3DFile BTKTRANSFORMTDFTOVICONC3DFILE transforms a TDF file (BTS Bioengineering) to a compatible Vicon C3D file.
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
btkTransformTDFToViconC3DFile BTKTRANSFORMTDFTOVICONC3DFILE transforms a TDF file (BTS Bioengineering) to a compatible Vicon C3D file.
C3dProcessedData Extraction of experimental data in a processed c3d
DataInC3D Computation of the external forces
SOURCE CODE
function h = btkReadAcquisition(filename) %#ok
%BTKREADACQUISITION Read an acquisition's file (C3D, TRC, ...)
%
%  H = BTKREADACQUISITION(FILENAME) returns the handle H of a biomechanical
%  acquisition stored in file FILENAME.  This handle is returned
%  as a double and can be only used with the btk* function.
%
%  The release of the memory associated with the handle H can be done automatically
%  by Matlab when you use the command 'clear all', or you can use the function
%  BTKDELETEACQUISITION.  The use of the function BTKDELETEACQUISITION is greatly
%  advised when you are doing batch processing as Matlab does not manage the C++
%  memory and an "Out of memory" error could be thrown.
%
%  [H, BYTEORDER] = BTKREADACQUISITION(FILENAME) returns the byte order of the
%  file as a string. The known values are:
%   - OrderNotApplicable (In the case the file is an ASCII file).
%   - IEEE_LittleEndian
%   - VAX_LittleEndian
%   - IEEE_BigEndian
%
%  [H, BYTEORDER, STORAGEFORMAT] = BTKREADACQUISITION(FILENAME) returns the storage
%  format of the file as a string. The known values are:
%   - StorageNotApplicable (In the case the file is an ASCII file).
%   - Float
%   - Integer
%  Author: A. Barré
%  Copyright 2009-2013 Biomechanical ToolKit (BTK).
% The following comment, MATLAB compiler pragma, is necessary to avoid
% compiling this M-file instead of linking against the MEX-file.  Don't remove.
%# mex
error(generatemsgid('NotSupported'),'MEX file for BTKREADACQUISITION not found');
% [EOF] btkReadAcquisition.m