Description of MVNX_V3
MVNX_V3
PURPOSE
Import MVNX file
SYNOPSIS
function [varargout] = MVNX_V3(varargin)
DESCRIPTION
 Import MVNX file
 Licence
 Toolbox distributed under GPL 3.0 Licence
________________________________________________________
 Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
 Georges Dumont
________________________________________________________
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
CalibrateModelGeneration Generation of the calibrated musculoskeletal model
CalibrateModelGenerationNum Generation of the calibrated musculoskeletal model
ExternalForcesPrediction Prediction of ground reaction forces
InverseKinematics Computation of the inverse kinematics step
SOURCE CODE
function [varargout] = MVNX_V3(varargin)
% Import MVNX file
%
% Licence
% Toolbox distributed under GPL 3.0 Licence
%________________________________________________________
%
% Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
% Georges Dumont
%________________________________________________________
varargout = cell(0);
end