Description of find_solid_path
find_solid_path
PURPOSE
Identification of the hierarchical path between two solids
SYNOPSIS
function [solid_1_path,solid_2_path]=find_solid_path(Human_model,i,k)
DESCRIPTION
 Identification of the hierarchical path between two solids
   INPUT
   - Human_model: osteo-articular model (see the Documentation for the
   structure)
   - i: number of the first solid
   - k: number of the second solid
   OUTPUT
   - solid_1_path: hierarchical path from first solid to nearest ancestor
   - solid_2_path: hierarchical path from second solid to nearest ancestor
________________________________________________________
 Licence
 Toolbox distributed under GPL 3.0 Licence
________________________________________________________
 Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
 Georges Dumont
________________________________________________________
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
distance_point Computation of the distance between two points
distance_point_wrap Computation of the distance between two points
AnimationFramebyFrame Computation of animation structure for animation
distance_point_anthropo Computation of the distance between a point and the center of mass of a solid
Symbolic_ForwardKinematicsCoupure_A Computation of a symbolic forward kinematics
Data_ClosedLoop Return data fixed by the model about closing loop
Symbolic_ForwardKinematicsCoupure Computation of a symbolic forward kinematics
ForwardKinematicsPoint Computation of the position of a point according to a reference solid
SUBFUNCTIONS
function solid_root_path=find_solid_root_path(Human_model,i,solid_root_path)
SOURCE CODE
function [solid_1_path,solid_2_path]=find_solid_path(Human_model,i,k)
% Identification of the hierarchical path between two solids
%
%   INPUT
%   - Human_model: osteo-articular model (see the Documentation for the
%   structure)
%   - i: number of the first solid
%   - k: number of the second solid
%   OUTPUT
%   - solid_1_path: hierarchical path from first solid to nearest ancestor
%   - solid_2_path: hierarchical path from second solid to nearest ancestor
%________________________________________________________
%
% Licence
% Toolbox distributed under GPL 3.0 Licence
%________________________________________________________
%
% Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
% Georges Dumont
%________________________________________________________
% Path to tree root starting from solid i
solid_1_root_path = find_solid_root_path(Human_model,i);
% Path to tree root starting from solid k
solid_2_root_path = find_solid_root_path(Human_model,k);
% Finding closest common solid to both root paths
common_ancestors = intersect(solid_1_root_path,solid_2_root_path);
nearest_ancestor = max(common_ancestors);
solid_1_ancestor_ind = find(solid_1_root_path==nearest_ancestor);
solid_2_ancestor_ind = find(solid_2_root_path==nearest_ancestor);
if i>k % Starting from smallest solid increment
    solid_1_path = solid_1_root_path(solid_1_ancestor_ind:end);
    solid_2_path = sort(solid_2_root_path(solid_2_ancestor_ind:end),'ascend');
else
    solid_1_path = solid_2_root_path(solid_2_ancestor_ind:end);
    solid_2_path = sort(solid_1_root_path(solid_1_ancestor_ind:end),'ascend');
end
% end
end
function solid_root_path=find_solid_root_path(Human_model,i,solid_root_path)
if nargin < 3   % if first incrementation
    solid_root_path=i;
    if i==1
        return
    end
elseif i==1
    solid_root_path = [1 solid_root_path];
    return
end
j=Human_model(i).mother; % number of the mother
solid_root_path=[j solid_root_path]; % Number (dent) of the mother is added into the global path
if j == 1  % If Mother corresponds to the solid that closes the loop
    return;
else
    [solid_root_path]=find_solid_root_path(Human_model,j,solid_root_path);
end
end