Description of Huygens
Huygens
PURPOSE
Computation of inertia matrix at point O
SYNOPSIS
function [Io] = Huygens(OG,Ig,m)
DESCRIPTION
 Computation of inertia matrix at point O
   INPUT
   - OG: location of the center of gravity (G) from point O
   - Ig: inertia matrix at point G
   - m: solid mass
   OUTPUT
   - Io: inertia matrix at point O
________________________________________________________
 Licence
 Toolbox distributed under GPL 3.0 Licence
________________________________________________________
 Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
 Georges Dumont
________________________________________________________
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
rgyration2inertia Computation of inertia matrix from radius of gyration
ShankFoot Addition of a shank/foot model
UpperTrunkHead Addition of an upper trunk / head model
torso_gait2354 CREDIT
SOURCE CODE
function [Io] = Huygens(OG,Ig,m)
% Computation of inertia matrix at point O
%
%   INPUT
%   - OG: location of the center of gravity (G) from point O
%   - Ig: inertia matrix at point G
%   - m: solid mass
%   OUTPUT
%   - Io: inertia matrix at point O
%________________________________________________________
%
% Licence
% Toolbox distributed under GPL 3.0 Licence
%________________________________________________________
%
% Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
% Georges Dumont
%________________________________________________________
Io=Ig+m*[OG(2)^2 + OG(3)^2 -OG(1)*OG(2) -OG(1)*OG(3);-OG(1)*OG(2) OG(1)^2+OG(3)^2 -OG(2)*OG(3);-OG(1)*OG(3) -OG(2)*OG(3) OG(1)^2+OG(2)^2];
end