Description of Rodrigues
Rodrigues
PURPOSE
Computation of the Rodrigues equation
SYNOPSIS
function R = Rodrigues(a,q)
DESCRIPTION
 Computation of the Rodrigues equation
   INPUT
   - a: axis of rotation
   - q: rotation angle
   OUTPUT
   - R: rotation matrix
________________________________________________________
 Licence
 Toolbox distributed under GPL 3.0 Licence
________________________________________________________
 Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
 Georges Dumont
________________________________________________________
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Rodrigues_from_two_axes Computation of the Rodrigues equation
distance_point Computation of the distance between two points
distance_point_wrap Computation of the distance between two points
ForwardKinematicsAnimation8 Computation of a forward kinematics step for the animation8
ForwardKinematicsAnimation8XSens Computation of a forward kinematics step for the animation8 (adapted for
DynCalibOptimization Calibration of the inertial parameters
distance_point_anthropo Computation of the distance between a point and the center of mass of a solid
GeometricalCalibration Calibration of the geometrical parameters
Symbolic_ForwardKinematicsCoupure_A Computation of a symbolic forward kinematics
ImportKinect Extraction of experimental data from a Kinect
BaseOfSupport Computation of the base of support
ForwardKinematics Forward kinematics
JointPositions
ForwardAllKinematics Computation of spacial position, velocity and acceleration for each solid
InverseDynamics Computation of the inverse dynamics step
Kinetics Computation of the kinetic energy
ExternalForcesPrediction Prediction of ground reaction forces
ForwardAllKinematicsPrediction Computation of spacial position, velocity and acceleration for each solid used for the prediction of ground reaction forces
ForwardKinematicsAnimation_Interf Computation of a forward kinematics step for the interface
ForwardKinematics_ClosedLoop Computation of a symbolic forward kinematics
ForwardPositions Computation of spacial position and rotation for each solid starting from
Symbolic_ForwardKinematicsCoupure Computation of a symbolic forward kinematics
ShankFoot Addition of a shank/foot model
ForwardKinematicsPoint Computation of the position of a point according to a reference solid
ForwardKinematicsR Computation of a forward kinematics step to obtained all matrix rotation
XSens_Visual Visual generation for XSens data
SOURCE CODE
function R = Rodrigues(a,q)
% Computation of the Rodrigues equation
%
%   INPUT
%   - a: axis of rotation
%   - q: rotation angle
%   OUTPUT
%   - R: rotation matrix
%________________________________________________________
%
% Licence
% Toolbox distributed under GPL 3.0 Licence
%________________________________________________________
%
% Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
% Georges Dumont
%________________________________________________________
if isequal(size(a),[0 0]) || isequal(size(q),[0 0])
    R=eye(3);
else
    ap=[0 -a(3) a(2);...
         a(3) 0 -a(1);...
        -a(2) a(1) 0];
    R=[1 0 0;0 1 0;0 0 1]+ap*sin(q)+ap*ap*(1-cos(q));
end
end