function [OsteoArticularModel]= Pelvis_gait2354(OsteoArticularModel,k,Mass,AttachmentPoint)

%	CREDIT
%   Delp S.L., Loan J.P., Hoy M.G., Zajac F.E., Topp E.L., Rosen J.M., Thelen D.G., Anderson F.C., Seth A. 
%   NOTES
%   3D, 23 DOF gait model created by D.G. Thelen, Univ. of Wisconsin-Madison, and Ajay Seth, Frank C. Anderson, and Scott L. Delp, Stanford University. Lower extremity joint defintions based on Delp et al. (1990). Low back joint and anthropometry based on Anderson and Pandy (1999, 2001). Planar knee model of Yamaguchi and Zajac (1989). Seth replaced tibia translation constraints with a CustomJoint for the knee and removed the patella to eliminate all kinematic constraints; insertions of the quadrucepts are handled with moving points in the tibia frame as defined by Delp 1990. 
%   LINK
%   http://simtk-confluence.stanford.edu:8080/display/OpenSim/Gait+2392+and+2354+Models
%   Based on: 
%   - Delp, S.L., Loan, J.P., Hoy, M.G., Zajac, F.E., Topp E.L., Rosen, J.M.: An interactive graphics-based model of the lower extremity to study orthopaedic surgical procedures, IEEE Transactions on Biomedical Engineering, vol. 37, pp. 757-767, 1990. 
%   - Yamaguchi G.T., Zajac F.E.: A planar model of the knee joint to characterize the knee extensor mechanism." J . Biomech. vol. 22. pp. 1-10. 1989. 
%   - Anderson F.C., Pandy M.G.: A dynamic optimization solution for vertical jumping in three dimensions. Computer Methods in Biomechanics and Biomedical Engineering 2:201-231, 1999. Anderson F.C., Pandy M.G.: Dynamic optimization of human walking. Journal of Biomechanical Engineering 123:381-390, 2001.
%   INPUT
%   - OsteoArticularModel: osteo-articular model of an already existing
%   model (see the Documentation for the structure)
%   - k: homothety coefficient for the geometrical parameters (defined as
%   the subject size in cm divided by 180)
%   - Signe: side of the thigh model ('R' for right side or 'L' for left side)
%   - Mass: mass of the solids
%   - AttachmentPoint: name of the attachment point of the model on the
%   already existing model (character string)
%   OUTPUT
%   - OsteoArticularModel: new osteo-articular model (see the Documentation
%   for the structure) 
%________________________________________________________
%
% Licence
% Toolbox distributed under GPL 3.0 Licence
%________________________________________________________
%
% Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
% Georges Dumont
%________________________________________________________

%% Variables de sortie :
% "enrichissement de la structure "Human_model""

list_solid={'pelvis'};

% %% Incrémentation du numéro des groupes
% n_group=0;
% for i=1:numel(OsteoArticularModel)
%     if size(OsteoArticularModel(i).Group) ~= [0 0] %#ok<BDSCA>
%         n_group=max(n_group,OsteoArticularModel(i).Group(1,1));
%     end
% end
% n_group=n_group+1;

%% Incrémentation de la numérotation des solides

s=size(OsteoArticularModel,2)+1;  %#ok<NASGU> % numéro du premier solide
for i=1:size(list_solid,2)      % numérotation de chaque solide : s_"nom du solide"
    if i==1
        eval(strcat('s_',list_solid{i},'=s;'))
    else
        eval(strcat('s_',list_solid{i},'=s_',list_solid{i-1},'+1;'))
    end
end

% trouver le numéro de la mère à partir du nom du point d'attache : 'attachment_pt'
if numel(OsteoArticularModel) == 0
    s_mother=0;
    pos_attachment_pt=[0 0 0]';
else
%     AttachmentPoint=varargin{1};
    test=0;
    for i=1:numel(OsteoArticularModel)
        for j=1:size(OsteoArticularModel(i).anat_position,1)
            if strcmp(AttachmentPoint,OsteoArticularModel(i).anat_position{j,1})
                s_mother=i;
                pos_attachment_pt=OsteoArticularModel(i).anat_position{j,2}+OsteoArticularModel(s_mother).c;
                test=1;
                break
            end
        end
        if i==numel(OsteoArticularModel) && test==0
            error([AttachmentPoint ' is no existent'])
        end
    end
    if OsteoArticularModel(s_mother).child == 0      % si la mère n'a pas d'enfant
        OsteoArticularModel(s_mother).child = eval(['s_' list_solid{1}]);    % l'enfant de cette mère est ce solide
    else
        [OsteoArticularModel]=sister_actualize(OsteoArticularModel,OsteoArticularModel(s_mother).child,eval(['s_' list_solid{1}]));   % recherche de la dernière soeur
    end
end

%% ------------------------- Pelvis ----------------------------------------

% Position du CoM par rapport au repère de centré au milieu RASIS-LASIS
CoM_Pelvis = k*[-0.0707 0 0]';

%milieu de RASIS et ASIS dans le repère centré à la hanche droite
Hip_midRASISASIS = k*[0; 0; 0]-CoM_Pelvis;

% Position des noeuds dans le repère centré au milieu de RASIS et ASIS
Pelvis_HipJointRightNode = k*[-0.0707 -0.0661 0.0835]'                        - CoM_Pelvis;
Pelvis_HipJointLeftNode = k*[-0.0707 -0.0661 -0.0835]'                          - CoM_Pelvis;
Pelvis_HipJointsCenterNode = (Pelvis_HipJointLeftNode+Pelvis_HipJointRightNode)/2-CoM_Pelvis;

% ------------------------- Sacrum ----------------------------------------

% Position des noeuds
% Sacrum_L5JointNode = k*[-65;30;0]/1000- CoM_Pelvis; % Défini à la main sur la géométrie du Sacrum .STL

Pelvis_L5JointNode = k*[-0.1007 0.0815 0]'-CoM_Pelvis;
LowerTrunk_UpperTrunkNode = k*[-0.1007 0.0815 0]'-CoM_Pelvis;

%% Définition des positions anatomiques

Pelvis_position_set= {...
    'RFWT',k*([0.02;0.03;0.128])-CoM_Pelvis;...
    'LFWT',k*([0.02;0.03;-0.128])-CoM_Pelvis;...
    'V.Sacral',k*([-0.16;0.04;0])-CoM_Pelvis;...
    'LBWT',                     (k*[-0.08;0.0361;-0.055]); ...
    'RBWT',                     (k*[-0.08;0.0361;0.055]); ...
    ...%'RightPubicTubercle', ((k*[0.0489;	-0.0032;	-0.0853]-Hip_midRASISASIS)   -CoM_Pelvis); ...
    ...%'LeftPubicTubercle', ([1 0 0;0 1 0;0 0 -1]*(k*[0.0489;	-0.0032;	-0.0853]-Hip_midRASISASIS )  -CoM_Pelvis); ...
    'Pelvis_HipJointRightNode', Pelvis_HipJointRightNode; ...
    'Pelvis_HipJointLeftNode',  Pelvis_HipJointLeftNode; ...
    'Pelvis_LowerTrunkNode',    Pelvis_L5JointNode; ...
        'Pelvis_L5JointNode', Pelvis_L5JointNode; ...
    'Pelvis_HipJointsCenterNode', Pelvis_HipJointsCenterNode; ...
    'CoMPelvis',                [0; 0; 0];...
    'Hip_midRASISASIS',Hip_midRASISASIS;...
    'LowerTrunk_UpperTrunkNode',LowerTrunk_UpperTrunkNode;...
    };


Pelvis_position_set = [Pelvis_position_set;...
    {...
    ['glut_med1_r-P1'],k*([-0.0408;0.0304;0.1209])-CoM_Pelvis;...
    ['glut_med2_r-P1'],k*([-0.0855;0.0445;0.0766])-CoM_Pelvis;...
    ['glut_med3_r-P1'],k*([-0.1223;0.0105;0.0648])-CoM_Pelvis;...
    ['bifemlh_r-P1'],k*([-0.12596;-0.10257;0.06944])-CoM_Pelvis;...
    ['sar_r-P1'],k*([-0.0153;-0.0013;0.1242])-CoM_Pelvis;...
    ['add_mag2_r-P1'],k*([-0.0831;-0.1192;0.0308])-CoM_Pelvis;...
    ['tfl_r-P1'],k*([-0.0311;0.0214;0.1241])-CoM_Pelvis;...
    ['pect_r-P1'],k*([-0.0431;-0.0768;0.0451])-CoM_Pelvis;...
    ['grac_r-P1'],k*([-0.07401;-0.1187;0.02794])-CoM_Pelvis;...
    ['glut_max1_r-P1'],k*([-0.1195;0.0612;0.07])-CoM_Pelvis;...
    ['glut_max1_r-P2'],k*([-0.1291;0.0012;0.0886])-CoM_Pelvis;...
    ['glut_max2_r-P1'],k*([-0.1349;0.0176;0.0563])-CoM_Pelvis;...
    ['glut_max2_r-P2'],k*([-0.1376;-0.052;0.0914])-CoM_Pelvis;...
    ['glut_max3_r-P1'],k*([-0.1556;-0.0314;0.0058])-CoM_Pelvis;...
    ['glut_max3_r-P2'],k*([-0.1529;-0.1052;0.0403])-CoM_Pelvis;...
    ['iliacus_r-P1'],k*([-0.0674;0.0365;0.0854])-CoM_Pelvis;...
    ['iliacus_r-P2'],k*([-0.0258;-0.055;0.0811])-CoM_Pelvis;...
    ['psoas_r-P1'],k*([-0.0647;0.0887;0.0289])-CoM_Pelvis;...
    ['psoas_r-P2'],k*([-0.0238;-0.057;0.0759])-CoM_Pelvis;...
    ['quad_fem_r-P1'],k*([-0.1143;-0.1151;0.052])-CoM_Pelvis;...
    ['gem_r-P1'],k*([-0.1133;-0.082;0.0714])-CoM_Pelvis;...
    ['peri_r-P1'],k*([-0.1396;0.0003;0.0235])-CoM_Pelvis;...
    ['peri_r-P2'],k*([-0.1193;-0.0276;0.0657])-CoM_Pelvis;...
    ['rect_fem_r-P1'],k*([-0.0295;-0.0311;0.0968])-CoM_Pelvis;...
    ['glut_med1_l-P1'],k*([-0.0408;0.0304;-0.1209])-CoM_Pelvis;...
    ['glut_med2_l-P1'],k*([-0.0855;0.0445;-0.0766])-CoM_Pelvis;...
    ['glut_med3_l-P1'],k*([-0.1223;0.0105;-0.0648])-CoM_Pelvis;...
    ['bifemlh_l-P1'],k*([-0.12596;-0.10257;-0.06944])-CoM_Pelvis;...
    ['sar_l-P1'],k*([-0.0153;-0.0013;-0.1242])-CoM_Pelvis;...
    ['add_mag2_l-P1'],k*([-0.0831;-0.1192;-0.0308])-CoM_Pelvis;...
    ['tfl_l-P1'],k*([-0.0311;0.0214;-0.1241])-CoM_Pelvis;...
    ['pect_l-P1'],k*([-0.0431;-0.0768;-0.0451])-CoM_Pelvis;...
    ['grac_l-P1'],k*([-0.07401;-0.1187;-0.02794])-CoM_Pelvis;...
    ['glut_max1_l-P1'],k*([-0.1195;0.0612;-0.07])-CoM_Pelvis;...
    ['glut_max1_l-P2'],k*([-0.1291;0.0012;-0.0886])-CoM_Pelvis;...
    ['glut_max2_l-P1'],k*([-0.1349;0.0176;-0.0563])-CoM_Pelvis;...
    ['glut_max2_l-P2'],k*([-0.1376;-0.052;-0.0914])-CoM_Pelvis;...
    ['glut_max3_l-P1'],k*([-0.1556;-0.0314;-0.0058])-CoM_Pelvis;...
    ['glut_max3_l-P2'],k*([-0.1529;-0.1052;-0.0403])-CoM_Pelvis;...
    ['iliacus_l-P1'],k*([-0.0674;0.0365;-0.0854])-CoM_Pelvis;...
    ['iliacus_l-P2'],k*([-0.0258;-0.055;-0.0811])-CoM_Pelvis;...
    ['psoas_l-P1'],k*([-0.0647;0.0887;-0.0289])-CoM_Pelvis;...
    ['psoas_l-P2'],k*([-0.0238;-0.057;-0.0759])-CoM_Pelvis;...
    ['quad_fem_l-P1'],k*([-0.1143;-0.1151;-0.052])-CoM_Pelvis;...
    ['gem_l-P1'],k*([-0.1133;-0.082;-0.0714])-CoM_Pelvis;...
    ['peri_l-P1'],k*([-0.1396;0.0003;-0.0235])-CoM_Pelvis;...
    ['peri_l-P2'],k*([-0.1193;-0.0276;-0.0657])-CoM_Pelvis;...
    ['rect_fem_l-P1'],k*([-0.0295;-0.0311;-0.0968])-CoM_Pelvis;...
    ['ercspn_r-P1'],k*([-0.14;0.0439;0.0436])-CoM_Pelvis;...
    ['ercspn_l-P1'],k*([-0.14;0.0439;-0.0436])-CoM_Pelvis;...
    ['intobl_r-P1'],k*([-0.04;0.07;0.1157])-CoM_Pelvis;...
    ['intobl_l-P1'],k*([-0.04;0.07;-0.1157])-CoM_Pelvis;...
    ['extobl_r-P1'],k*([-0.03;-0.0636;0.01])-CoM_Pelvis;...
    ['extobl_l-P1'],k*([-0.03;-0.0636;-0.01])-CoM_Pelvis;...
    }]; %#ok<AGROW>

%%                     Mise à l'échelle des inerties

    %% ["Adjustments to McConville et al. and Young et al. body segment inertial parameters"] R. Dumas
    % ------------------------- Pelvis ----------------------------------------
    Length_Pelvis = norm(Pelvis_HipJointsCenterNode-Pelvis_L5JointNode);
    [I_Pelvis]=rgyration2inertia([100 107 95 25*1i 12*1i 8*1i], Mass.Pelvis_Mass, [0 0 0], Length_Pelvis);

%% Création de la structure "Human_model"

num_solid=0;
%% Pelvis
% Pelvis
num_solid=num_solid+1;        % solide numéro ...
name=list_solid{num_solid}; % nom du solide
eval(['incr_solid=s_' name ';'])  % numéro du solide dans le modèle
OsteoArticularModel(incr_solid).name=name;               % nom du solide
OsteoArticularModel(incr_solid).sister=0;                      % sister
OsteoArticularModel(incr_solid).child=0;       % child
OsteoArticularModel(incr_solid).mother=s_mother;                      % mother
OsteoArticularModel(incr_solid).a=[0 0 0]';                    % axe de rotation
OsteoArticularModel(incr_solid).joint=1;                       % type d'articulation : 1:pivot / 2:glissière
OsteoArticularModel(incr_solid).calib_k_constraint=[];         % initialisation des contraintes d'optimisation pour la calibration de la longueur des membres
OsteoArticularModel(incr_solid).u=[];                          % rotation fixe selon l'axe u d'un angle theta (après la rotation q)
OsteoArticularModel(incr_solid).theta=[];
OsteoArticularModel(incr_solid).KinematicsCut=[];              % coupure cinématique
OsteoArticularModel(incr_solid).ClosedLoop=[];                 % si solide de fermeture de boucle : {numéro du solide i sur lequel est attaché ce solide ; point d'attache (repère du solide i)}
OsteoArticularModel(incr_solid).ActiveJoint=1;                 % 1 si articulation active / 0 si articulation passive
OsteoArticularModel(incr_solid).Visual=1;                      % 1 si il y a un visuel associé / 0 sinon
% OsteoArticularModel(incr_solid).Group=[n_group 1];                   % groupe pour la calibration dynamique
OsteoArticularModel(incr_solid).b=pos_attachment_pt;                    % position du point d'attache par rapport au repère parent
OsteoArticularModel(incr_solid).c=[0 0 0]';                    % position du centre de masse dans le repère local
OsteoArticularModel(incr_solid).m=Mass.Pelvis_Mass;                 % masse
OsteoArticularModel(incr_solid).I=[I_Pelvis(1) I_Pelvis(4) I_Pelvis(5); I_Pelvis(4) I_Pelvis(2) I_Pelvis(6); I_Pelvis(5) I_Pelvis(6) I_Pelvis(3)];                  % matrice d'inertie de référence
OsteoArticularModel(incr_solid).anat_position=Pelvis_position_set;
OsteoArticularModel(incr_solid).linear_constraint=[];
OsteoArticularModel(incr_solid).L={'Pelvis_HipJointsCenterNode';'Pelvis_LowerTrunkNode'};
OsteoArticularModel(incr_solid).v= [] ;
OsteoArticularModel(incr_solid).visual_file = ['gait2354/pelvis.mat'];

end
