Description of btkGetFirstFrame
btkGetFirstFrame
PURPOSE
BTKGETFIRSTFRAME Returns acquisition's first frame index.
SYNOPSIS
function ff = btkGetFirstFrame(h) %#ok
DESCRIPTION
BTKGETFIRSTFRAME Returns acquisition's first frame index.
  FF = BTKGETFIRSTFRAME(H) returns the first frame index of the acquisition.
  The acquistion is represented by the handle H, obtained by the use of a
  btk* function.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
btkCropAcquisition BTKCROPACQUISITION Crop the acquisition and adapt the events' frame/time.
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
btkGetLastFrame BTKGETLASTFRAME Returns acquisition's last frame index.
btkCropAcquisition BTKCROPACQUISITION Crop the acquisition and adapt the events' frame/time.
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
btkGetLastFrame BTKGETLASTFRAME Returns acquisition's last frame index.
btkCropAcquisition BTKCROPACQUISITION Crop the acquisition and adapt the events' frame/time.
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
btkGetLastFrame BTKGETLASTFRAME Returns acquisition's last frame index.
C3dProcessedData Extraction of experimental data in a processed c3d
SOURCE CODE
function ff = btkGetFirstFrame(h) %#ok
%BTKGETFIRSTFRAME Returns acquisition's first frame index.
%
%  FF = BTKGETFIRSTFRAME(H) returns the first frame index of the acquisition.
%  The acquistion is represented by the handle H, obtained by the use of a
%  btk* function.
%  Author: A. Barré
%  Copyright 2009-2013 Biomechanical ToolKit (BTK).
% The following comment, MATLAB compiler pragma, is necessary to avoid
% compiling this M-file instead of linking against the MEX-file.  Don't remove.
%# mex
error(generatemsgid('NotSupported'),'MEX file for BTKGETFIRSTFRAME not found');
% [EOF] btkGetFirstFrame.m