Description of btkEmulateC3Dserver
btkEmulateC3Dserver
PURPOSE
BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
SYNOPSIS
function itf = btkEmulateC3Dserver()
DESCRIPTION
BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
  ITF = BTKEMULATEC3DSERVER() returns a structure which emulates the COM
  object generated by the function 'actxserver('C3Dserver.C3D')'. So, it gives
  the possibility to run scripts which use C3Dserver by using BTK.
  However, BTK did't make the same choice than C3Dserver to extract C3D
  informations. Then, you will find some slight differences between both:
    - This emulation use function handles and then required for every
      functions to be used with parenthesis (you cannot call 'itf.Close'
      but 'itf.Close()'). Use parenthesis keep your code compatible with
      C3Dserver.
    - A C3D file is always opened in mode 3.
    - The event's status is not kept in BTK. Using the following code:
      'itf.SetEventStatus(0,'0')' sends a warning and do nothing. To remove
      the warning, you have to add this command:
      'warning('OFF','btk:C3Dserver:SetEventStatus')'
    - The group and parameter number are generated from the index instead
      of using the ID stored in the C3D file. Like that, the user doesn't
      need to manage this number. So, if you set the group or parameter
      number, a warning will inform you of the impossibility to do it. To
      remove this warning, type the following command:
      'warning('OFF','btk:C3Dserver:UniqueNumber')'
      Removing this warning has an effect on the functions
      SetGroupNumber, SetParameterNumber. But also on the function AddGroup
      when you set manually the number.
    - The function 'CompressParameterBlocks' is alway activated in BTK as the
      the number of blocks needed for the groups/parameters is automatically
      adapted when you write the C3D. Trying to deactivate the compression
      (by using CompressParameterBlocks(0)) will send a warning. To remove the
      warning, you have to add the command:
      'warning('OFF','btk:C3Dserver:CompressParameterBlocks')'.
    - If some groups and parameters has the same name in the C3D file (which
      is the case with the group PROCESSING and its parameter for C3D files
      generated with Vicon Nexus 1.4), then BTK removes the duplication
      (which is not the case of C3Dserver).
    - When you delete a group, it is not possible to keep the associated
      parameters (They are stored in the group). If you try to do it, then
      a warning will be displayed and the parameters are removed. To remove the
      warning, use the command: 'warning('OFF','btk:C3Dserver:DeleteGroup')'.
    - The parameters are sorted by groups. Then if you select parameter by
      using hardcoded indices, you could have unexpected results.
    - The parameters' values are managed automatically inside BTK. In the
      case of parameter with the type 'Char', BTK trims (remove leading and
      trailing white space) values when you open the C3D file. If you set
      a number in a parameter with the type Char, then the number is
      converted into a string.
    - When you modify the parameter's type, then BTK adapts its values. In
      lots of conversion you can come back to the original value. However,
      transforming a string which doesn't contain a number creates the
      value 0. If you convert a Real into an Integer, you lost the
      floating information. If you convert an Integer into a Byte and the
      value is not in the range [-128, 127], then you lost the most
      significant part of the number.
      For example, the conversion (Char->Integer) for 'FOO' creates the
      number 0. But the conversion (Char->Integer) for '1234' creates the
      number 1234. The conversion (Integer->Byte) for the number 12456
      creates the number 168.
    - Modifying the parameter's type, adapts also its dimensions.
      For example, transforming a integer parameter into a char parameter
      add 1 dimension corresponding to the number of characters. Or, in
      the other case, transforming a char parameter into an integer,
      remove.
    - Retrieving a parameter in another index than the original will keep
      the group for this index.
    - Trying to retrieve a parameter which has the same name than one in
      the destination group (other than the original group) will throw an
      error.
    - An AV ratio equal to 0 in BTK is automatically converted to 1. The
      number of analog frames is at least equal to the number of video
      frames.
    - Starting with BTK 0.2, the camera mask is no longer supported. Trying
      to extract or set a mask will display a warning. The returned masks
      from the functions GetPointMask and GetPointMaskEx are fake masks and
      always set to '0000000'. To remove the warning, you have to add
      the command: 'warning('OFF','btk:C3Dserver:FakeMask')'.
CROSS-REFERENCE INFORMATION
This function calls:
btkGetForcePlatformWrenches BTKGETFORCEPLATFORMWRENCHES Extract force platform wrenches (FPW) from a biomechanical acquisition in the global frame.
btkGetGroundReactionWrenches BTKGETGROUNDREACTIONWRENCHES Extract ground reaction wrenches (GRW) from a biomechanical acquisition in the global frame.
btkAppendAnalog BTKAPPENDANALOG Append a new analog channel and return an updated list of analog channels.
btkAppendEvent BTKAPPENDEVENT Append a new event and return an updated list of events.
btkAppendMetaData BTKAPPENDMETADATA Append a new metada and return an updated list of the metadata in the acquisition.
btkAppendPoint BTKAPPENDPOINT Append a new point and return an updated list of points.
btkDeleteAcquisition BTKDELETEACQUISITION Deletes the acquisiton associated to the handle.
btkGetAnalog BTKGETANALOG Extract one analog channel from a biomechanical acquisition
btkGetAnalogFrameNumber BTKGETANALOGFRAMENUMBER Returns the number of frames for the analog channels.
btkGetAnalogNumber BTKGETANALOGNUMBER Returns the number of analog channels.
btkGetAnalogSampleNumberPerFrame BTKGETANALOGSAMPLENUMBERPERFRAME Return the number of analog samples per video frame.
btkGetAnalogsValues BTKGETANALOGSVALUES Extract analog channels' values and store them in a matrix
btkGetEventsValues BTKGETEVENTSVALUES Extract events' values from a biomechanical acquisition
btkGetFirstFrame BTKGETFIRSTFRAME Returns acquisition's first frame index.
btkGetMaxInterpolationGap BTKGETMAXINTERPOLATIONGAP Returns acquisition's maximum interpolation gap.
btkGetMetaData btkGetMetaData Extract acquisition's metadata
btkGetPoint BTKGETPOINT Get point's data.
btkGetPointFrameNumber BTKGETPOINTFRAMENUMBER Returns the number of frames for the points.
btkGetPointFrequency BTKGETPOINTFREQUENCY Returns the point's frequency.
btkGetPointNumber BTKGETPOINTNUMBER Returns number of points.
btkGetPointsResiduals BTKGETPOINTSRESIDUALS Extract points' residuals and store them in a matrix
btkGetPointsValues BTKGETPOINTSVALUES Extract points' components and store them in a matrix
btkNewAcquisition BTKNEWACQUISITION Create a new and initialized acquisition
btkRemoveAnalog BTKREMOVEANALOG Delete the analog channel with the given index or label.
btkRemoveEvent BTKREMOVEEVENT Delete events corresponding to the given criterias.
btkRemoveMetaData BTKREMOVEMETADATA Remove a metada and return an updated list of the metada in the acquisition.
btkRemovePoint BTKREMOVEPOINT Delete the point with the given index or label.
btkSetAnalogGain BTKSETANALOGGAIN Modify analog's gain and return updated analogs.
btkSetAnalogOffset BTKSETANALOGOFFSET Modify analog's offset and return updated analogs.
btkSetAnalogSampleNumberPerFrame BTKSETANALOGSAMPLENUMBERPERFRAME Set the number of analog sample per 3D frame
btkSetAnalogScale BTKSETANALOGSCALE Modify analog's scale and return updated analogs.
btkSetAnalogValues BTKSETANALOGVALUES Modify analog's value and return updated analogs.
btkSetAnalogsValues BTKSETANALOGSVALUES Sets analog channels' values from a matrix
btkSetEventLabel BTKSETEVENTLABEL Modify the label of the selected event.
btkSetEventTime BTKSETEVENTTIME Modify the time of the selected event.
btkSetFrameNumber BTKSETFRAMENUMBER Set points and analogs frames number.
btkSetFrequency BTKSETFREQUENCY Set the main frequency.
btkSetMaxInterpolationGap BTKSETMAXINTERPOLATIONGAP Set acquisition's maximum interpolation gap.
btkSetMetaDataDescription BTKSETMETADATADESCRIPTION Set a metadata's description.
btkSetMetaDataDimensions BTKSETMETADATADIMENSIONS Set metadata's dimensions.
btkSetMetaDataFormat BTKSETMETADATAFORMAT Set a metadata's format.
btkSetMetaDataLabel BTKSETMETADATALABEL Set a metadata's label
btkSetMetaDataUnlock BTKSETMETADATAUNLOCK Set the unlock state of a metadata.
btkSetMetaDataValue BTKSETMETADATAVALUE Set one metada's value.
btkSetPointResiduals BTKSETPOINTRESIDUALS Sets point's residuals from a row vector
btkSetPointValues BTKSETPOINTVALUES Sets point's coordinates (values) from a matrix
btkSetPointsResiduals BTKSETPOINTSRESIDUALS Sets points' residuals from a matrix
btkSetPointsValues BTKSETPOINTSVALUES Sets points' components from a matrix
btkReadAcquisition BTKREADACQUISITION Read an acquisition's file (C3D, TRC, ...)
btkWriteAcquisition BTKWRITEACQUISITION Write acquisition's data into file (C3D, TRC, ...)
btkFindMetaData BTKFINDMETADATA Return the searched metadata or 0 if not found.
btkGetEventNumber BTKGETEVENTNUMBER Return the number of events.
btkGetLastFrame BTKGETLASTFRAME Returns acquisition's last frame index.
btkGetVersion V = BTKGETVERSION returns the release number of BTK.
btkMetaDataInfo BTKMETADATAINFO Create a structure containing the required fields for the informations of a metadata.
btkGetForcePlatformWrenches BTKGETFORCEPLATFORMWRENCHES Extract force platform wrenches (FPW) from a biomechanical acquisition in the global frame.
btkGetGroundReactionWrenches BTKGETGROUNDREACTIONWRENCHES Extract ground reaction wrenches (GRW) from a biomechanical acquisition in the global frame.
btkAppendAnalog BTKAPPENDANALOG Append a new analog channel and return an updated list of analog channels.
btkAppendEvent BTKAPPENDEVENT Append a new event and return an updated list of events.
btkAppendMetaData BTKAPPENDMETADATA Append a new metada and return an updated list of the metadata in the acquisition.
btkAppendPoint BTKAPPENDPOINT Append a new point and return an updated list of points.
btkDeleteAcquisition BTKDELETEACQUISITION Deletes the acquisiton associated to the handle.
btkGetAnalog BTKGETANALOG Extract one analog channel from a biomechanical acquisition
btkGetAnalogFrameNumber BTKGETANALOGFRAMENUMBER Returns the number of frames for the analog channels.
btkGetAnalogNumber BTKGETANALOGNUMBER Returns the number of analog channels.
btkGetAnalogSampleNumberPerFrame BTKGETANALOGSAMPLENUMBERPERFRAME Return the number of analog samples per video frame.
btkGetAnalogsValues BTKGETANALOGSVALUES Extract analog channels' values and store them in a matrix
btkGetEventsValues BTKGETEVENTSVALUES Extract events' values from a biomechanical acquisition
btkGetFirstFrame BTKGETFIRSTFRAME Returns acquisition's first frame index.
btkGetMaxInterpolationGap BTKGETMAXINTERPOLATIONGAP Returns acquisition's maximum interpolation gap.
btkGetMetaData btkGetMetaData Extract acquisition's metadata
btkGetPoint BTKGETPOINT Get point's data.
btkGetPointFrameNumber BTKGETPOINTFRAMENUMBER Returns the number of frames for the points.
btkGetPointFrequency BTKGETPOINTFREQUENCY Returns the point's frequency.
btkGetPointNumber BTKGETPOINTNUMBER Returns number of points.
btkGetPointsResiduals BTKGETPOINTSRESIDUALS Extract points' residuals and store them in a matrix
btkGetPointsValues BTKGETPOINTSVALUES Extract points' components and store them in a matrix
btkNewAcquisition BTKNEWACQUISITION Create a new and initialized acquisition
btkRemoveAnalog BTKREMOVEANALOG Delete the analog channel with the given index or label.
btkRemoveEvent BTKREMOVEEVENT Delete events corresponding to the given criterias.
btkRemoveMetaData BTKREMOVEMETADATA Remove a metada and return an updated list of the metada in the acquisition.
btkRemovePoint BTKREMOVEPOINT Delete the point with the given index or label.
btkSetAnalogGain BTKSETANALOGGAIN Modify analog's gain and return updated analogs.
btkSetAnalogOffset BTKSETANALOGOFFSET Modify analog's offset and return updated analogs.
btkSetAnalogSampleNumberPerFrame BTKSETANALOGSAMPLENUMBERPERFRAME Set the number of analog sample per 3D frame
btkSetAnalogScale BTKSETANALOGSCALE Modify analog's scale and return updated analogs.
btkSetAnalogValues BTKSETANALOGVALUES Modify analog's value and return updated analogs.
btkSetAnalogsValues BTKSETANALOGSVALUES Sets analog channels' values from a matrix
btkSetEventLabel BTKSETEVENTLABEL Modify the label of the selected event.
btkSetEventTime BTKSETEVENTTIME Modify the time of the selected event.
btkSetFrameNumber BTKSETFRAMENUMBER Set points and analogs frames number.
btkSetFrequency BTKSETFREQUENCY Set the main frequency.
btkSetMaxInterpolationGap BTKSETMAXINTERPOLATIONGAP Set acquisition's maximum interpolation gap.
btkSetMetaDataDescription BTKSETMETADATADESCRIPTION Set a metadata's description.
btkSetMetaDataDimensions BTKSETMETADATADIMENSIONS Set metadata's dimensions.
btkSetMetaDataFormat BTKSETMETADATAFORMAT Set a metadata's format.
btkSetMetaDataLabel BTKSETMETADATALABEL Set a metadata's label
btkSetMetaDataUnlock BTKSETMETADATAUNLOCK Set the unlock state of a metadata.
btkSetMetaDataValue BTKSETMETADATAVALUE Set one metada's value.
btkSetPointResiduals BTKSETPOINTRESIDUALS Sets point's residuals from a row vector
btkSetPointValues BTKSETPOINTVALUES Sets point's coordinates (values) from a matrix
btkSetPointsResiduals BTKSETPOINTSRESIDUALS Sets points' residuals from a matrix
btkSetPointsValues BTKSETPOINTSVALUES Sets points' components from a matrix
btkReadAcquisition BTKREADACQUISITION Read an acquisition's file (C3D, TRC, ...)
btkWriteAcquisition BTKWRITEACQUISITION Write acquisition's data into file (C3D, TRC, ...)
btkFindMetaData BTKFINDMETADATA Return the searched metadata or 0 if not found.
btkGetEventNumber BTKGETEVENTNUMBER Return the number of events.
btkGetLastFrame BTKGETLASTFRAME Returns acquisition's last frame index.
btkGetVersion V = BTKGETVERSION returns the release number of BTK.
btkMetaDataInfo BTKMETADATAINFO Create a structure containing the required fields for the informations of a metadata.
btkGetForcePlatformWrenches BTKGETFORCEPLATFORMWRENCHES Extract force platform wrenches (FPW) from a biomechanical acquisition in the global frame.
btkGetGroundReactionWrenches BTKGETGROUNDREACTIONWRENCHES Extract ground reaction wrenches (GRW) from a biomechanical acquisition in the global frame.
btkAppendAnalog BTKAPPENDANALOG Append a new analog channel and return an updated list of analog channels.
btkAppendEvent BTKAPPENDEVENT Append a new event and return an updated list of events.
btkAppendMetaData BTKAPPENDMETADATA Append a new metada and return an updated list of the metadata in the acquisition.
btkAppendPoint BTKAPPENDPOINT Append a new point and return an updated list of points.
btkDeleteAcquisition BTKDELETEACQUISITION Deletes the acquisiton associated to the handle.
btkGetAnalog BTKGETANALOG Extract one analog channel from a biomechanical acquisition
btkGetAnalogFrameNumber BTKGETANALOGFRAMENUMBER Returns the number of frames for the analog channels.
btkGetAnalogNumber BTKGETANALOGNUMBER Returns the number of analog channels.
btkGetAnalogSampleNumberPerFrame BTKGETANALOGSAMPLENUMBERPERFRAME Return the number of analog samples per video frame.
btkGetAnalogsValues BTKGETANALOGSVALUES Extract analog channels' values and store them in a matrix
btkGetEventsValues BTKGETEVENTSVALUES Extract events' values from a biomechanical acquisition
btkGetFirstFrame BTKGETFIRSTFRAME Returns acquisition's first frame index.
btkGetMaxInterpolationGap BTKGETMAXINTERPOLATIONGAP Returns acquisition's maximum interpolation gap.
btkGetMetaData btkGetMetaData Extract acquisition's metadata
btkGetPoint BTKGETPOINT Get point's data.
btkGetPointFrameNumber BTKGETPOINTFRAMENUMBER Returns the number of frames for the points.
btkGetPointFrequency BTKGETPOINTFREQUENCY Returns the point's frequency.
btkGetPointNumber BTKGETPOINTNUMBER Returns number of points.
btkGetPointsResiduals BTKGETPOINTSRESIDUALS Extract points' residuals and store them in a matrix
btkGetPointsValues BTKGETPOINTSVALUES Extract points' components and store them in a matrix
btkNewAcquisition BTKNEWACQUISITION Create a new and initialized acquisition
btkRemoveAnalog BTKREMOVEANALOG Delete the analog channel with the given index or label.
btkRemoveEvent BTKREMOVEEVENT Delete events corresponding to the given criterias.
btkRemoveMetaData BTKREMOVEMETADATA Remove a metada and return an updated list of the metada in the acquisition.
btkRemovePoint BTKREMOVEPOINT Delete the point with the given index or label.
btkSetAnalogGain BTKSETANALOGGAIN Modify analog's gain and return updated analogs.
btkSetAnalogOffset BTKSETANALOGOFFSET Modify analog's offset and return updated analogs.
btkSetAnalogSampleNumberPerFrame BTKSETANALOGSAMPLENUMBERPERFRAME Set the number of analog sample per 3D frame
btkSetAnalogScale BTKSETANALOGSCALE Modify analog's scale and return updated analogs.
btkSetAnalogValues BTKSETANALOGVALUES Modify analog's value and return updated analogs.
btkSetAnalogsValues BTKSETANALOGSVALUES Sets analog channels' values from a matrix
btkSetEventLabel BTKSETEVENTLABEL Modify the label of the selected event.
btkSetEventTime BTKSETEVENTTIME Modify the time of the selected event.
btkSetFrameNumber BTKSETFRAMENUMBER Set points and analogs frames number.
btkSetFrequency BTKSETFREQUENCY Set the main frequency.
btkSetMaxInterpolationGap BTKSETMAXINTERPOLATIONGAP Set acquisition's maximum interpolation gap.
btkSetMetaDataDescription BTKSETMETADATADESCRIPTION Set a metadata's description.
btkSetMetaDataDimensions BTKSETMETADATADIMENSIONS Set metadata's dimensions.
btkSetMetaDataFormat BTKSETMETADATAFORMAT Set a metadata's format.
btkSetMetaDataLabel BTKSETMETADATALABEL Set a metadata's label
btkSetMetaDataUnlock BTKSETMETADATAUNLOCK Set the unlock state of a metadata.
btkSetMetaDataValue BTKSETMETADATAVALUE Set one metada's value.
btkSetPointResiduals BTKSETPOINTRESIDUALS Sets point's residuals from a row vector
btkSetPointValues BTKSETPOINTVALUES Sets point's coordinates (values) from a matrix
btkSetPointsResiduals BTKSETPOINTSRESIDUALS Sets points' residuals from a matrix
btkSetPointsValues BTKSETPOINTSVALUES Sets points' components from a matrix
btkReadAcquisition BTKREADACQUISITION Read an acquisition's file (C3D, TRC, ...)
btkWriteAcquisition BTKWRITEACQUISITION Write acquisition's data into file (C3D, TRC, ...)
btkFindMetaData BTKFINDMETADATA Return the searched metadata or 0 if not found.
btkGetEventNumber BTKGETEVENTNUMBER Return the number of events.
btkGetLastFrame BTKGETLASTFRAME Returns acquisition's last frame index.
btkGetVersion V = BTKGETVERSION returns the release number of BTK.
btkMetaDataInfo BTKMETADATAINFO Create a structure containing the required fields for the informations of a metadata.
This function is called by:
SUBFUNCTIONS
function h = btkC3DserverGetHandle(id)
function res = btkC3DserverOpen(id, filename, mode)
function btkC3DserverClose(id)
function res = btkC3DserverNewFile(id, file, fileType, dataType, numAnalog, avRatio, numMarkers, frequencyRate, scalingFactor, numFrames)
function res = btkC3DserverIsModified(id)
function res = btkC3DserverSaveFile(id, filename, fileType)
function num = btkC3DserverGetNumber3DPoints(id)
function num = btkC3DserverGetAnalogChannels(id)
function num = btkC3DserverGetVideoFrame(id,startEnd)
function num = btkC3DserverGetMaxInterpolationGap(id)
function res = btkC3DserverSetMaxInterpolationGap(id, maxInterGap)
function scale = btkC3DserverGetHeaderScaleFactor(id)
function num = btkC3DserverGetStartingRecord(id)
function ratio = btkC3DserverGetAnalogVideoRatio(id)
function f = btkC3DserverGetVideoFrameRate(id)
function type = btkC3DserverGetFileType(id)
function type = btkC3DserverGetDataType(id)
function num = btkC3DserverGetNumberEvents(id)
function time = btkC3DserverGetEventTime(id, index)
function label = btkC3DserverGetEventLabel(id, index)
function status = btkC3DserverGetEventStatus(id, index)
function res = btkC3DserverAddEvent(id, label, status, time)
function res = btkC3DserverSetEventLabel(id, index, label)
function res = btkC3DserverSetEventTime(id, index, time)
function res = btkC3DserverSetEventStatus(id, index, status)
function res = btkC3DserverDeleteEvent(id, index)
function btkC3DserverSetStrictParameterChecking(id, value)
function btkCompressParameterBlocks(id, compress)
function num = btkC3DserverGetNumberGroups(id)
function index = btkC3DserverGetGroupIndex(id, label)
function name = btkC3DserverGetGroupName(id, index)
function num = btkC3DserverGetGroupNumber(id, index)
function locked = btkC3DserverGetGroupLock(id, index)
function desc = btkC3DserverGetGroupDescription(id, index)
function res = btkC3DserverSetGroupName(id, index, name)
function res = btkC3DserverSetGroupNumber(id, index, num)
function res = btkC3DserverSetGroupDescription(id, index, desc)
function res = btkC3DserverSetGroupLock(id, index, locked)
function res = btkC3DserverAddGroup(id, num, name, desc, locked)
function res = btkC3DserverDeleteGroup(id, index, deleteParameters)
function num = btkC3DserverGetNumberParameters(id)
function index = btkC3DserverGetParameterIndex(id, groupLabel, paramLabel)
function name = btkC3DserverGetParameterName(id, index)
function num = btkC3DserverGetParameterNumber(id, index)
function locked = btkC3DserverGetParameterLock(id, index)
function description = btkC3DserverGetParameterDescription(id, index)
function t = btkC3DserverGetParameterType(id, index)
function num = btkC3DserverGetParameterNumberDim(id, index)
function num = btkC3DserverGetParameterDimension(id, index, dim)
function num = btkC3DserverGetParameterLength(id, index)
function value = btkC3DserverGetParameterValue(id, index, item)
function res = btkC3DserverSetParameterName(id, index, name)
function res = btkC3DserverSetParameterNumber(id, index, num)
function res = btkC3DserverSetParameterLock(id, index, locked)
function res = btkC3DserverSetParameterDescription(id, index, desc)
function res = btkC3DserverSetParameterType(id, index, t)
function res = btkC3DserverSetParameterValue(id, index, item, value)
function res = btkC3DserverAddParameter(id, name, desc, group, locked, t, numDim, dimList, data)
function res = btkC3DserverDeleteParameter(id, index)
function res = btkC3DserverCopyParameter(id, index)
function res = btkC3DserverRetrieveParameter(id, index)
function res = btkC3DserverRemoveParameterData(id, index, item)
function res = btkC3DserverAddParameterData(id, index, items)
function data = btkC3DserverGetAnalogData(id, channel, frame, subFrame, scaled, offset, scale, useScale)
function data = btkC3DserverGetAnalogDataEx(id, channel, startFrame, endFrame, scaled, offset, scale, useScale)
function res = btkC3DserverSetAnalogData(id, channel, frame, subFrame, data)
function res = btkC3DserverSetAnalogDataEx(id, channel, frame, data)
function res = btkC3DserverSetAVRatio(id, avRatio)
function index = btkC3DserverAddAnalogChannel(id)
function res = btkC3DserverDeleteAnalogChannel(id, index)
function res = btkC3DserverDeleteAnalogChannelWithParameter(id, index)
function data = btkC3DserverGetForceData(id, cord, fp, startFrame, endFrame)
function data = btkC3DserverGetMomentData(id, cord, fp, startFrame, endFrame)
function res = btkC3DserverZeroAnalogChannel(id, channel, method, frames)
function data = btkC3DserverGetPointData(id, channel, cord, frame, scaled)
function data = btkC3DserverGetPointDataEx(id, channel, cord, startFrame, endFrame, scaled)
function data = btkC3DserverGetPointResidualEx(id, channel, startFrame, endFrame)
function data = btkC3DserverGetPointResidual(id, channel, frame)
function data = btkC3DserverGetPointMask(id, channel, frame)
function data = btkC3DserverGetPointMaskEx(id, channel, startFrame, endFrame)
function res = btkC3DserverSetPointData(id, channel, cord, frame, data)
function res = btkC3DserverSetPointDataEx(id, channel, cord, frame, data)
function index = btkC3DserverAddMarker(id)
function res = btkC3DserverDeleteMarker(id, index)
function res = btkC3DserverDeleteMarkerWithParameter(id, index)
function num = btkC3DserverAddFrames(id, frames, insertAt)
function num = btkC3DserverDeleteFrames(id, startAt, frames)
function id = btkC3DserverRequestNewHandle_p()
function idx = btkC3DserverCheckHandleID_p(id)
function res = btkC3DserverCheckHandleValue_p(idx)
function [h, idx] = btkC3DserverExtractHandle_p(id)
function btkC3DserverSetModified_p(idx, s)
function [parameter, indices, parent] = btkC3DserverExtractParameter_p(h, idx, index)
function parameter = btkC3DserverGetCopiedParameter_p(idx)
function btkC3DserverModifyCopiedParameter_p(idx, field, value, item)
function [scale, offset, label, description, gain] = btkC3DserverExtractAnalogInfos_p(h,index)
function [h, frames] = btkC3DserverCheckFPInputs_p(id, component, cord, fp, startFrame, endFrame)
function btkC3DserverAddMetaData_p(h, varargin)
function num = btkC3DserverGetEventNumber_p(h,idx)
function index_ = btkC3DserverGetEventIndex_p(index,idx)
SOURCE CODE
function itf = btkEmulateC3Dserver()
%BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
%
%  ITF = BTKEMULATEC3DSERVER() returns a structure which emulates the COM
%  object generated by the function 'actxserver('C3Dserver.C3D')'. So, it gives
%  the possibility to run scripts which use C3Dserver by using BTK.
%
%  However, BTK did't make the same choice than C3Dserver to extract C3D
%  informations. Then, you will find some slight differences between both:
%    - This emulation use function handles and then required for every
%      functions to be used with parenthesis (you cannot call 'itf.Close'
%      but 'itf.Close()'). Use parenthesis keep your code compatible with
%      C3Dserver.
%    - A C3D file is always opened in mode 3.
%    - The event's status is not kept in BTK. Using the following code:
%      'itf.SetEventStatus(0,'0')' sends a warning and do nothing. To remove
%      the warning, you have to add this command:
%      'warning('OFF','btk:C3Dserver:SetEventStatus')'
%    - The group and parameter number are generated from the index instead
%      of using the ID stored in the C3D file. Like that, the user doesn't
%      need to manage this number. So, if you set the group or parameter
%      number, a warning will inform you of the impossibility to do it. To
%      remove this warning, type the following command:
%      'warning('OFF','btk:C3Dserver:UniqueNumber')'
%      Removing this warning has an effect on the functions
%      SetGroupNumber, SetParameterNumber. But also on the function AddGroup
%      when you set manually the number.
%    - The function 'CompressParameterBlocks' is alway activated in BTK as the
%      the number of blocks needed for the groups/parameters is automatically
%      adapted when you write the C3D. Trying to deactivate the compression
%      (by using CompressParameterBlocks(0)) will send a warning. To remove the
%      warning, you have to add the command:
%      'warning('OFF','btk:C3Dserver:CompressParameterBlocks')'.
%    - If some groups and parameters has the same name in the C3D file (which
%      is the case with the group PROCESSING and its parameter for C3D files
%      generated with Vicon Nexus 1.4), then BTK removes the duplication
%      (which is not the case of C3Dserver).
%    - When you delete a group, it is not possible to keep the associated
%      parameters (They are stored in the group). If you try to do it, then
%      a warning will be displayed and the parameters are removed. To remove the
%      warning, use the command: 'warning('OFF','btk:C3Dserver:DeleteGroup')'.
%    - The parameters are sorted by groups. Then if you select parameter by
%      using hardcoded indices, you could have unexpected results.
%    - The parameters' values are managed automatically inside BTK. In the
%      case of parameter with the type 'Char', BTK trims (remove leading and
%      trailing white space) values when you open the C3D file. If you set
%      a number in a parameter with the type Char, then the number is
%      converted into a string.
%    - When you modify the parameter's type, then BTK adapts its values. In
%      lots of conversion you can come back to the original value. However,
%      transforming a string which doesn't contain a number creates the
%      value 0. If you convert a Real into an Integer, you lost the
%      floating information. If you convert an Integer into a Byte and the
%      value is not in the range [-128, 127], then you lost the most
%      significant part of the number.
%      For example, the conversion (Char->Integer) for 'FOO' creates the
%      number 0. But the conversion (Char->Integer) for '1234' creates the
%      number 1234. The conversion (Integer->Byte) for the number 12456
%      creates the number 168.
%    - Modifying the parameter's type, adapts also its dimensions.
%      For example, transforming a integer parameter into a char parameter
%      add 1 dimension corresponding to the number of characters. Or, in
%      the other case, transforming a char parameter into an integer,
%      remove.
%    - Retrieving a parameter in another index than the original will keep
%      the group for this index.
%    - Trying to retrieve a parameter which has the same name than one in
%      the destination group (other than the original group) will throw an
%      error.
%    - An AV ratio equal to 0 in BTK is automatically converted to 1. The
%      number of analog frames is at least equal to the number of video
%      frames.
%    - Starting with BTK 0.2, the camera mask is no longer supported. Trying
%      to extract or set a mask will display a warning. The returned masks
%      from the functions GetPointMask and GetPointMaskEx are fake masks and
%      always set to '0000000'. To remove the warning, you have to add
%      the command: 'warning('OFF','btk:C3Dserver:FakeMask')'.
%  Author: A. Barr
%  Copyright 2009-2013 Biomechanical ToolKit (BTK).
%  TODO:
%    - How to set parameter's values with the type 'Char'?
%    - What is the syntax to add frames other than using -1 and -2?
%    - Check for the btkGetForceData (remove offset part)
%    - Check for the btkGetMomentData (remove offset, in the global frame)
%  HISTORY:
%    - 13/12/28: btkEmulateC3Dserver 1.0 beta 4 released with BTK 0.3
%        - Default groups/parameters are now generated within the command NewFile.
%        - The writing of a C3D file relies now on the informations stored in the
%          existing groups/parameters as C3Dserver does (instead of the default
%          behavior of BTK which regenerate groups/parameters from acquisition data).
%        - Events are correctly saved in the C3D header section.
%        - Emulation of some commands improved to speedup them.
%        - Generation of the internal ID fixed when btkEmulateC3Dserver is called
%          more than once in the same function.
%    - 12/08/30: btkEmulateC3Dserver 1.0 beta 3 released with BTK 0.2
%        - Code updated to remove all the BTK functions related to the camera mask
%          as this information was removed from BTK 0.2.
%    - 12/04/11: btkEmulateC3Dserver 1.0 beta 2 released with BTK 0.1.10
%        - Implementation errors in the function SaveFile for the C3Dserver emulation.
%    - 11/06/28: Initial public beta
% Construct the emulated COM object by using function handles.
id = btkC3DserverRequestNewHandle_p();
itf.GetRegistrationMode = 2; % Register mode (full speed)
itf.GetRegUserName = 'Free Emulation Copy';
itf.GetRegUserOrganization = 'Biomechanical ToolKit (BTK)';
itf.GetVersion = sprintf('C3D Server Emulator 1.0 (beta 4) - BTK version %s, compatible C3Dserver 1.144.0', btkGetVersion());
itf.GetHandle = @()btkC3DserverGetHandle(id);
itf.Open = @(filename,mode)btkC3DserverOpen(id,filename,mode);
itf.Close = @()btkC3DserverClose(id);
itf.NewFile = @(file, fileType, dataType, numAnalog, avRatio, numMarkers, frequencyRate, scalingFactor, numFrames)btkC3DserverNewFile(id, file, fileType, dataType, numAnalog, avRatio, numMarkers, frequencyRate, scalingFactor, numFrames);
itf.IsModified = @()btkC3DserverIsModified(id);
itf.SaveFile = @(filename, fileType)btkC3DserverSaveFile(id, filename, fileType);
itf.GetNumber3DPoints = @()btkC3DserverGetNumber3DPoints(id);
itf.GetAnalogChannels = @()btkC3DserverGetAnalogChannels(id);
itf.GetVideoFrameHeader = @(startEnd)btkC3DserverGetVideoFrame(id, startEnd); % Give the same result than the function GetVideoFrame (in BTK, a C3D is transformed in an acquisition object)
itf.GetVideoFrame = @(startEnd)btkC3DserverGetVideoFrame(id, startEnd);
itf.GetMaxInterpolationGap = @()btkC3DserverGetMaxInterpolationGap(id); % Fake result as BTK doesn't save this value
itf.SetMaxInterpolationGap = @(maxInterGap)btkC3DserverSetMaxInterpolationGap(id, maxInterGap); % Do nothing
itf.GetHeaderScaleFactor = @()btkC3DserverGetHeaderScaleFactor(id); % Return the value stored in POINT:SCALE
itf.GetStartingRecord = @()btkC3DserverGetStartingRecord(id);
itf.GetAnalogVideoRatio = @()btkC3DserverGetAnalogVideoRatio(id);
itf.GetVideoFrameRate = @()btkC3DserverGetVideoFrameRate(id);
itf.GetFileType = @()btkC3DserverGetFileType(id);
itf.GetDataType = @()btkC3DserverGetDataType(id);
itf.GetNumberEvents = @()btkC3DserverGetNumberEvents(id);
itf.GetEventTime = @(index)btkC3DserverGetEventTime(id, index);
itf.GetEventLabel = @(index)btkC3DserverGetEventLabel(id, index);
itf.GetEventStatus = @(index)btkC3DserverGetEventStatus(id, index);
itf.AddEvent = @(label, status, time)btkC3DserverAddEvent(id, label, status, time);
itf.SetEventLabel = @(index, label)btkC3DserverSetEventLabel(id, index, label);
itf.SetEventTime = @(index, time)btkC3DserverSetEventTime(id, index, time);
itf.SetEventStatus = @(index, status)btkC3DserverSetEventStatus(id, index, status);
itf.DeleteEvent = @(index)btkC3DserverDeleteEvent(id, index);
itf.SetStrictParameterChecking = @(value)btkC3DserverSetStrictParameterChecking(id, value);
itf.CompressParameterBlocks = @(compress)btkCompressParameterBlocks(id, compress);
itf.GetNumberGroups = @()btkC3DserverGetNumberGroups(id);
itf.GetGroupIndex = @(label)btkC3DserverGetGroupIndex(id, label);
itf.GetGroupName = @(index)btkC3DserverGetGroupName(id, index);
itf.GetGroupNumber = @(index)btkC3DserverGetGroupNumber(id, index);
itf.GetGroupLock = @(index)btkC3DserverGetGroupLock(id, index);
itf.GetGroupDescription = @(index)btkC3DserverGetGroupDescription(id, index);
itf.SetGroupName = @(index, name)btkC3DserverSetGroupName(id, index, name);
itf.SetGroupNumber = @(index, num)btkC3DserverSetGroupNumber(id, index, num);
itf.SetGroupDescription = @(index, desc)btkC3DserverSetGroupDescription(id, index, desc);
itf.SetGroupLock = @(index, locked)btkC3DserverSetGroupLock(id, index, locked);
itf.AddGroup = @(num, name, desc, locked)btkC3DserverAddGroup(id, num, name, desc, locked);
itf.DeleteGroup = @(index, deleteParameters)btkC3DserverDeleteGroup(id, index, deleteParameters);
itf.GetNumberParameters = @()btkC3DserverGetNumberParameters(id);
itf.GetParameterIndex = @(groupLabel, paramLabel)btkC3DserverGetParameterIndex(id, groupLabel, paramLabel);
itf.GetParameterName = @(index)btkC3DserverGetParameterName(id, index);
itf.GetParameterNumber = @(index)btkC3DserverGetParameterNumber(id, index);
itf.GetParameterLock = @(index)btkC3DserverGetParameterLock(id, index);
itf.GetParameterDescription = @(index)btkC3DserverGetParameterDescription(id, index);
itf.GetParameterType = @(index)btkC3DserverGetParameterType(id, index);
itf.GetParameterNumberDim = @(index)btkC3DserverGetParameterNumberDim(id, index);
itf.GetParameterDimension = @(index, dim)btkC3DserverGetParameterDimension(id, index, dim);
itf.GetParameterLength = @(index)btkC3DserverGetParameterLength(id, index);
itf.GetParameterValue = @(index, value)btkC3DserverGetParameterValue(id, index, value);
itf.SetParameterName = @(index, name)btkC3DserverSetParameterName(id, index, name);
itf.SetParameterNumber = @(index, num)btkC3DserverSetParameterNumber(id, index, num);
itf.SetParameterLock = @(index, locked)btkC3DserverSetParameterLock(id, index, locked);
itf.SetParameterDescription = @(index, desc)btkC3DserverSetParameterDescription(id, index, desc);
itf.SetParameterType = @(index, t)btkC3DserverSetParameterType(id, index, t);
itf.SetParameterValue = @(index, item, value)btkC3DserverSetParameterValue(id, index, item, value);
itf.AddParameter = @(name, desc, group, locked, t, numDim, dimList, data)btkC3DserverAddParameter(id, name, desc, group, locked, t, numDim, dimList, data);
itf.DeleteParameter = @(index)btkC3DserverDeleteParameter(id, index);
itf.CopyParameter = @(index)btkC3DserverCopyParameter(id, index);
itf.RetrieveParameter = @(index)btkC3DserverRetrieveParameter(id, index);
itf.RemoveParameterData = @(index, item)btkC3DserverRemoveParameterData(id, index, item);
itf.AddParameterData = @(index, items)btkC3DserverAddParameterData(id, index, items);
itf.GetAnalogData = @(channel, frame, subFrame, scaled, offset, scale, useScale)btkC3DserverGetAnalogData(id, channel, frame, subFrame, scaled, offset, scale, useScale);
itf.GetAnalogDataEx = @(channel, startFrame, endFrame, scaled, offset, scale, useScale)btkC3DserverGetAnalogDataEx(id, channel, startFrame, endFrame, scaled, offset, scale, useScale);
itf.SetAnalogData = @(channel, frame, subFrame, data)btkC3DserverSetAnalogData(id, channel, frame, subFrame, data);
itf.SetAnalogDataEx = @(channel, frame, data)btkC3DserverSetAnalogDataEx(id, channel, frame, data);
itf.SetAVRatio = @(avRatio)btkC3DserverSetAVRatio(id, avRatio);
itf.AddAnalogChannel = @()btkC3DserverAddAnalogChannel(id);
itf.DeleteAnalogChannel = @(index)btkC3DserverDeleteAnalogChannel(id, index);
itf.DeleteAnalogChannelWithParam = @(index)btkC3DserverDeleteAnalogChannelWithParameter(id, index);
itf.DeleteAnalogChannelWithParameter = @(index)btkC3DserverDeleteAnalogChannelWithParameter(id, index);
itf.GetForceData = @(cord, fp, startFrame, endFrame)btkC3DserverGetForceData(id, cord, fp, startFrame, endFrame);
itf.GetMomentData = @(cord, fp, startFrame, endFrame)btkC3DserverGetMomentData(id, cord, fp, startFrame, endFrame);
itf.ZeroAnalogChannel = @(channel, method, frames)btkC3DserverZeroAnalogChannel(id, channel, method, frames);
itf.GetPointData = @(channel, cord, frame, scaled)btkC3DserverGetPointData(id, channel, cord, frame, scaled);
itf.GetPointDataEx = @(channel, cord, startFrame, endFrame, scaled)btkC3DserverGetPointDataEx(id, channel, cord, startFrame, endFrame, scaled);
itf.GetPointResidualEx = @(channel, startFrame, endFrame)btkC3DserverGetPointResidualEx(id, channel, startFrame, endFrame);
itf.GetPointResidual = @(channel, frame)btkC3DserverGetPointResidual(id, channel, frame);
itf.GetPointMask = @(channel, frame)btkC3DserverGetPointMask(id, channel, frame);
itf.GetPointMaskEx = @(channel, startFrame, endFrame)btkC3DserverGetPointMaskEx(id, channel, startFrame, endFrame);
itf.SetPointData = @(channel, cord, frame, data)btkC3DserverSetPointData(id, channel, cord, frame, data);
itf.SetPointDataEx = @(channel, cord, frame, data)btkC3DserverSetPointDataEx(id, channel, cord, frame, data);
itf.AddMarker = @()btkC3DserverAddMarker(id);
itf.DeleteMarker = @(index)btkC3DserverDeleteMarker(id, index);
itf.DeleteMarkerWithParam = @(index)btkC3DserverDeleteMarkerWithParameter(id, index);
itf.DeleteMarkerWithParameter = @(index)btkC3DserverDeleteMarkerWithParameter(id, index);
itf.AddFrames = @(frames, insertAt)btkC3DserverAddFrames(id, frames, insertAt);
itf.DeleteFrames = @(startAt, numFrames)btkC3DserverDeleteFrames(id, startAt, numFrames);
% -------------------------------------------------------------------------
% Public functions to extract BTK data
% -------------------------------------------------------------------------
% Return the associated acquisition's handle
function h = btkC3DserverGetHandle(id)
global btkC3DserverHandles;
idx = btkC3DserverCheckHandleID_p(id);
h = btkC3DserverHandles(idx).handle;
% -------------------------------------------------------------------------
% Public functions to emulate the methods in the COM object
% -------------------------------------------------------------------------
% The input mode has no effect in our case
function res = btkC3DserverOpen(id, filename, mode)
global btkC3DserverHandles;
idx = btkC3DserverCheckHandleID_p(id);
try
    if (btkC3DserverCheckHandleValue_p(idx) == 0)
        btkDeleteAcquisition(btkC3DserverHandles(idx).handle);
    end
    % Handle
    warning('off', 'btk:ReadAcquisition');
    [btkC3DserverHandles(idx).handle, bo, sf] = btkReadAcquisition(filename);
    warning('on', 'btk:ReadAcquisition');
    pointScale = btkGetMetaData(btkC3DserverHandles(idx).handle,'POINT','SCALE');
    btkC3DserverHandles(idx).scalingFactor = pointScale.info.values(1);
    % File type
    switch bo
        case 'IEEE_LittleEndian'
            btkC3DserverHandles(idx).fileType = 1;
        case 'VAX_LittleEndian'
            btkC3DserverHandles(idx).fileType = 2;
        case 'IEEE_BiEndian'
            btkC3DserverHandles(idx).fileType = 3;
    end
    % Data type
    switch sf
        case 'Integer'
            btkC3DserverHandles(idx).dataType = 1;
        case 'Float'
            btkC3DserverHandles(idx).dataType = 2;
    end
    res = 0; % File read
    btkC3DserverHandles(idx).file = filename;
    btkC3DserverHandles(idx).modified = 0; % Reset
    btkC3DserverHandles(idx).parameterIndexMapping = {};
    btkC3DserverHandles(idx).copiedParameter = 0;
    % Extra: The events in the EVENT group are not included by C3Dserver but BTK does
    %        The emulation tries to hide them instead of removing them in the case
    %        the user mix C3Dserver and native BTK code.
    eventUsed = btkFindMetaData(btkC3DserverHandles(idx).handle,'EVENT','USED');
    if (~isstruct(eventUsed))
        eventUsed = btkFindMetaData(btkC3DserverHandles(idx).handle,'EVENTS','USED');
    end
    if (isstruct(eventUsed))
        num = eventUsed.info.values(1);
        first = btkGetEventNumber(btkC3DserverHandles(idx).handle) - num + 1;
        btkC3DserverHandles(idx).hiddenParameterEvents = [first,num];
    end
catch
    err = lasterror();
    error('btk:C3Dserver',['Internal error: ' , err.message]);
end
md = btkGetMetaData(btkC3DserverHandles(idx).handle);
num = 0;
if (isstruct(md.children))
    labels = fieldnames(md.children);
    for i = 1:size(labels,1)
        children = md.children.(labels{i}).children;
        if isstruct(children)
            labels_ = fieldnames(children);
            for j = 1:size(labels_,1)
                btkC3DserverHandles(idx).parameterIndexMapping(end+1,:) = {[i,j],num};
                num = num + 1;
            end
        end
    end
end
function btkC3DserverClose(id)
global btkC3DserverHandles;
idx = btkC3DserverCheckHandleID_p(id);
res = btkC3DserverCheckHandleValue_p(idx);
if (res == 0)
    btkDeleteAcquisition(btkC3DserverHandles(idx).handle);
    btkC3DserverHandles(idx).handle = NaN;
    btkC3DserverHandles(idx).file = '';
    btkC3DserverHandles(idx).scalingFactor = 1;
end
function res = btkC3DserverNewFile(id, file, fileType, dataType, numAnalog, avRatio, numMarkers, frequencyRate, scalingFactor, numFrames)
global btkC3DserverHandles;
if ((fileType < 1) || (fileType > 3))
    fileType = 1;
end
if ((dataType < 1) || (dataType > 2))
    dataType = 1;
end
idx = btkC3DserverCheckHandleID_p(id);
try
    if (btkC3DserverCheckHandleValue_p(idx) == 0)
        btkDeleteAcquisition(btkC3DserverHandles(idx).handle);
    end
    btkC3DserverHandles(idx).handle = btkNewAcquisition(numMarkers, numFrames, numAnalog, avRatio);
    btkC3DserverHandles(idx).file = file;
    btkC3DserverHandles(idx).fileType = fileType;
    btkC3DserverHandles(idx).dataType = dataType;
    btkC3DserverHandles(idx).scalingFactor = scalingFactor;
    btkC3DserverHandles(idx).modified = 1;
    h = btkC3DserverHandles(idx).handle;
    % Add default groups/parameters
    btkC3DserverAddMetaData_p(h, 'ANALOG', 'Analog Parameters');
    btkC3DserverAddMetaData_p(h, 'ANALOG', 'GEN_SCALE', btkMetaDataInfo('Real', 1), 'General Scale Factor');
    btkC3DserverAddMetaData_p(h, 'ANALOG', 'RATE', btkMetaDataInfo('Real', avRatio * frequencyRate), 'Analog Base Sampling Rate');
    btkC3DserverAddMetaData_p(h, 'ANALOG', 'USED', btkMetaDataInfo('Integer', numAnalog), 'Number of analog channels used');
    btkC3DserverAddMetaData_p(h, 'ANALOG', 'SCALE', btkMetaDataInfo('Real', ones(numAnalog,1)), 'Analog scale factors');
    btkC3DserverAddMetaData_p(h, 'ANALOG', 'OFFSET', btkMetaDataInfo('Integer', 2048 * ones(numAnalog,1)), 'Analog Offsets');
    btkC3DserverAddMetaData_p(h, 'ANALOG', 'UNITS', btkMetaDataInfo('Char', repmat({''},numAnalog,1)), 'Analog units');
    btkC3DserverAddMetaData_p(h, 'ANALOG', 'LABELS', btkMetaDataInfo('Char', cellstr(num2str([1:numAnalog]','CH%03i'))), 'Analog labels');
    btkC3DserverAddMetaData_p(h, 'ANALOG', 'DESCRIPTIONS', btkMetaDataInfo('Char', cellstr(num2str([1:numAnalog]','Channel %03i'))), 'Analog descriptions');
    btkC3DserverAddMetaData_p(h, 'POINT', 'Point Parameters');
    btkC3DserverAddMetaData_p(h, 'POINT', 'USED', btkMetaDataInfo('Integer', numMarkers), 'Number of Markers');
    btkC3DserverAddMetaData_p(h, 'POINT', 'FRAMES', btkMetaDataInfo('Integer', numFrames), 'Number of Video Frames');
    btkC3DserverAddMetaData_p(h, 'POINT', 'DATA_START', btkMetaDataInfo('Integer', 10), 'Start Record for Data');
    btkC3DserverAddMetaData_p(h, 'POINT', 'SCALE', btkMetaDataInfo('Real', scalingFactor), 'Scale factor for video data');
    btkC3DserverAddMetaData_p(h, 'POINT', 'RATE', btkMetaDataInfo('Real', frequencyRate), 'Video sampling rate');
    btkC3DserverAddMetaData_p(h, 'POINT', 'LABELS', btkMetaDataInfo('Char', cellstr(num2str([1:numMarkers]','MK%03i'))), 'Marker labels');
    btkC3DserverAddMetaData_p(h, 'POINT', 'DESCRIPTIONS', btkMetaDataInfo('Char', cellstr(num2str([1:numMarkers]','Marker %03i'))), 'Point descriptions');
    btkC3DserverAddMetaData_p(h, 'FORCE_PLATFORM', 'Force Platform Parameters');
    btkC3DserverAddMetaData_p(h, 'FORCE_PLATFORM', 'USED', btkMetaDataInfo('Integer', 0), 'Number of Force Plates');
    % Others
    btkSetFrequency(h, frequencyRate);
    % File created
    res = 1;
catch
    err = lasterror();
    error('btk:C3Dserver',['An error occured during the creation of the file: ''', err.message , ''''])
end
function res = btkC3DserverIsModified(id)
global btkC3DserverHandles;
idx = btkC3DserverCheckHandleID_p(id);
res = char(btkC3DserverHandles(idx).modified);
function res = btkC3DserverSaveFile(id, filename, fileType)
global btkC3DserverHandles;
[h, idx] = btkC3DserverExtractHandle_p(id);
if (isempty(filename))
    filename = btkC3DserverHandles(idx).file;
end
if (fileType == -1)
    fileType = btkC3DserverHandles(idx).fileType;
end
if ((fileType < 1) || (fileType > 3))
    fileType = 1;
end
byteorder = {'IEEE_LittleEndian', 'VAX_LittleEndian', 'IEEE_BigEndian'};
storageformat = {'Integer', 'Float'};
try
    btkWriteAcquisition(h, filename, 'ByteOrder', byteorder{fileType}, 'StorageFormat', storageformat{btkC3DserverHandles(idx).dataType}, 'InternalsUpdate', 'MetaDataBasedUpdate');
    res = 1; % File wrote
catch
    err = lasterror();
    error('btk:C3Dserver',['An error occured during the saving of the file: ''', err.message , ''''])
end
function num = btkC3DserverGetNumber3DPoints(id)
h = btkC3DserverExtractHandle_p(id);
num = btkGetPointNumber(h);
function num = btkC3DserverGetAnalogChannels(id)
h = btkC3DserverExtractHandle_p(id);
num = btkGetAnalogNumber(h);
function num = btkC3DserverGetVideoFrame(id,startEnd)
h = btkC3DserverExtractHandle_p(id);
if (startEnd == 0)
    num = btkGetFirstFrame(h);
else
    num = btkGetLastFrame(h);
end;
function num = btkC3DserverGetMaxInterpolationGap(id)
h = btkC3DserverExtractHandle_p(id);
num = btkGetMaxInterpolationGap(h);
function res = btkC3DserverSetMaxInterpolationGap(id, maxInterGap)
[h, idx] = btkC3DserverExtractHandle_p(id);
btkSetMaxInterpolationGap(h, maxInterGap);
res = 1;
btkC3DserverSetModified_p(idx,1);
function scale = btkC3DserverGetHeaderScaleFactor(id)
global btkC3DserverHandles;
[h, idx] = btkC3DserverExtractHandle_p(id);
scale = btkC3DserverHandles(idx).scalingFactor;
function num = btkC3DserverGetStartingRecord(id)
h = btkC3DserverExtractHandle_p(id);
pointDataStart = btkFindMetaData(h, 'POINT', 'DATA_START');
num = 2;
if isstruct(pointDataStart)
    num = pointDataStart.info.values(1);
end
function ratio = btkC3DserverGetAnalogVideoRatio(id)
h = btkC3DserverExtractHandle_p(id);
ratio = btkGetAnalogSampleNumberPerFrame(h);
function f = btkC3DserverGetVideoFrameRate(id)
h = btkC3DserverExtractHandle_p(id);
f = btkGetPointFrequency(h);
function type = btkC3DserverGetFileType(id)
global btkC3DserverHandles;
idx = btkC3DserverCheckHandleID_p(id);
type = btkC3DserverHandles(idx).fileType;
function type = btkC3DserverGetDataType(id)
global btkC3DserverHandles;
idx = btkC3DserverCheckHandleID_p(id);
type = btkC3DserverHandles(idx).dataType;
function num = btkC3DserverGetNumberEvents(id)
[h,idx] = btkC3DserverExtractHandle_p(id);
num = btkC3DserverGetEventNumber_p(h,idx);
function time = btkC3DserverGetEventTime(id, index)
[h,idx] = btkC3DserverExtractHandle_p(id);
if ((index < 0) || (index >= btkC3DserverGetEventNumber_p(h,idx)))
    error('btk:C3Dserver', 'Invalid index has been used.');
end
times = btkGetEventsValues(h);
index_ = btkC3DserverGetEventIndex_p(index,idx);
time = times(index_);
function label = btkC3DserverGetEventLabel(id, index)
[h,idx] = btkC3DserverExtractHandle_p(id);
if ((index < 0) || (index >= btkC3DserverGetEventNumber_p(h,idx)))
    error('btk:C3Dserver', 'Invalid index has been used.');
end
[times, labels] = btkGetEventsValues(h);
index_ = btkC3DserverGetEventIndex_p(index,idx);
label = labels{index_};
% The status returned is always set to 1 as the the metadata EVENTS doesn't take it into account.
function status = btkC3DserverGetEventStatus(id, index)
[h,idx] = btkC3DserverExtractHandle_p(id);
if ((index < 0) || (index >= btkC3DserverGetEventNumber_p(h,idx)))
    error('btk:C3Dserver', 'Invalid index has been used.');
end
%[times, labels, descriptions, statuses] = btkGetEventsValues(h);
%status = char(statuses(index+1));
status = char(1);
% The status is not saved as the the metadata EVENTS doesn't take it into account.
function res = btkC3DserverAddEvent(id, label, status, time)
[h, idx] = btkC3DserverExtractHandle_p(id);
try
    if (status == char(0))
        warning('btk:C3Dserver:AddEvent','The library BTK didn''t save event''s status and are always set as displayed.');
    end
    btkAppendEvent(h, label, time, '', '', '', -65536); % -65536: Special ID which will set the event detection flag to the value 0x10000. The ID will be then set to the default value (i.e. 0).
    res = btkC3DserverGetEventNumber_p(h,idx) - 1; % Added
    btkC3DserverSetModified_p(idx,1);
catch
    err = lasterror();
    error('btk:C3Dserver',['An error occured during the adding of the event: ''', err.message , ''''])
end
function res = btkC3DserverSetEventLabel(id, index, label)
[h, idx] = btkC3DserverExtractHandle_p(id);
if ((index < 0) || (index >= btkC3DserverGetEventNumber_p(h,idx)))
    error('btk:C3Dserver', 'Invalid index has been used.');
end
index_ = btkC3DserverGetEventIndex_p(index,idx);
btkSetEventLabel(h, index_, label);
res = 1;
btkC3DserverSetModified_p(idx,1);
function res = btkC3DserverSetEventTime(id, index, time)
[h, idx] = btkC3DserverExtractHandle_p(id);
if((index < 0) || (index >= btkC3DserverGetEventNumber_p(h,idx)))
    error('btk:C3Dserver', 'Invalid index has been used.');
end
index_ = btkC3DserverGetEventIndex_p(index,idx);
btkSetEventTime(h, index_, time);
res = 1; % Modified
btkC3DserverSetModified_p(idx,1);
function res = btkC3DserverSetEventStatus(id, index, status)
[h, idx] = btkC3DserverExtractHandle_p(id);
if ((index < 0) || (index >= btkC3DserverGetEventNumber_p(h,idx)))
    error('btk:C3Dserver', 'Invalid index has been used.');
end
%btkSetEventStatus(h, index+1, status);
if (status == '0')
    warning('btk:C3Dserver:SetEventStatus', 'The library BTK doesn''t set the event''s status.');
    res = 0; % Not modified
else
    res = 1;
    btkC3DserverSetModified_p(idx,1);
end
function res = btkC3DserverDeleteEvent(id, index)
[h, idx] = btkC3DserverExtractHandle_p(id);
if ((index < 0) || (index >= btkC3DserverGetEventNumber_p(h,idx)))
    error('btk:C3Dserver', 'Invalid index has been used.');
end
index_ = btkC3DserverGetEventIndex_p(index,idx);
btkRemoveEvent(h, index_);
res = 1; % Removed
btkC3DserverSetModified_p(idx,1);
function btkC3DserverSetStrictParameterChecking(id, value)
global btkC3DserverHandles;
idx = btkC3DserverCheckHandleID_p(id);
btkC3DserverHandles(idx).strictChecking = value;
function btkCompressParameterBlocks(id, compress)
btkC3DserverCheckHandleID_p(id);
if (compress == 0)
    warning('btk:C3Dserver:CompressParameterBlocks','Compression is done automatilcaly by BTK, as it regenerates the groups/parameters when you write the C3D.');
end
function num = btkC3DserverGetNumberGroups(id)
h = btkC3DserverExtractHandle_p(id);
md = btkGetMetaData(h);
if (isstruct(md.children))
    num = size(fieldnames(md.children),1);
else
    num = 0;
end
function index = btkC3DserverGetGroupIndex(id, label)
h = btkC3DserverExtractHandle_p(id);
index = -1; % Not found
md = btkGetMetaData(h);
if (isstruct(md.children))
    labels = fieldnames(md.children);
    for i = 1:size(labels,1)
        if (strcmp(labels{i}, label))
            index = i - 1;
            break;
        end
    end
else
    error('btk:C3Dserver', 'No group and parameter.');
end
function name = btkC3DserverGetGroupName(id, index)
h = btkC3DserverExtractHandle_p(id);
md = btkGetMetaData(h);
if (isstruct(md.children))
    labels = fieldnames(md.children);
    if ((index < 0) || (index >= size(labels,1)))
        error('btk:C3Dserver', 'Invalid index has been used.');
    end
    name = labels{index+1};
else
    error('btk:C3Dserver', 'No group and parameter.');
end
function num = btkC3DserverGetGroupNumber(id, index)
h = btkC3DserverExtractHandle_p(id);
md = btkGetMetaData(h);
if (isstruct(md.children))
    labels = fieldnames(md.children);
    if ((index < 0) || (index >= size(labels,1)))
        error('btk:C3Dserver', 'Invalid index has been used.');
    end
    num = -1*(index+1);
else
    error('btk:C3Dserver', 'No group and parameter.');
end
function locked = btkC3DserverGetGroupLock(id, index)
h = btkC3DserverExtractHandle_p(id);
md = btkGetMetaData(h);
if (isstruct(md.children))
    labels = fieldnames(md.children);
    if ((index < 0) || (index >= size(labels,1)))
        error('btk:C3Dserver', 'Invalid index has been used.');
    end
    if (md.children.(labels{index+1}).unlocked == 0)
        locked = char(1);
    else
        locked = char(0);
    end
else
    error('btk:C3Dserver', 'No group and parameter.');
end
function desc = btkC3DserverGetGroupDescription(id, index)
h = btkC3DserverExtractHandle_p(id);
md = btkGetMetaData(h);
if (isstruct(md.children))
    labels = fieldnames(md.children);
    if ((index < 0) || (index >= size(labels,1)))
        error('btk:C3Dserver', 'Invalid index has been used.');
    end
    desc = md.children.(labels{index+1}).description;
else
    error('btk:C3Dserver', 'No group and parameter.');
end
function res = btkC3DserverSetGroupName(id, index, name)
global btkC3DserverHandles
[h, idx] = btkC3DserverExtractHandle_p(id);
md = btkGetMetaData(h);
if (isstruct(md.children))
    labels = fieldnames(md.children);
    if ((index < 0) || (index >= size(labels,1)))
        error('btk:C3Dserver', 'Invalid index has been used.');
    end
    for i =1:length(labels)
        if ((i ~= (index+1)) && strcmp(name, labels{i}))
            error('btk:C3Dserver','Group name already exists.');
        elseif ((i ~= (index+1)) && (btkC3DserverHandles(idx).strictChecking ~= 0))
            name_ = name;
            if (length(name_) > 6)
                name_ = name_(1:6);
            end
            label_ = labels{i};
            if (length(label_) > 6)
                label_ = label_(1:6);
            end
            if (strcmp(name_, label_))
                error('btk:C3Dserver','Group name already exists.');
            end
        end
    end
    try
        btkSetMetaDataLabel(h, index+1, name);
    catch
        err = lasterror();
        error('btk:C3Dserver', ['Internal error: ', err.message]);
    end
else
    error('btk:C3Dserver', 'No group and parameter.');
end
btkC3DserverSetModified_p(idx,1);
res = 1;
function res = btkC3DserverSetGroupNumber(id, index, num)
[h, idx] = btkC3DserverExtractHandle_p(id);
md = btkGetMetaData(h);
if (isstruct(md.children))
    labels = fieldnames(md.children);
    if ((index < 0) || (index >= size(labels,1)))
        error('btk:C3Dserver', 'Incorrect value for group number.');
    elseif (num >= 0)
        error('btk:C3Dserver', 'Incorrect value for group number.');
    end
    warning('btk:C3Dserver:UniqueNumber', 'The library BTK doesn''t use an unique number for groups and parameters as it is automatically set when you write the C3D file. The number is not assigned.');
else
    error('btk:C3Dserver', 'No group and parameter.');
end
btkC3DserverSetModified_p(idx,1);
res = 1;
function res = btkC3DserverSetGroupDescription(id, index, desc)
[h, idx] = btkC3DserverExtractHandle_p(id);
md = btkGetMetaData(h);
if (isstruct(md.children))
    labels = fieldnames(md.children);
    if ((index < 0) || (index >= size(labels,1)))
        error('btk:C3Dserver', 'Incorrect value for group number.');
    end
    btkSetMetaDataDescription(h, index+1, desc);
else
    error('btk:C3Dserver', 'No group and parameter.');
end
btkC3DserverSetModified_p(idx,1);
res = 1;
function res = btkC3DserverSetGroupLock(id, index, locked)
[h, idx] = btkC3DserverExtractHandle_p(id);
md = btkGetMetaData(h);
if (isstruct(md.children))
    labels = fieldnames(md.children);
    if ((index < 0) || (index >= size(labels,1)))
        error('btk:C3Dserver', 'Incorrect value for group number.');
    end
    if (locked == char(0))
        btkSetMetaDataUnlock(h, index+1, 1);
    else
        btkSetMetaDataUnlock(h, index+1, 0);
    end
else
    error('btk:C3Dserver', 'No group and parameter.');
end
btkC3DserverSetModified_p(idx,1);
res = 1;
function res = btkC3DserverAddGroup(id, num, name, desc, locked)
global btkC3DserverHandles;
[h, idx] = btkC3DserverExtractHandle_p(id);
if (num > 0)
    error('btk:C3Dserver', 'Incorrect value for group number.');
elseif (num ~= 0)
    warning('btk:C3Dserver:UniqueNumber', 'The library BTK doesn''t use an unique number for group and parameter as it is automatically set when you write the C3D file. The number is not assigned.');
end
md = btkGetMetaData(h);
if (isstruct(md.children))
    labels = fieldnames(md.children);
    for i =1:length(labels)
        if strcmp(name, labels{i})
            error('btk:C3Dserver','Group name already exists.');
        elseif (btkC3DserverHandles(idx).strictChecking ~= 0)
            name_ = name;
            if (length(name_) > 6)
                name_ = name_(1:6);
            end
            label_ = labels{i};
            if (length(label_) > 6)
                label_ = label_(1:6);
            end
            if (strcmp(name_, label_))
                error('btk:C3Dserver','Group name already exists.');
            end
        end
    end
else
    error('btk:C3Dserver', 'No group and parameter.');
end
try
    md = btkAppendMetaData(h, name);
    res = size(fieldnames(md.children),1);
    btkSetMetaDataDescription(h, res, desc);
    if (locked == char(0))
        btkSetMetaDataUnlock(h, res, 1);
    else
        btkSetMetaDataUnlock(h, res, 0);
    end
    res = res - 1;
catch
    err = lasterror();
    error('btk:C3Dserver', ['Internal error: ', err.message]);
end
btkC3DserverSetModified_p(idx,1);
function res = btkC3DserverDeleteGroup(id, index, deleteParameters)
global btkC3DserverHandles;
[h, idx] = btkC3DserverExtractHandle_p(id);
md = btkGetMetaData(h);
if (isstruct(md.children))
    labels = fieldnames(md.children);
    if ((index < 0) || (index >= size(labels,1)))
        error('btk:C3Dserver', 'Invalid index has been used.');
    end
    if (deleteParameters == char(0))
        warning('btk:C3Dserver:DeleteGroup', 'BTK doesn''t give the possibily to remove only the group and not its parameter (they will become orphans).');
    end
    btkRemoveMetaData(h, index+1);
else
    error('btk:C3Dserver', 'No group and parameter.');
end
% Update internal parameter index
mapping = btkC3DserverHandles(idx).parameterIndexMapping;
num = size(mapping,1);
foo = [mapping{:,1}]; foo = reshape(foo, 2, length(foo)/2)';
mapping = mapping(~(foo(:,1) == (index + 1)),:);
num = num - size(mapping,1);
for i=1:size(mapping,1)
    if (mapping{i,1}(1) > (index + 1))
        mapping{i,1}(1) = mapping{i,1}(1) - 1;
        mapping{i,2} = mapping{i,2} - num;
    end
end
btkC3DserverHandles(idx).parameterIndexMapping = mapping;
btkC3DserverSetModified_p(idx,1);
res = 1;
function num = btkC3DserverGetNumberParameters(id)
h = btkC3DserverExtractHandle_p(id);
num = 0;
md = btkGetMetaData(h);
if (isstruct(md.children))
    labels = fieldnames(md.children);
    for i = 1:size(labels,1)
        children = md.children.(labels{i}).children;
        if (isstruct(children))
            num = num + size(fieldnames(children),1);
        end
    end
else
    error('btk:C3Dserver', 'No group and parameter.');
end
function index = btkC3DserverGetParameterIndex(id, groupLabel, paramLabel)
global btkC3DserverHandles;
[h, idx] = btkC3DserverExtractHandle_p(id);
num = 0;
index = -1;
md = btkGetMetaData(h);
if (isstruct(md.children))
    idxGr = 0;
    labels = fieldnames(md.children);
    for i = 1:size(labels,1)
        children = md.children.(labels{i}).children;
        if (strcmp(labels{i}, groupLabel))
            idxGr = i;
            break;
        elseif (isstruct(children))
            num = num + size(fieldnames(children),1);
        end
    end
    if (idxGr ~= 0)
        idxPr = 0;
        md = md.children.(labels{idxGr});
        if (isstruct(md.children))
            labels = fieldnames(md.children);
            for i = 1:size(labels,1)
                if (strcmp(labels{i}, paramLabel))
                    idxPr = i;
                    break;
                else
                    num = num + 1;
                end
            end
        end
        if (idxPr ~= 0)
            for i = 1:size(btkC3DserverHandles(idx).parameterIndexMapping,1)
                if all(btkC3DserverHandles(idx).parameterIndexMapping{i,1} == [idxGr, idxPr])
                    index = btkC3DserverHandles(idx).parameterIndexMapping{i,2};
                    break;
                end
            end
        end
    end
else
    error('btk:C3Dserver', 'No group and parameter.');
end
function name = btkC3DserverGetParameterName(id, index)
[h, idx] = btkC3DserverExtractHandle_p(id);
if (index == -1)
    parameter = btkC3DserverGetCopiedParameter_p(idx);
else
    parameter = btkC3DserverExtractParameter_p(h, idx, index);
end
name = parameter.label;
function num = btkC3DserverGetParameterNumber(id, index)
[h, idx] = btkC3DserverExtractHandle_p(id);
if (index == -1)
    parameter = btkC3DserverGetCopiedParameter_p(idx);
else
    parameter = btkC3DserverExtractParameter_p(h, idx, index);
end
num = parameter.id;
function locked = btkC3DserverGetParameterLock(id, index)
[h, idx] = btkC3DserverExtractHandle_p(id);
if (index == -1)
    parameter = btkC3DserverGetCopiedParameter_p(idx);
else
    parameter = btkC3DserverExtractParameter_p(h, idx, index);
end
if (parameter.unlocked == 0)
    locked = char(1);
else
    locked = char(0);
end
function description = btkC3DserverGetParameterDescription(id, index)
[h, idx] = btkC3DserverExtractHandle_p(id);
if (index == -1)
    parameter = btkC3DserverGetCopiedParameter_p(idx);
else
    parameter = btkC3DserverExtractParameter_p(h, idx, index);
end
description = parameter.description;
function t = btkC3DserverGetParameterType(id, index)
[h, idx] = btkC3DserverExtractHandle_p(id);
if (index == -1)
    parameter = btkC3DserverGetCopiedParameter_p(idx);
else
    parameter = btkC3DserverExtractParameter_p(h, idx, index);
end
if (isstruct(parameter.info))
    switch parameter.info.format
        case 'Char'
            t = -1;
        case 'Byte'
            t = 1;
        case 'Integer'
            t = 2;
        case 'Real'
            t = 4;
    end
else
    error('btk:C3Dserver','The selected metadata doesn''t contains information.')
end
function num = btkC3DserverGetParameterNumberDim(id, index)
[h, idx] = btkC3DserverExtractHandle_p(id);
if (index == -1)
    parameter = btkC3DserverGetCopiedParameter_p(idx);
else
    parameter = btkC3DserverExtractParameter_p(h, idx, index);
end
if (isstruct(parameter.info))
    num = length(parameter.info.dims);
else
    error('btk:C3Dserver','The selected metadata doesn''t contains information.')
end
function num = btkC3DserverGetParameterDimension(id, index, dim)
[h, idx] = btkC3DserverExtractHandle_p(id);
if (index == -1)
    parameter = btkC3DserverGetCopiedParameter_p(idx);
else
    parameter = btkC3DserverExtractParameter_p(h, idx, index);
end
if (isstruct(parameter.info))
    if (dim >= length(parameter.info.dims))
        error('btk:C3Dserver', 'Invalid index has been used.');
    else
        num = parameter.info.dims(dim+1);
    end
else
    error('btk:C3Dserver','The selected metadata doesn''t contains information.')
end
function num = btkC3DserverGetParameterLength(id, index)
[h, idx] = btkC3DserverExtractHandle_p(id);
if (index == -1)
    parameter = btkC3DserverGetCopiedParameter_p(idx);
else
    parameter = btkC3DserverExtractParameter_p(h, idx, index);
end
if (isstruct(parameter.info))
    num = numel(parameter.info.values);
else
    error('btk:C3Dserver','The selected metadata doesn''t contains information.')
end
function value = btkC3DserverGetParameterValue(id, index, item)
[h, idx] = btkC3DserverExtractHandle_p(id);
if (index == -1)
    parameter = btkC3DserverGetCopiedParameter_p(idx);
else
1000     parameter = btkC3DserverExtractParameter_p(h, idx, index);
1001 end
1002 if (isstruct(parameter.info))
1003     if (item >= numel(parameter.info.values))
1004         if (strcmp(parameter.info.format, 'Char'))
1005             value = '';
1006         else
1007             value = 0;
1008         end
1009     else
1010         value = parameter.info.values(item+1);
1011         if (iscell(value))
1012             value = value{1};
1013         end
1014     end
1015 else
1016     error('btk:C3Dserver','The selected metadata doesn''t contains information.')
1017 end
1018 switch parameter.info.format
1019     case 'Byte'
1020         value = uint8(value);
1021     case 'Integer'
1022         value = int32(value);
1023     case 'Real'
1024         value = single(value);
1025 end
1026
1027 function res = btkC3DserverSetParameterName(id, index, name)
1028 global btkC3DserverHandles;
1029 [h, idx] = btkC3DserverExtractHandle_p(id);
1030 if (index == -1)
1031     btkC3DserverModifyCopiedParameter_p(idx, 'label', name);
1032 else
1033     [parameter, indices, parent] = btkC3DserverExtractParameter_p(h, idx, index);
1034     labels = fieldnames(parent.children);
1035     for i =1:length(labels)
1036         if ((i ~= (index+1)) && strcmp(name, labels{i}))
1037             error('btk:C3Dserver','This parameter already exists within the group.');
1038         elseif ((i ~= (index+1)) && (btkC3DserverHandles(idx).strictChecking ~= 0))
1039             name_ = name;
1040             if (length(name_) > 6)
1041                 name_ = name_(1:6);
1042             end
1043             label_ = labels{i};
1044             if (length(label_) > 6)
1045                 label_ = label_(1:6);
1046             end
1047             if (strcmp(name_, label_))
1048                 error('btk:C3Dserver','This parameter already exists within the group.');
1049             end
1050         end
1051     end
1052     try
1053         btkSetMetaDataLabel(h, indices(1), indices(2), name);
1054     catch
1055         err = lasterror();
1056         error('btk:C3Dserver', ['Internal error: ', err.message]);
1057     end
1058 end
1059 btkC3DserverSetModified_p(idx,1);
1060 res = 1;
1061
1062
1063 function res = btkC3DserverSetParameterNumber(id, index, num)
1064 [h, idx] = btkC3DserverExtractHandle_p(id);
1065 if (index ~= -1)
1066     [temp indices] = btkC3DserverExtractParameter_p(h, idx, index);
1067 end
1068 if (num <= 0)
1069     error('btk:C3Dserver', 'Incorrect value for parameter number.');
1070 end
1071 warning('btk:C3Dserver:UniqueNumber', 'The library BTK doesn''t use an unique number for group and parameter as it is automatically set when you write the C3D file. The number is not assigned.');
1072 btkC3DserverSetModified_p(idx,1);
1073 res = 1;
1074
1075
1076 function res = btkC3DserverSetParameterLock(id, index, locked)
1077 [h, idx] = btkC3DserverExtractHandle_p(id);
1078 if (index == -1)
1079     unlocked = 0;
1080     if (locked == char(0))
1081         unlocked = 1;
1082     end
1083     btkC3DserverModifyCopiedParameter_p(idx, 'unlocked', unlocked);
1084 else
1085     [temp indices] = btkC3DserverExtractParameter_p(h, idx, index);
1086     try
1087         if (locked == char(0))
1088             btkSetMetaDataUnlock(h, indices(1), indices(2), 1);
1089         else
1090             btkSetMetaDataUnlock(h, indices(1), indices(2), 0);
1091         end
1092     catch
1093         err = lasterror();
1094         error('btk:C3Dserver', ['Internal error: ', err.message]);
1095     end
1096 end
1097 btkC3DserverSetModified_p(idx,1);
1098 res = 1;
1099
1100
1101 function res = btkC3DserverSetParameterDescription(id, index, desc)
1102 [h, idx] = btkC3DserverExtractHandle_p(id);
1103 if (index == -1)
1104     btkC3DserverModifyCopiedParameter_p(idx, 'description', desc);
1105 else
1106     [temp indices] = btkC3DserverExtractParameter_p(h, idx, index);
1107     try
1108         btkSetMetaDataDescription(h, indices(1), indices(2), desc);
1109     catch
1110         err = lasterror();
1111         error('btk:C3Dserver', ['Internal error: ', err.message]);
1112     end
1113 end
1114 btkC3DserverSetModified_p(idx,1);
1115 res = 1;
1116
1117
1118 function res = btkC3DserverSetParameterType(id, index, t)
1119 [h, idx] = btkC3DserverExtractHandle_p(id);
1120 switch t
1121     case -1
1122         t_ = 'Char';
1123     case 1
1124         t_ = 'Byte';
1125     case 2
1126         t_ = 'Integer';
1127     case 4
1128         t_ = 'Real';
1129     otherwise
1130         error('btk:C3Dserver', 'The given parameter''s type is unsupported.')
1131 end
1132 if (index == -1)
1133     btkC3DserverModifyCopiedParameter_p(idx, {'info','format'}, t_);
1134 else
1135     [temp indices] = btkC3DserverExtractParameter_p(h, idx, index);
1136     try
1137         btkSetMetaDataFormat(h, indices(1), indices(2), t_);
1138     catch
1139         err = lasterror();
1140         error('btk:C3Dserver', ['Internal error: ', err.message]);
1141     end
1142 end
1143 btkC3DserverSetModified_p(idx,1);
1144 res = 1;
1145
1146
1147 function res = btkC3DserverSetParameterValue(id, index, item, value)
1148 [h, idx] = btkC3DserverExtractHandle_p(id);
1149 if (index == -1)
1150     btkC3DserverModifyCopiedParameter_p(idx, {'info','values'}, value, item);
1151 else
1152     [parameter indices] = btkC3DserverExtractParameter_p(h, idx, index);
1153     try
1154         if ((item < 0) || (item > numel(parameter.info.values)))
1155             error('btk:C3Dserver', 'Invalid index has been used.')
1156         end
1157         btkSetMetaDataValue(h, indices(1), indices(2), item+1, value);
1158     catch
1159         err = lasterror();
1160         error('btk:C3Dserver', ['Internal error: ', err.message]);
1161     end
1162 end
1163 % Why C3Dserver doesn't set the flag modified to true?
1164 %btkC3DserverSetModified_p(idx,1);
1165 res = 1;
1166
1167
1168 function res = btkC3DserverAddParameter(id, name, desc, group, locked, t, numDim, dimList, data)
1169 global btkC3DserverHandles
1170 [h, idx] = btkC3DserverExtractHandle_p(id);
1171 md = btkGetMetaData(h);
1172 if (~isstruct(md.children))
1173     error('btk:C3Dserver', 'No group and parameter.');
1174 end
1175 labels = fieldnames(md.children);
1176 parent = [];
1177     for i = 1:length(labels)
1178         if strcmp(group, labels{i})
1179             parent = md.children.(labels{i});
1180             idxGr = i;
1181             break;
1182         end
1183     end
1184 if isempty(parent)
1185     error('btk:C3Dserver','Could not find the selected group.');
1186 end
1187 if (isstruct(parent.children))
1188     labels = fieldnames(parent.children);
1189     for i = 1:length(labels)
1190         if (strcmp(name, labels{i}))
1191             error('btk:C3Dserver','This parameter already exists within the group.');
1192         elseif (btkC3DserverHandles(idx).strictChecking ~= 0)
1193             name_ = name;
1194             if (length(name_) > 6)
1195                 name_ = name_(1:6);
1196             end
1197             label_ = labels{i};
1198             if (length(label_) > 6)
1199                 label_ = label_(1:6);
1200             end
1201             if (strcmp(name_, label_))
1202                 error('btk:C3Dserver','This parameter already exists within the group.');
1203             end
1204         end
1205     end
1206     idxPr = length(labels) + 1;
1207 end
1208 switch t
1209     case -1
1210         format = 'Char';
1211     case 1
1212         format = 'Byte';
1213     case 2
1214         format = 'Integer';
1215     case 4
1216         format = 'Real';
1217     otherwise
1218         error('btk:C3Dserver','The given parameter''s type is unsupported.');
1219 end
1220 if (numDim ~= numel(dimList))
1221     dimList = ones(1,numDim);
1222     if (t == -1)
1223         data = {};
1224     else
1225         data = 1;
1226     end
1227 end
1228 if (t ~= -1)
1229     data = double(data); % Adapt the data for btkAppendMetaData
1230 end
1231 try
1232     btkAppendMetaData(h, group, name, btkMetaDataInfo(format, data(:)));
1233     btkSetMetaDataDimensions(h, group, name, double(dimList));
1234     if (locked == char(0))
1235         btkSetMetaDataUnlock(h, group, name, 1);
1236     else
1237         btkSetMetaDataUnlock(h, group, name, 0);
1238     end
1239     btkSetMetaDataDescription(h, group, name, desc);
1240     res = btkC3DserverGetNumberParameters(id)-1;
1241     btkC3DserverHandles(idx).parameterIndexMapping(end+1,:) = {[idxGr, idxPr], res};
1242     %res = btkC3DserverGetParameterIndex(id, group, name);
1243 catch
1244     err = lasterror();
1245     error('btk:C3Dserver', ['Internal error: ', err.message]);
1246 end
1247 % Why C3Dserver doesn't set the flag modified to true?
1248 %btkC3DserverSetModified_p(idx,1);
1249
1250
1251 function res = btkC3DserverDeleteParameter(id, index)
1252 global btkC3DserverHandles;
1253 [h, idx] = btkC3DserverExtractHandle_p(id);
1254 [temp indices] = btkC3DserverExtractParameter_p(h, idx, index);
1255 try
1256     btkRemoveMetaData(h, indices(1), indices(2));
1257     res = 1; % Deleted
1258 catch
1259     err = lasterror();
1260     error('btk:C3Dserver', ['Internal error: ', err.message]);
1261 end
1262 % Update internal parameter index
1263 mapping = btkC3DserverHandles(idx).parameterIndexMapping;
1264 foo = [mapping{:,1}]; foo = reshape(foo, 2, length(foo)/2)';
1265 mapping = mapping(~((foo(:,1) == indices(1)) & (foo(:,2) == indices(2))),:);
1266 for i=1:size(mapping,1)
1267     if ((mapping{i,1}(1) == indices(1)) && (mapping{i,1}(2) > indices(2)))
1268         mapping{i,1}(2) = mapping{i,1}(2) - 1;
1269         mapping{i,2} = mapping{i,2} - 1;
1270     elseif (mapping{i,1}(1) > indices(1))
1271         mapping{i,2} = mapping{i,2} - 1;
1272     end
1273 end
1274 btkC3DserverHandles(idx).parameterIndexMapping = mapping;
1275 btkC3DserverSetModified_p(idx,1);
1276
1277
1278 function res = btkC3DserverCopyParameter(id, index)
1279 global btkC3DserverHandles;
1280 [h, idx] = btkC3DserverExtractHandle_p(id);
1281 parameter = btkC3DserverExtractParameter_p(h, idx, index);
1282 if ~iscell(parameter.info.values)
1283     parameter.info.values = {parameter.info.values};
1284 end
1285 btkC3DserverHandles(idx).copiedParameter = parameter;
1286 res = 1; % Copied
1287
1288 function res = btkC3DserverRetrieveParameter(id, index)
1289 global btkC3DserverHandles;
1290 [h, idx] = btkC3DserverExtractHandle_p(id);
1291 res = 0; % Not retrieved
1292 if isstruct(btkC3DserverHandles(idx).copiedParameter)
1293     indices = [];
1294     for i = 1:length(btkC3DserverHandles(idx).parameterIndexMapping)
1295         if (btkC3DserverHandles(idx).parameterIndexMapping{i,2} == index)
1296             indices = btkC3DserverHandles(idx).parameterIndexMapping{i,1};
1297             break;
1298         end
1299     end
1300     if isempty(indices)
1301         error('btk:C3Dserver', 'Invalid index has been used.');
1302     end
1303     try
1304         parameter = btkC3DserverHandles(idx).copiedParameter;
1305         btkSetMetaDataLabel(h, indices(1), indices(2), parameter.label);
1306         btkSetMetaDataFormat(h, indices(1), indices(2), parameter.info.format);
1307         btkSetMetaDataDimensions(h, indices(1), indices(2), parameter.info.dims);
1308         for i = 1:numel(parameter.info.values);
1309             btkSetMetaDataValue(h, indices(1), indices(2), i, parameter.info.values{i});
1310         end
1311         btkSetMetaDataUnlock(h, indices(1), indices(2), parameter.unlocked);
1312         btkSetMetaDataDescription(h, indices(1), indices(2), parameter.description);
1313     catch
1314         err = lasterror();
1315         error('btk:C3Dserver', ['Internal error: ', err.message]);
1316     end
1317     % No modification
1318     %btkC3DserverSetModified_p(idx,1);
1319     res = 1;
1320 end
1321
1322
1323 function res = btkC3DserverRemoveParameterData(id, index, item)
1324 [h, idx] = btkC3DserverExtractHandle_p(id);
1325 [parameter indices] = btkC3DserverExtractParameter_p(h, idx, index);
1326 if isstruct(parameter.info)
1327     if ~isempty(parameter.info.dims)
1328         if (~(strcmp(parameter.info.format, 'Char') && (numel(parameter.info.dims) == 1)) && (item < parameter.info.dims(end)))
1329             if (item < 0)
1330                 error('btk:C3Dserver', 'Invalid (negative) index has been used.');
1331             end
1332             if (strcmp(parameter.info.format, 'Char'))
1333                 idxStart = 2;
1334             else
1335                 idxStart = 1;
1336             end
1337             p = prod(parameter.info.dims(idxStart:end-1));
1338             offset = p * item;
1339             values = parameter.info.values;
1340             dims = parameter.info.dims;
1341             dims(end) = dims(end) - 1;
1342             values = values(:);
1343             values = values([1:offset,offset+p+1:end]);
1344             try
1345                 btkSetMetaDataDimensions(h,indices(1),indices(2),dims);
1346                 for j=1:length(values);
1347                     btkSetMetaDataValue(h,indices(1),indices(2),j,values(j));
1348                 end;
1349             catch
1350                 err = lasterror();
1351                 error('btk:C3Dserver', ['Internal error: ', err.message]);
1352             end
1353             % Not modified?
1354             %btkC3DserverSetModified_p(idx,1);
1355         end
1356         res = 1;
1357         return;
1358     end
1359 end
1360 res = 0;
1361
1362
1363 function res = btkC3DserverAddParameterData(id, index, items)
1364 [h, idx] = btkC3DserverExtractHandle_p(id);
1365 [parameter indices] = btkC3DserverExtractParameter_p(h, idx, index);
1366 if (items <= 0)
1367     error('btk:C3Dserver', 'Invalid value for the dimension.');
1368 end
1369 res = -1; % Not added
1370 if isstruct(parameter.info) && ~isempty(parameter.info.dims)
1371     dims = parameter.info.dims;
1372     dims(end) = dims(end) + items;
1373     try
1374         btkSetMetaDataDimensions(h,indices(1),indices(2),dims);
1375     catch
1376         err = lasterror();
1377         error('btk:C3Dserver', ['Internal error: ', err.message]);
1378     end
1379     % Not modified?
1380     %btkC3DserverSetModified_p(idx,1);
1381     res = 1;
1382 end
1383
1384
1385 function data = btkC3DserverGetAnalogData(id, channel, frame, subFrame, scaled, offset, scale, useScale)
1386 h = btkC3DserverExtractHandle_p(id);
1387 if ((channel < 0) || (channel >= btkGetAnalogNumber(h)))
1388     error('btk:C3Dserver','Invalid channel number.');
1389 elseif ((frame < btkGetFirstFrame(h)) || (frame > btkGetLastFrame(h)))
1390     error('btk:C3Dserver','Invalid frame number.');
1391 elseif ((subFrame < 1) || (subFrame > btkGetAnalogSampleNumberPerFrame(h)))
1392     error('btk:C3Dserver','Invalid subframe number.');
1393 end
1394 frame_ = (frame - btkGetFirstFrame(h)) * btkGetAnalogSampleNumberPerFrame(h) + subFrame;
1395 [data, info] = btkGetAnalog(h, channel+1);
1396 data = data(frame_);
1397 % Unscale the data
1398 offset_ = info.offset;
1399 scale_ = info.scale;
1400 data = data / scale_ + offset_;
1401 if (scaled == char(0)) % Unscaled data
1402     % Nothing to do
1403 elseif (useScale == char(0)) % Scaled data with acquisition's offset and scale
1404     % Rescale
1405     [rescale, reoffset] = btkC3DserverExtractAnalogInfos_p(h,channel+1);
1406     data = (data - reoffset) * rescale;
1407 else % Scaled with the given offset and scale
1408     % Rescale
1409     data = (data - offset) * scale;
1410 end
1411 data = single(data);
1412
1413
1414 function data = btkC3DserverGetAnalogDataEx(id, channel, startFrame, endFrame, scaled, offset, scale, useScale)
1415 global btkC3DserverHandles;
1416 [h, idx] = btkC3DserverExtractHandle_p(id);
1417 if ((channel < 0) || (channel >= btkGetAnalogNumber(h)))
1418     error('btk:C3Dserver','Invalid channel number.');
1419 elseif (endFrame < startFrame)
1420     error('btk:C3Dserver','End frame number lower than start frame number.');
1421 elseif ((startFrame < btkGetFirstFrame(h)) || (startFrame > btkGetLastFrame(h)))
1422     error('btk:C3Dserver','Invalid start frame number.');
1423 elseif ((endFrame < btkGetFirstFrame(h)) || (endFrame > btkGetLastFrame(h)))
1424     error('btk:C3Dserver','Invalid end frame number.');
1425 end
1426 sF = (startFrame - btkGetFirstFrame(h)) * btkGetAnalogSampleNumberPerFrame(h) + 1;
1427 eF = (endFrame - btkGetFirstFrame(h) + 1) * btkGetAnalogSampleNumberPerFrame(h);
1428 frames_ = sF:eF;
1429 [data_, info] = btkGetAnalog(h, channel+1);
1430 data_ = data_(frames_);
1431 % Unscale the data
1432 offset_ = info.offset;
1433 scale_ = info.scale;
1434 data_ = data_ / scale_ + offset_;
1435 if (scaled == 0) % Unscaled data
1436     if (btkC3DserverHandles(idx).dataType == 1) % Integer format
1437         data_ = int16(data_);
1438     else
1439         data_ = single(data_);
1440     end
1441 elseif (useScale == 0) % Scaled data with acquisition's offset and scale
1442     % Rescale
1443     [rescale, reoffset] = btkC3DserverExtractAnalogInfos_p(h,channel+1);
1444     data_ = (data_ - reoffset) * rescale;
1445     data_ = single(data_);
1446 else % Scaled with the given offset and scale
1447     % Rescale
1448     data_ = (data_ - offset) * scale;
1449     if (btkC3DserverHandles(idx).dataType == 1) % Integer format
1450         data_ = single(data_);
1451     end
1452 end
1453 data = num2cell(data_);
1454
1455
1456 function res = btkC3DserverSetAnalogData(id, channel, frame, subFrame, data)
1457 [h, idx] = btkC3DserverExtractHandle_p(id);
1458 if ((channel < 0) || (channel >= btkGetAnalogNumber(h)))
1459     error('btk:C3Dserver','Invalid channel number.');
1460 elseif ((frame < btkGetFirstFrame(h)) || (frame > btkGetLastFrame(h)))
1461     error('btk:C3Dserver','Invalid frame number.');
1462 elseif ((subFrame < 1) || (subFrame > btkGetAnalogSampleNumberPerFrame(h)))
1463     error('btk:C3Dserver','Invalid subframe number.');
1464 end
1465 frame_ = (frame - btkGetFirstFrame(h)) * btkGetAnalogSampleNumberPerFrame(h) + subFrame;
1466 [data_, info] = btkGetAnalog(h, channel+1);
1467 offset_ = info.offset;
1468 scale_ = info.scale;
1469 data_(frame_) = (data - offset_) * scale_ ;
1470 btkSetAnalogValues(h, channel+1, data_);
1471 btkC3DserverSetModified_p(idx,1);
1472 res = 1;
1473
1474
1475 function res = btkC3DserverSetAnalogDataEx(id, channel, frame, data)
1476 [h, idx] = btkC3DserverExtractHandle_p(id);
1477 if ((channel < 0) || (channel >= btkGetAnalogNumber(h)))
1478     error('btk:C3Dserver','Invalid channel number.');
1479 elseif ((frame < btkGetFirstFrame(h)) || (frame > btkGetLastFrame(h)))
1480     error('btk:C3Dserver','Invalid frame number.');
1481 elseif (size(data,1) ~= 1)
1482     error('btk:C3Dserver','Invalid data size. Must contain only one row.');
1483 elseif ~isa(data,'int16')
1484     error('btk:C3Dserver','Incorrect data type passed to the function.');
1485 end
1486 sF = (frame - btkGetFirstFrame(h)) * btkGetAnalogSampleNumberPerFrame(h) + 1;
1487 eF = btkGetAnalogFrameNumber(h);
1488 if ((sF + length(data)) <= eF)
1489     frames_ = sF:sF+length(data)-1;
1490 else
1491     frames_ = sF:eF;
1492 end
1493 [d, info] = btkGetAnalog(h, channel+1);
1494 offset_ = info.offset;
1495 scale_ = info.scale;
1496 d(frames_) = (double(data(1:length(frames_))) - offset_) * scale_ ;
1497 btkSetAnalogValues(h, channel+1, d);
1498 btkC3DserverSetModified_p(idx,1);
1499 res = 1;
1500
1501
1502 function res = btkC3DserverSetAVRatio(id, avRatio)
1503 [h, idx] = btkC3DserverExtractHandle_p(id);
1504 if (btkGetAnalogNumber(h) > 0)
1505     error('btk:C3Dserver','Analog channels already exists in the file.');
1506 elseif (avRatio < 0)
1507     error('btk:C3Dserver','You have to provide a ratio greater than or equal to zero.');
1508 end
1509 if (avRatio == 0)
1510     avRatio = 1;
1511 end
1512 btkSetAnalogSampleNumberPerFrame(h, round(avRatio));
1513 btkC3DserverSetModified_p(idx,1);
1514 res = 1;
1515
1516
1517 function index = btkC3DserverAddAnalogChannel(id)
1518 [h, idx] = btkC3DserverExtractHandle_p(id);
1519 data = zeros(btkGetAnalogFrameNumber(h),1);
1520 num = btkGetAnalogNumber(h)+1;
1521 [scale, offset, label, description, gain] = btkC3DserverExtractAnalogInfos_p(h,num);
1522 btkAppendAnalog(h, label, data, description);
1523 btkSetAnalogOffset(h, num, offset);
1524 btkSetAnalogScale(h, num, scale);
1525 btkSetAnalogGain(h, num, gain);
1526 analogUsed = btkFindMetaData(h, 'ANALOG', 'USED');
1527 btkAppendMetaData(h, 'ANALOG', 'USED', btkMetaDataInfo('Integer', num));
1528 if (isstruct(analogUsed) && ~isempty(analogUsed.description))
1529     btkSetMetaDataDescription(h,'ANALOG','USED',analogUsed.description);
1530 end
1531 index = num - 1;
1532 btkC3DserverSetModified_p(idx,1);
1533
1534
1535 function res = btkC3DserverDeleteAnalogChannel(id, index)
1536 [h, idx] = btkC3DserverExtractHandle_p(id);
1537 if ((index < 0) || (index >= btkGetAnalogNumber(h)))
1538     error('btk:C3Dserver','Invalid channel number.');
1539 end
1540 btkRemoveAnalog(h, index+1);
1541 btkAppendMetaData(h, 'ANALOG', 'USED', btkMetaDataInfo('Integer', btkGetAnalogNumber(h)));
1542 btkC3DserverSetModified_p(idx,1);
1543 res = 1;
1544
1545
1546 function res = btkC3DserverDeleteAnalogChannelWithParameter(id, index)
1547 [h, idx] = btkC3DserverExtractHandle_p(id);
1548 if ((index < 0) || (index >= btkGetAnalogNumber(h)))
1549     error('btk:C3Dserver','Invalid channel number.');
1550 end
1551 md = btkFindMetaData(h, 'FORCE_PLATFORM', 'CHANNEL');
1552 if (isstruct(md))
1553     if (find(md.info.values == index + 1))
1554         error('btk:C3Dserver','Based on C3dServer, it seems not possible to delete an analog channel used for the force platforms. Contact the developers if is not the case.');
1555     end
1556 end
1557 btkRemoveAnalog(h, index+1);
1558 btkAppendMetaData(h, 'ANALOG', 'USED', btkMetaDataInfo('Integer', btkGetAnalogNumber(h)));
1559 if (isstruct(md))
1560     channels = md.info.values;
1561     indices = find(channels > index + 1);
1562     channels(indices) = channels(indices) - 1;
1563     btkAppendMetaData(h, 'FORCE_PLATFORM', 'CHANNEL', btkMetaDataInfo('Integer', channels));
1564 end
1565 md = btkFindMetaData(h, 'ANALOG', 'LABELS');
1566 if (isstruct(md))
1567     labels = md.info.values;
1568     labels = labels(setdiff(1:length(labels),index+1));
1569     btkAppendMetaData(h, 'ANALOG', 'LABELS', btkMetaDataInfo('Char', labels));
1570 end
1571 md = btkFindMetaData(h, 'ANALOG', 'DESCRIPTIONS');
1572 if (isstruct(md))
1573     descs = md.info.values;
1574     descs = descs(setdiff(1:length(descs),index+1));
1575     btkAppendMetaData(h, 'ANALOG', 'DESCRIPTIONS', btkMetaDataInfo('Char', descs));
1576 end
1577 md = btkFindMetaData(h, 'ANALOG', 'SCALE');
1578 if (isstruct(md))
1579     scales = md.info.values;
1580     scales = scales(setdiff(1:length(scales),index+1));
1581     btkAppendMetaData(h, 'ANALOG', 'SCALE', btkMetaDataInfo('Real', scales));
1582 end
1583 md = btkFindMetaData(h, 'ANALOG', 'OFFSET');
1584 if (isstruct(md))
1585     offsets = md.info.values;
1586     offsets = offsets(setdiff(1:length(offsets),index+1));
1587     btkAppendMetaData(h, 'ANALOG', 'OFFSET', btkMetaDataInfo('Integer', offsets));
1588 end
1589 md = btkFindMetaData(h, 'ANALOG', 'UNITS');
1590 if (isstruct(md))
1591     units = md.info.values;
1592     units = units(setdiff(1:length(units),index+1));
1593     btkAppendMetaData(h, 'ANALOG', 'UNITS', btkMetaDataInfo('Char', units));
1594 end
1595 btkC3DserverSetModified_p(idx,1);
1596 res = 1;
1597
1598
1599 function data = btkC3DserverGetForceData(id, cord, fp, startFrame, endFrame)
1600 [h, frames] = btkC3DserverCheckFPInputs_p(id, 'F', cord, fp, startFrame, endFrame);
1601 try
1602     fpws = btkGetForcePlatformWrenches(h, 0); % Local frame
1603 catch
1604     err = lasterror();
1605     error('btk:C3Dserver', ['Internal error: ', err.message]);
1606 end
1607 if ((fp < 0) || (fp > length(fpws)))
1608     error('btk:C3Dserver', 'Incorrect force platform index.');
1609 end
1610 data_ = fpws(fp+1).F;
1611 data_ = single(data_(frames,cord+1));
1612 data = cell(length(frames),1);
1613 for i=1:length(frames)
1614     data{i} = data_(i);
1615 end
1616
1617
1618 function data = btkC3DserverGetMomentData(id, cord, fp, startFrame, endFrame)
1619 % error('btk:C3Dserver','Method GetMomentData not yet implemented.');
1620 [h, frames] = btkC3DserverCheckFPInputs_p(id, 'M', cord, fp, startFrame, endFrame);
1621 try
1622     grws = btkGetGroundReactionWrenches(h, 5); % Check for the threshold!
1623 catch
1624     err = lasterror();
1625     error('btk:C3Dserver', ['Internal error: ', err.message]);
1626 end
1627 if ((fp < 0) || (fp > length(grws)))
1628     error('btk:C3Dserver', 'Incorrect force platform index.');
1629 end
1630 if (cord == 0)
1631     data_ = grws(fp+1).P(:,1); % Px
1632 elseif (cord == 1)
1633     data_ = grws(fp+1).P(:,2); % Py
1634 else
1635     data_ = grws(fp+1).M(:,3); % Tz
1636 end
1637 data_ = single(data_(frames));
1638 data = cell(length(frames),1);
1639 for i=1:length(frames)
1640     data{i} = data_(i);
1641 end
1642
1643
1644 function res = btkC3DserverZeroAnalogChannel(id, channel, method, frames)
1645 [h, idx] = btkC3DserverExtractHandle_p(id);
1646 if ((channel < 0) || (channel >= btkGetAnalogNumber(h)))
1647     error('btk:C3Dserver','Invalid channel number.');
1648 elseif ((frames < 0) || (frames > btkGetPointFrameNumber(h)))
1649     error('btk:C3Dserver','Invalid frame number.');
1650 elseif isempty(intersect(method, 1:4))
1651     error('btk:C3Dserver','Incorrect method supplied to zero the analog channel.');
1652 elseif (~isempty(intersect(method, 3:4)) && ((frames < 1) || (frames > btkGetPointFrameNumber(h))))
1653     error('btk:C3Dserver','Incorrect number of frames supplied to zero the analog channel.');
1654 end
1655 [data, info] = btkGetAnalog(h,channel+1);
1656 % Unscale the data
1657 data = data / info.scale + info.offset;
1658 % Remove baseline
1659 if (method == 1)
1660     base = ceil(mean(data)) - info.offset;
1661 elseif (method == 2)
1662     base = 0;
1663     md = btkFindMetaData(h,'FORCE_PLATFORM','ZERO');
1664     if isstruct(md)
1665         sF = md.info.values(1);
1666         eF = md.info.values(2);
1667         if (sF == 0)
1668             sF = 1;
1669         end
1670         sF = 1 + (sF - 1) * btkGetAnalogSampleNumberPerFrame(h);
1671         eF = eF * btkGetAnalogSampleNumberPerFrame(h);
1672         base = ceil(mean(data(sF:eF))) - info.offset;
1673     end
1674 elseif (method == 3)
1675     base = ceil(mean(data(1:frames*btkGetAnalogSampleNumberPerFrame(h)))) - info.offset;
1676 elseif (method == 4)
1677     num = btkGetAnalogFrameNumber(h);
1678     base = ceil(mean(data(num-frames*btkGetAnalogSampleNumberPerFrame(h)+1:num))) - info.offset;
1679 end
1680 data = data - base;
1681 % Rescale data
1682 data = (data - info.offset) * info.scale;
1683 % Store modified data
1684 btkSetAnalogValues(h, channel+1, data);
1685 btkC3DserverSetModified_p(idx,1);
1686 res = 1;
1687
1688
1689 function data = btkC3DserverGetPointData(id, channel, cord, frame, scaled)
1690 global btkC3DserverHandles;
1691 [h, idx] = btkC3DserverExtractHandle_p(id);
1692 if ((channel < 0) || (channel >= btkGetPointNumber(h)))
1693     error('btk:C3Dserver','Invalid channel number.');
1694 elseif ((frame < btkGetFirstFrame(h)) || (frame > btkGetLastFrame(h)))
1695     error('btk:C3Dserver','Invalid frame number.');
1696 elseif ((cord < 0) || (cord > 2))
1697     error('btk:C3Dserver','Invalid Index has been used.');
1698 end
1699 frame = frame - btkGetFirstFrame(h) + 1;
1700 data = btkGetPoint(h, channel+1);
1701 data = data(frame,cord+1);
1702 % Unscale the data (if necessary)
1703 if ((btkC3DserverHandles(idx).dataType == 1) && (scaled == char(0)))
1704     data = data / btkC3DserverHandles(idx).scalingFactor;
1705 end
1706 data = single(data);
1707
1708
1709 function data = btkC3DserverGetPointDataEx(id, channel, cord, startFrame, endFrame, scaled)
1710 global btkC3DserverHandles;
1711 [h, idx] = btkC3DserverExtractHandle_p(id);
1712 if ((channel < 0) || (channel >= btkGetPointNumber(h)))
1713     error('btk:C3Dserver','Invalid channel number.');
1714 elseif (endFrame < startFrame)
1715     error('btk:C3Dserver','End frame number lower than start frame number.');
1716 elseif ((startFrame < btkGetFirstFrame(h)) || (startFrame > btkGetLastFrame(h)))
1717     error('btk:C3Dserver','Invalid start frame number.');
1718 elseif ((endFrame < btkGetFirstFrame(h)) || (endFrame > btkGetLastFrame(h)))
1719     error('btk:C3Dserver','Invalid end frame number.');
1720 elseif ((cord < 0) || (cord > 2))
1721     error('btk:C3Dserver','Invalid Index has been used.');
1722 end
1723 start_ = startFrame - btkGetFirstFrame(h) + 1;
1724 end_ = endFrame - btkGetFirstFrame(h) + 1;
1725 data_ = btkGetPoint(h, channel+1);
1726 frames = start_:end_;
1727 data_ = data_(frames,cord+1);
1728 % Unscale the data (if necessary)
1729 if ((btkC3DserverHandles(idx).dataType == 1) && (scaled == char(0)))
1730     data_ = data_ / btkC3DserverHandles(idx).scalingFactor;
1731     data_ = int16(data_);
1732 else
1733     data_ = single(data_);
1734 end
1735 data = num2cell(data_);
1736
1737
1738 function data = btkC3DserverGetPointResidualEx(id, channel, startFrame, endFrame)
1739 h = btkC3DserverExtractHandle_p(id);
1740 if ((channel < 0) || (channel >= btkGetPointNumber(h)))
1741     error('btk:C3Dserver','Invalid channel number.');
1742 elseif (endFrame < startFrame)
1743     error('btk:C3Dserver','End frame number lower than start frame number.');
1744 elseif ((startFrame < btkGetFirstFrame(h)) || (startFrame > btkGetLastFrame(h)))
1745     error('btk:C3Dserver','Invalid start frame number.');
1746 elseif ((endFrame < btkGetFirstFrame(h)) || (endFrame > btkGetLastFrame(h)))
1747     error('btk:C3Dserver','Invalid end frame number.');
1748 end
1749 start_ = startFrame - btkGetFirstFrame(h) + 1;
1750 end_ = endFrame - btkGetFirstFrame(h) + 1;
1751 frames = start_:end_;
1752 [values, data_] = btkGetPoint(h, channel+1);
1753 data = num2cell(data_(frames));
1754
1755
1756 function data = btkC3DserverGetPointResidual(id, channel, frame)
1757 h = btkC3DserverExtractHandle_p(id);
1758 if ((channel < 0) || (channel >= btkGetPointNumber(h)))
1759     error('btk:C3Dserver','Invalid channel number.');
1760 elseif ((frame < btkGetFirstFrame(h)) || (frame > btkGetLastFrame(h)))
1761     error('btk:C3Dserver','Invalid frame number.');
1762 end
1763 frame = frame - btkGetFirstFrame(h) + 1;
1764 [values, data] = btkGetPoint(h, channel+1);
1765 data = data(frame);
1766
1767
1768 function data = btkC3DserverGetPointMask(id, channel, frame)
1769 h = btkC3DserverExtractHandle_p(id);
1770 if ((channel < 0) || (channel >= btkGetPointNumber(h)))
1771     error('btk:C3Dserver','Invalid channel number.');
1772 elseif ((frame < btkGetFirstFrame(h)) || (frame > btkGetLastFrame(h)))
1773     error('btk:C3Dserver','Invalid frame number.');
1774 end
1775 warning('btk:C3Dserver:FakeMask', 'The library BTK doesn''t support anymore the camera mask. Nothing is set. If you access to the mask, all the returned values are set to ''0000000''.');
1776 data = '0000000';
1777
1778 function data = btkC3DserverGetPointMaskEx(id, channel, startFrame, endFrame)
1779 h = btkC3DserverExtractHandle_p(id);
1780 if ((channel < 0) || (channel >= btkGetPointNumber(h)))
1781     error('btk:C3Dserver','Invalid channel number.');
1782 elseif (endFrame < startFrame)
1783     error('btk:C3Dserver','End frame number lower than start frame number.');
1784 elseif ((startFrame < btkGetFirstFrame(h)) || (startFrame > btkGetLastFrame(h)))
1785     error('btk:C3Dserver','Invalid start frame number.');
1786 elseif ((endFrame < btkGetFirstFrame(h)) || (endFrame > btkGetLastFrame(h)))
1787     error('btk:C3Dserver','Invalid end frame number.');
1788 end
1789 warning('btk:C3Dserver:FakeMask', 'The library BTK doesn''t support anymore the camera mask. Nothing is set. If you access to the mask, all the returned values are set to ''0000000''.');
1790 data = repmat({'0000000'},endFrame-startFrame+1,1);
1791
1792
1793 function res = btkC3DserverSetPointData(id, channel, cord, frame, data)
1794 global btkC3DserverHandles;
1795 [h, idx] = btkC3DserverExtractHandle_p(id);
1796 if ((channel < 0) || (channel >= btkGetPointNumber(h)))
1797     error('btk:C3Dserver','Invalid channel number.');
1798 elseif ((cord < 0) || (cord > 4))
1799     error('btk:C3Dserver','Invalid has been used.');
1800 elseif ((frame < btkGetFirstFrame(h)) || (frame > btkGetLastFrame(h)))
1801     error('btk:C3Dserver','Invalid frame number.');
1802 end
1803 frame_ = frame - btkGetFirstFrame(h) + 1;
1804 scale = 1;
1805 md = btkFindMetaData(h, 'POINT', 'SCALE');
1806 if (isstruct(md) && isstruct(md.info))
1807     scale = abs(md.info.values(1));
1808 end
1809 if (cord <= 2)
1810     data_ = btkGetPoint(h, channel+1);
1811     data = double(data);
1812     if (btkC3DserverHandles(idx).dataType == 1) % Integer
1813         data = data * scale;
1814     end
1815     data_(frame_,cord+1) = data;
1816     btkSetPointValues(h, channel+1, data_);
1817 elseif (cord == 3)
1818     [values, data_] = btkGetPoint(h, channel+1);
1819     data_(frame_) = floor(double(data) / scale) * scale;
1820     btkSetPointResiduals(h, channel+1, data_);
1821 elseif (cord == 4)
1822     warning('btk:C3Dserver:FakeMask', 'The library BTK doesn''t support anymore the camera mask. Nothing is set. If you access to the mask, all the returned values are set to ''0000000''.');
1823 end
1824 btkC3DserverSetModified_p(idx,1);
1825 res = 1;
1826
1827
1828 function res = btkC3DserverSetPointDataEx(id, channel, cord, frame, data)
1829 global btkC3DserverHandles;
1830 [h, idx] = btkC3DserverExtractHandle_p(id);
1831 if ((channel < 0) || (channel >= btkGetPointNumber(h)))
1832     error('btk:C3Dserver','Invalid channel number.');
1833 elseif ((frame < btkGetFirstFrame(h)) || (frame > btkGetLastFrame(h)))
1834     error('btk:C3Dserver','Invalid start frame number.');
1835 elseif ((cord < 0) || (cord > 4))
1836     error('btk:C3Dserver','Invalid has been used.');
1837 elseif (size(data,1) ~= 1)
1838     error('btk:C3Dserver','Invalid data size. Must contain only one row.');
1839 end
1840 sF = frame - btkGetFirstFrame(h) + 1;
1841 eF = btkGetPointFrameNumber(h);
1842 if ((sF + length(data)) <= eF)
1843     frames = sF:sF+length(data)-1;
1844 else
1845     frames = sF:eF;
1846     data = data(1:length(frames));
1847 end
1848 scale = 1;
1849 md = btkFindMetaData(h, 'POINT', 'SCALE');
1850 if (isstruct(md) && isstruct(md.info))
1851     scale = abs(md.info.values(1));
1852 end
1853 if (cord <= 2)
1854     data_ = btkGetPoint(h, channel+1);
1855     data = double(data);
1856     if (btkC3DserverHandles(idx).dataType == 1) % Integer
1857         data = data * scale;
1858     end
1859     data_(frames,cord+1) = data;
1860     btkSetPointValues(h, channel+1, data_);
1861 elseif (cord == 3)
1862     [values, data_] = btkGetPoint(h, channel+1);
1863     data_(frames) = floor(double(data) / scale) * scale;
1864     btkSetPointResiduals(h, channel+1, data_);
1865 elseif (cord == 4)
1866     warning('btk:C3Dserver:FakeMask', 'The library BTK doesn''t support anymore the camera mask. Nothing is set. If you access to the mask, all the returned values are set to ''0000000''.');
1867 end
1868 btkC3DserverSetModified_p(idx,1);
1869 res = 1;
1870
1871
1872 function index = btkC3DserverAddMarker(id)
1873 [h, idx] = btkC3DserverExtractHandle_p(id);
1874 % index = -1; % Not modified
1875 data = zeros(btkGetPointFrameNumber(h),3);
1876 num = btkGetPointNumber(h) + 1;
1877 label = ['uname*', num2str(num)];
1878 btkAppendPoint(h, 'Marker', label, data);
1879 btkAppendMetaData(h, 'POINT', 'USED', btkMetaDataInfo('Integer', num));
1880 btkC3DserverSetModified_p(idx,1);
1881 index = num-1;
1882
1883
1884 function res = btkC3DserverDeleteMarker(id, index)
1885 [h, idx] = btkC3DserverExtractHandle_p(id);
1886 % res = 0; % Not removed
1887 if (index >= btkGetPointNumber(h))
1888     error('btk:C3Dserver','Invalid point number.');
1889 end
1890 btkRemovePoint(h, index+1);
1891 btkAppendMetaData(h, 'POINT', 'USED', btkMetaDataInfo('Integer', btkGetPointNumber(h)));
1892 res = 1;
1893 btkC3DserverSetModified_p(idx,1);
1894
1895 function res = btkC3DserverDeleteMarkerWithParameter(id, index)
1896 [h, idx] = btkC3DserverExtractHandle_p(id);
1897 % res = 0; % Not removed
1898 if (index >= btkGetPointNumber(h))
1899     error('btk:C3Dserver','Invalid channel number.');
1900 end
1901 btkRemovePoint(h, index+1);
1902 btkAppendMetaData(h, 'POINT', 'USED', btkMetaDataInfo('Integer', btkGetPointNumber(h)));
1903 md = btkFindMetaData(h, 'POINT', 'LABELS');
1904 if (isstruct(md))
1905     labels = md.info.values;
1906     labels = labels(setdiff(1:length(labels),index+1));
1907     btkAppendMetaData(h, 'POINT', 'LABELS', btkMetaDataInfo('Char', labels));
1908 end
1909 md = btkFindMetaData(h, 'POINT', 'DESCRIPTIONS');
1910 if (isstruct(md))
1911     descs = md.info.values;
1912     descs = descs(setdiff(1:length(descs),index+1));
1913 %     btkAppendMetaData(h, 'POINT', 'DESCRIPTIONS', btkMetaDataInfo('Char', descs));
1914 end
1915 res = 1;
1916 btkC3DserverSetModified_p(idx,1);
1917
1918
1919 function num = btkC3DserverAddFrames(id, frames, insertAt)
1920 [h, idx] = btkC3DserverExtractHandle_p(id);
1921 ff = btkGetFirstFrame(h);
1922 lf = btkGetLastFrame(h);
1923 snpf = btkGetAnalogSampleNumberPerFrame(h);
1924 % num = -1; % Not modified
1925 if (frames < 0)
1926     error('btk:C3Dserver','Negative number of frames.');
1927 elseif (insertAt == -1)
1928     insertAt = ff;
1929 elseif (insertAt == -2)
1930     insertAt = lf+1;
1931 % elseif ((insertAt < ff) || insertAt > lf)
1932 %     error('btk:C3Dserver', 'Invalid insert index.');
1933 else
1934     error('btk:C3Dserver','As C3dServer under Matlab seems to not give the possibilty to insert frame other than using the index -1 and -2, we decide to do the same. If it is not the case, please contact the developers.');
1935 end
1936 num = btkGetPointFrameNumber(h) + frames;
1937 btkSetFrameNumber(h, num);
1938 % Modifying points
1939 pidx = insertAt:insertAt+frames-1;
1940 newDataIdx = insertAt+frames:num;
1941 oldDataIdx = insertAt:num-frames;
1942 % - values
1943 pv = btkGetPointsValues(h);
1944 pv(newDataIdx,:) = pv(oldDataIdx,:);
1945 pv(pidx,:) = zeros(length(pidx), 3 * btkGetPointNumber(h));
1946 btkSetPointsValues(h,pv);
1947 % - residuals
1948 rv = btkGetPointsResiduals(h);
1949 rv(newDataIdx,:) = rv(oldDataIdx,:);
1950 rv(pidx,:) = zeros(length(pidx), btkGetPointNumber(h));
1951 btkSetPointsResiduals(h,rv);
1952 % Modifying analog channels
1953 aidx = (insertAt-1)*snpf+1:(insertAt+frames-1)*snpf;
1954 av = btkGetAnalogsValues(h);
1955 av(aidx(end)+1:end,:) = av(aidx(1):end-frames*snpf,:);
1956 av(aidx,:) = zeros(length(aidx), btkGetAnalogNumber(h));
1957 btkSetAnalogsValues(h, av);
1958 % Update the parameter POINT:FRAMES
1959 btkAppendMetaData(h, 'POINT', 'FRAMES', btkMetaDataInfo('Integer', num));
1960 btkC3DserverSetModified_p(idx,1);
1961
1962
1963 function num = btkC3DserverDeleteFrames(id, startAt, frames)
1964 [h, idx] = btkC3DserverExtractHandle_p(id);
1965 ff = btkGetFirstFrame(h);
1966 lf = btkGetLastFrame(h);
1967 snpf = btkGetAnalogSampleNumberPerFrame(h);
1968 % num = -1; % Not modified
1969 if ((startAt < ff) || startAt > lf)
1970     error('btk:C3Dserver','Invalid index.');
1971 elseif (frames > lf - startAt + 1)
1972     error('btk:C3Dserver','Incorrect number of frames specified.')
1973 elseif (frames == lf - ff + 1) % Clear all
1974     error('btk:C3Dserver','Due to the mechanism used in BTK, it is not possible to remove all the frames. Contact the developers if you really need it.')
1975 end
1976 % Data to keep
1977 % - Point
1978 pidx = setdiff(ff:lf, startAt:startAt+frames-1)-ff+1;
1979 pv = btkGetPointsValues(h);
1980 pv = pv(pidx,:);
1981 rv = btkGetPointsResiduals(h);
1982 rv = rv(pidx,:);
1983 % - Analog
1984 aidx = setdiff(ff:lf*snpf, ((startAt-1)*snpf)+ff:(startAt+frames-1)*snpf)-ff+1;
1985 av = btkGetAnalogsValues(h);
1986 av = av(aidx,:);
1987 % Resizing
1988 num = btkGetPointFrameNumber(h) - frames;
1989 btkSetFrameNumber(h, num);
1990 % Storing modifications
1991 btkSetPointsValues(h,pv);
1992 btkSetPointsResiduals(h,rv);
1993 btkSetAnalogsValues(h, av);
1994 % Update the parameter POINT:FRAMES
1995 btkAppendMetaData(h, 'POINT', 'FRAMES', btkMetaDataInfo('Integer', num));
1996 btkC3DserverSetModified_p(idx,1);
1997
1998
1999 % -------------------------------------------------------------------------
2000 % Private functions
2001 % -------------------------------------------------------------------------
2002
2003 % Create a new handle and return its ID.
2004 function id = btkC3DserverRequestNewHandle_p()
2005 global btkC3DserverHandles;
2006 id = size(btkC3DserverHandles,2);
2007 idx = id + 1;
2008 btkC3DserverHandles(idx).id = id;
2009 btkC3DserverHandles(idx).handle = NaN;
2010 btkC3DserverHandles(idx).file = '';
2011 btkC3DserverHandles(idx).fileType = 0;
2012 btkC3DserverHandles(idx).dataType = 0;
2013 btkC3DserverHandles(idx).scalingFactor = 1;
2014 btkC3DserverHandles(idx).modified = 0;
2015 btkC3DserverHandles(idx).strictChecking = 1;
2016 btkC3DserverHandles(idx).parameterIndexMapping = {};
2017 btkC3DserverHandles(idx).copiedParameter = 0;
2018 btkC3DserverHandles(idx).hiddenParameterEvents = [0,0];
2019
2020 % Check if the given ID is valid and then return the index of the associated index.
2021 function idx = btkC3DserverCheckHandleID_p(id)
2022 global btkC3DserverHandles;
2023 idx = NaN;
2024 for i=1:size(btkC3DserverHandles,2)
2025     if (btkC3DserverHandles(i).id == id)
2026         idx = i;
2027         break;
2028     end
2029 end
2030 if isnan(idx)
2031     error('Unknown C3Dserver handle ID.');
2032 end
2033
2034 % Check if the handle at the index 'idx' is valid (not NaN).
2035 function res = btkC3DserverCheckHandleValue_p(idx)
2036 global btkC3DserverHandles;
2037 res = 0;
2038 if (isnan(btkC3DserverHandles(idx).handle))
2039     res = 1;
2040 end
2041
2042
2043 % Check the validity of the ID, the value of the handle and extract it.
2044 function [h, idx] = btkC3DserverExtractHandle_p(id)
2045 global btkC3DserverHandles;
2046 idx = btkC3DserverCheckHandleID_p(id);
2047 if (btkC3DserverCheckHandleValue_p(idx) ~= 0)
2048     error('File is not open.');
2049 end
2050 h = btkC3DserverHandles(idx).handle;
2051
2052
2053 % Set the handle as modified
2054 function btkC3DserverSetModified_p(idx, s)
2055 global btkC3DserverHandles;
2056 btkC3DserverHandles(idx).modified = s;
2057
2058
2059 % Return the parameter associated with the given index
2060 function [parameter, indices, parent] = btkC3DserverExtractParameter_p(h, idx, index)
2061 global btkC3DserverHandles;
2062 index_ = find([btkC3DserverHandles(idx).parameterIndexMapping{:,2}] == index);
2063 if isempty(index_)
2064     error('btk:C3Dserver', 'Invalid index has been used.');
2065 elseif (length(index_) ~= 1)
2066     error('btk:C3Dserver', 'Duplicated internal parameter index.');
2067 else
2068     indices = btkC3DserverHandles(idx).parameterIndexMapping{index_,1};
2069     try
2070         md = btkGetMetaData(h);
2071         if (isstruct(md.children))
2072             labels = fieldnames(md.children);
2073             if (size(labels,1) < indices(1))
2074                 error('btk:C3Dserver', 'Invalid internal group index.');
2075             end
2076             children = md.children.(labels{indices(1)}).children;
2077             if (isstruct(children))
2078                 labels_ = fieldnames(children);
2079                 if (size(labels_,1) < indices(2))
2080                     error('btk:C3Dserver', 'Invalid internal parameter index.');
2081                 else
2082                     label = labels_{indices(2)};
2083                     parameter = children.(label);
2084                     parameter.label = label;
2085                     parameter.id = indices(1);
2086                     parent = md.children.(labels{indices(1)});
2087                     return;
2088                 end
2089             else
2090                 error('btk:C3Dserver', 'Invalid internal parameter index (no parameter).');
2091             end
2092         else
2093             error('btk:C3Dserver', 'No group and parameter.');
2094         end
2095     catch
2096         err = lasterror();
2097         error('btk:C3Dserver', ['Internal error: ', err.message]);
2098     end
2099 end
2100
2101 function parameter = btkC3DserverGetCopiedParameter_p(idx)
2102 global btkC3DserverHandles;
2103 if ~isstruct(btkC3DserverHandles(idx).copiedParameter)
2104     error('btk:C3Dserver', 'Invalid index has been used.');
2105 end
2106 parameter = btkC3DserverHandles(idx).copiedParameter;
2107
2108 function btkC3DserverModifyCopiedParameter_p(idx, field, value, item)
2109 global btkC3DserverHandles;
2110 if ~isstruct(btkC3DserverHandles(idx).copiedParameter)
2111     error('btk:C3Dserver', 'Invalid index has been used.');
2112 end
2113 if (nargin == 4) % info.values
2114     values = btkC3DserverHandles(idx).copiedParameter.(field{1}).(field{2});
2115     if (item > numel(values))
2116         error('btk:C3Dserver', 'Invalid index has been used.')
2117     end
2118     values{item+1} = value;
2119     btkC3DserverHandles(idx).copiedParameter.(field{1}).(field{2}) = values;
2120 elseif (iscell(field)) % info.*
2121     btkC3DserverHandles(idx).copiedParameter.(field{1}).(field{2}) = value;
2122 else
2123     btkC3DserverHandles(idx).copiedParameter.(field) = value;
2124 end
2125
2126 function [scale, offset, label, description, gain] = btkC3DserverExtractAnalogInfos_p(h,index)
2127 scale = 1;
2128 gen_scale = 1;
2129 offset = 0;
2130 label = ['uname_', num2str(index)];
2131 gain = 0;
2132 description = '';
2133 md = btkGetMetaData(h);
2134 if (isstruct(md.children) && isfield(md.children, 'ANALOG'))
2135     md = md.children.ANALOG;
2136     if (isstruct(md.children))
2137         % SCALE
2138         if (isfield(md.children, 'SCALE') && isstruct(md.children.SCALE.info) && (numel(md.children.SCALE.info.values) >= index))
2139             scale = md.children.SCALE.info.values(index);
2140         end
2141         % GEN_SCALE
2142         if (isfield(md.children, 'GEN_SCALE') && isstruct(md.children.GEN_SCALE.info))
2143             gen_scale = md.children.GEN_SCALE.info.values(1);
2144         end
2145         scale = scale * gen_scale;
2146         % OFFSET
2147         if (isfield(md.children, 'OFFSET') && isstruct(md.children.OFFSET.info) && (numel(md.children.OFFSET.info.values) >= index))
2148             format = 'Signed';
2149             offsets = md.children.OFFSET.info.values;
2150 %             bits = 12;
2151 %             format = 'Signed';
2152 %             if (isfield(md.children, 'BITS') && isstruct(md.children.BITS.info))
2153 %                 bits = md.children.BITS.info.values(1);
2154 %             end
2155             if (isfield(md.children, 'FORMAT') && isstruct(md.children.FORMAT.info))
2156                 format = md.children.FORMAT.info.values{1};
2157             end
2158 %             % Check
2159 %             inc = 1;
2160 %             while (inc <= numel(offsets))
2161 %                 if (offsets(inc) > 2^bits)
2162 %                     bits = bits * 2;
2163 %                 else
2164 %                     inc = inc + 1;
2165 %                 end
2166 %             end
2167 %             if (bits >= 16)
2168 %                 format = 'Unsigned';
2169 %             end
2170             offset = offsets(index);
2171             if (strcmpi(format,'Unsigned'))
2172                 offset = double(typecast(int16(offset), 'uint16'));
2173             end
2174         end
2175         % LABELS
2176         if (isfield(md.children, 'LABELS') && isstruct(md.children.LABELS.info) && (numel(md.children.LABELS.info.values) >= index))
2177             label = md.children.LABELS.info.values{index};
2178         end
2179         % DESCRIPTIONS
2180         if (isfield(md.children, 'DESCRIPTIONS') && isstruct(md.children.DESCRIPTIONS.info) && (numel(md.children.DESCRIPTIONS.info.values) >= index))
2181             description = md.children.DESCRIPTIONS.info.values{index};
2182         end
2183         % GAIN
2184         if (isfield(md.children, 'GAIN') && isstruct(md.children.GAIN.info) && (numel(md.children.GAIN.info.values) >= index))
2185             gain = md.children.GAIN.info.values(index);
2186         end
2187     end
2188 end
2189
2190 function [h, frames] = btkC3DserverCheckFPInputs_p(id, component, cord, fp, startFrame, endFrame)
2191 h = btkC3DserverExtractHandle_p(id);
2192 switch component
2193     case 'F'
2194         cpt = 'force';
2195     case 'M'
2196         cpt = 'moment';
2197 end
2198 if ((startFrame == -1) && (endFrame == -1))
2199     startFrame = btkGetFirstFrame(h);
2200     endFrame = btkGetLastFrame(h);
2201 end
2202 if ((cord < 0) || (cord > 2))
2203     error('btk:C3Dserver', ['Incorrect ', cpt, ' component.']);
2204 elseif ((startFrame < btkGetFirstFrame(h)) || (startFrame > btkGetLastFrame(h)))
2205     error('btk:C3Dserver', 'Incorrect start index.');
2206 elseif ((endFrame < btkGetFirstFrame(h)) || (endFrame > btkGetLastFrame(h)))
2207     error('btk:C3Dserver', 'Invalid end index.');
2208 elseif (endFrame < startFrame)
2209     error('btk:C3Dserver', 'End index lower then start index.');
2210 end
2211 sF = (startFrame - btkGetFirstFrame(h)) * btkGetAnalogSampleNumberPerFrame(h) + 1;
2212 eF = (endFrame - btkGetFirstFrame(h) + 1) * btkGetAnalogSampleNumberPerFrame(h);
2213 frames = sF:eF;
2214
2215 % Last input is the description
2216 function btkC3DserverAddMetaData_p(h, varargin)
2217 btkAppendMetaData(h, varargin{1:end-1});
2218 if (isstruct(varargin{end-1}))
2219     btkSetMetaDataDescription(h, varargin{1:end-2}, varargin{end});
2220 else
2221     btkSetMetaDataDescription(h, varargin{1:end-1}, varargin{end});
2222 end
2223
2224 function num = btkC3DserverGetEventNumber_p(h,idx)
2225 global btkC3DserverHandles;
2226 num = btkGetEventNumber(h) - btkC3DserverHandles(idx).hiddenParameterEvents(2);
2227
2228 function index_ = btkC3DserverGetEventIndex_p(index,idx)
2229 global btkC3DserverHandles;
2230 index_ = index + 1;
2231 if (index_ >= btkC3DserverHandles(idx).hiddenParameterEvents(1))
2232     index_ = index_ + btkC3DserverHandles(idx).hiddenParameterEvents(2);
2233 end