Description of btkGetEventNumber
btkGetEventNumber
PURPOSE
BTKGETEVENTNUMBER Return the number of events.
SYNOPSIS
function num = btkGetEventNumber(h)
DESCRIPTION
BTKGETEVENTNUMBER Return the number of events.
  NUM = BTKGETEVENTNUMBER(H) returns the number of events associated with the
  acquisitions reprenseted by the handle. This handle is obtained by the use of
  a btk* function.
CROSS-REFERENCE INFORMATION
This function calls:
btkGetEventsValues BTKGETEVENTSVALUES Extract events' values from a biomechanical acquisition
btkGetEventsValues BTKGETEVENTSVALUES Extract events' values from a biomechanical acquisition
btkGetEventsValues BTKGETEVENTSVALUES Extract events' values from a biomechanical acquisition
This function is called by:
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
SOURCE CODE
function num = btkGetEventNumber(h)
%BTKGETEVENTNUMBER Return the number of events.
%
%  NUM = BTKGETEVENTNUMBER(H) returns the number of events associated with the
%  acquisitions reprenseted by the handle. This handle is obtained by the use of
%  a btk* function.
%  Author: A. Barré
%  Copyright 2009-2013 Biomechanical ToolKit (BTK).
num = length(btkGetEventsValues(h));