Description of MuscleForcesComputation
Home > Functions > MuscleForces > MuscleForcesComputation.m
MuscleForcesComputation
PURPOSE
Computation of the muscle forces estimation step
SYNOPSIS
function [] = MuscleForcesComputation(AnalysisParameters)
DESCRIPTION
 Computation of the muscle forces estimation step
   Computation of muscle forces from joint torques and a
   biomechanical model
   INPUT
   - AnalysisParameters: parameters of the musculoskeletal analysis,
   automatically generated by the graphic interface 'Analysis'.%
   OUTPUT
   Results are automatically saved on the folder associated to each motion
   capture in variable 'MuscleForcesComputationResults'.
________________________________________________________
 Licence
 Toolbox distributed under 3-Clause BSD License
________________________________________________________
CROSS-REFERENCE INFORMATION
This function calls:
ForcesComputationMusIC Computation of the muscle forces estimation step by using the MusIC method
ForcesComputationOpti Computation of the muscle forces estimation step by using an optimization method
This function is called by:
Main Main script of the Toolbox
SOURCE CODE
function [] = MuscleForcesComputation(AnalysisParameters)
% Computation of the muscle forces estimation step
%   Computation of muscle forces from joint torques and a
%   biomechanical model
%
%   INPUT
%   - AnalysisParameters: parameters of the musculoskeletal analysis,
%   automatically generated by the graphic interface 'Analysis'.%
%   OUTPUT
%   Results are automatically saved on the folder associated to each motion
%   capture in variable 'MuscleForcesComputationResults'.
%________________________________________________________
%
% Licence
% Toolbox distributed under 3-Clause BSD License
%________________________________________________________
load('BiomechanicalModel.mat'); %#ok<LOAD>
for i = 1:numel(AnalysisParameters.filename)
    filename = AnalysisParameters.filename{i}(1:end-4);
    if AnalysisParameters.Muscles.Method == 1
        [MuscleForcesComputationResults] = ForcesComputationOpti(filename, BiomechanicalModel, AnalysisParameters); %#ok<NASGU>
    elseif AnalysisParameters.Muscles.Method == 2
        [MuscleForcesComputationResults] = ForcesComputationMusIC(filename, BiomechanicalModel); %#ok<NASGU>
    end
    save([filename '/MuscleForcesComputationResults'],'MuscleForcesComputationResults');
end
end