Description of MuscleForcesComputationNum
MuscleForcesComputationNum
PURPOSE
Computation of the muscle forces estimation step
SYNOPSIS
function [] = MuscleForcesComputationNum(AnalysisParameters)
DESCRIPTION
 Computation of the muscle forces estimation step
   Computation of muscle forces from joint torques and a
   biomechanical model
   INPUT
   - AnalysisParameters: parameters of the musculoskeletal analysis,
   automatically generated by the graphic interface 'Analysis'.%
   OUTPUT
   Results are automatically saved on the folder associated to each motion
   capture in variable 'MuscleForcesComputationResults'.
________________________________________________________
 Licence
 Toolbox distributed under GPL 3.0 Licence
________________________________________________________
 Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
 Georges Dumont
________________________________________________________
CROSS-REFERENCE INFORMATION
This function calls:
ForcesComputationMusIC Computation of the muscle forces estimation step by using the MusIC method
ForcesComputationOptiNum Computation of the muscle forces estimation step by using an optimization method
This function is called by:
Main Main script of the Toolbox
SOURCE CODE
function [] = MuscleForcesComputationNum(AnalysisParameters)
% Computation of the muscle forces estimation step
%   Computation of muscle forces from joint torques and a
%   biomechanical model
%
%   INPUT
%   - AnalysisParameters: parameters of the musculoskeletal analysis,
%   automatically generated by the graphic interface 'Analysis'.%
%   OUTPUT
%   Results are automatically saved on the folder associated to each motion
%   capture in variable 'MuscleForcesComputationResults'.
%________________________________________________________
%
% Licence
% Toolbox distributed under GPL 3.0 Licence
%________________________________________________________
%
% Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
% Georges Dumont
%________________________________________________________
load('BiomechanicalModel.mat'); %#ok<LOAD>
for i = 1:numel(AnalysisParameters.filename)
    filename = AnalysisParameters.filename{i}(1:end-(numel(AnalysisParameters.General.Extension)-1));
    if AnalysisParameters.Muscles.Method == 1
        [MuscleForcesComputationResults] = ForcesComputationOptiNum(filename, BiomechanicalModel, AnalysisParameters); %#ok<NASGU>
    elseif AnalysisParameters.Muscles.Method == 2
        [MuscleForcesComputationResults] = ForcesComputationMusIC(filename, BiomechanicalModel, AnalysisParameters); %#ok<NASGU>
    end
    save([filename '/MuscleForcesComputationResults'],'MuscleForcesComputationResults');
end
end