function [R1cut,p1cut] = f1cut(in1,in2,in3,in4,in5,in6)
%F1CUT
%    [R1CUT,P1CUT] = F1CUT(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-Nov-2021 17:56:04

RPelvis1_1 = in2(1);
RPelvis1_2 = in2(4);
RPelvis1_3 = in2(7);
RPelvis2_1 = in2(2);
RPelvis2_2 = in2(5);
RPelvis2_3 = in2(8);
RPelvis3_1 = in2(3);
RPelvis3_2 = in2(6);
RPelvis3_3 = in2(9);
pPelvis1 = in1(1,:);
pPelvis2 = in1(2,:);
pPelvis3 = in1(3,:);
q64 = in3(57,:);
q65 = in3(58,:);
q66 = in3(59,:);
q67 = in3(60,:);
q68 = in3(61,:);
t2 = cos(q67);
t3 = cos(q68);
t4 = sin(q67);
t5 = sin(q68);
t6 = RPelvis1_3.*t2;
t7 = RPelvis2_3.*t2;
t8 = RPelvis3_3.*t2;
t9 = RPelvis1_2.*t4;
t10 = RPelvis2_2.*t4;
t11 = RPelvis3_2.*t4;
t12 = -t9;
t13 = -t10;
t14 = -t11;
t15 = t6+t12;
t16 = t7+t13;
t17 = t8+t14;
R1cut = reshape([RPelvis1_1.*t3-t5.*t15,RPelvis2_1.*t3-t5.*t16,RPelvis3_1.*t3-t5.*t17,RPelvis1_2.*t2+RPelvis1_3.*t4,RPelvis2_2.*t2+RPelvis2_3.*t4,RPelvis3_2.*t2+RPelvis3_3.*t4,RPelvis1_1.*t5+t3.*t15,RPelvis2_1.*t5+t3.*t16,RPelvis3_1.*t5+t3.*t17],[3,3]);
if nargout > 1
    p1cut = [pPelvis1+RPelvis1_1.*q64+RPelvis1_2.*q65+RPelvis1_3.*q66;pPelvis2+RPelvis2_1.*q64+RPelvis2_2.*q65+RPelvis2_3.*q66;pPelvis3+RPelvis3_1.*q64+RPelvis3_2.*q65+RPelvis3_3.*q66];
end
