function out1 = LBWT_Position(in1,in2,in3,in4,in5,in6)
%LBWT_POSITION
%    OUT1 = LBWT_POSITION(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-Nov-2021 17:55:35

R1cut1_1 = in6(1);
R1cut1_2 = in6(4);
R1cut1_3 = in6(7);
R1cut2_1 = in6(2);
R1cut2_2 = in6(5);
R1cut2_3 = in6(8);
R1cut3_1 = in6(3);
R1cut3_2 = in6(6);
R1cut3_3 = in6(9);
k_sym1 = in4(1,:);
p1cut1 = in5(1);
p1cut2 = in5(2);
p1cut3 = in5(3);
p_adapt_sym16 = in4(38,:);
p_adapt_sym17 = in4(39,:);
q1 = in3(1,:);
t2 = cos(q1);
t3 = sin(q1);
t4 = k_sym1./5.0;
t5 = p_adapt_sym16./2.0e+1;
t6 = p_adapt_sym17./2.0e+1;
t8 = k_sym1.*3.888888888888889e-3;
t7 = t4+1.0;
t9 = t5-7.0./8.0e+1;
t10 = t6-7.0./1.8e+2;
t11 = t8+7.0./3.6e+2;
out1 = [p1cut1-t11.*(R1cut1_1.*t3-R1cut1_2.*t2)+R1cut1_3.*t7.*t10+t7.*t9.*(R1cut1_1.*t2+R1cut1_2.*t3);p1cut2-t11.*(R1cut2_1.*t3-R1cut2_2.*t2)+R1cut2_3.*t7.*t10+t7.*t9.*(R1cut2_1.*t2+R1cut2_2.*t3);p1cut3-t11.*(R1cut3_1.*t3-R1cut3_2.*t2)+R1cut3_3.*t7.*t10+t7.*t9.*(R1cut3_1.*t2+R1cut3_2.*t3)];
