function out1 = LHEE_Position(in1,in2,in3,in4,in5,in6)
%LHEE_POSITION
%    OUT1 = LHEE_POSITION(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-Nov-2021 17:55:48

R2cut1_1 = in6(10);
R2cut1_2 = in6(13);
R2cut1_3 = in6(16);
R2cut2_1 = in6(11);
R2cut2_2 = in6(14);
R2cut2_3 = in6(17);
R2cut3_1 = in6(12);
R2cut3_2 = in6(15);
R2cut3_3 = in6(18);
k_sym14 = in4(14,:);
p2cut1 = in5(4);
p2cut2 = in5(5);
p2cut3 = in5(6);
p_adapt_sym35 = in4(57,:);
q48 = in3(42,:);
t2 = cos(q48);
t3 = sin(q48);
t4 = k_sym14./5.0;
t5 = p_adapt_sym35./2.0e+1;
t7 = k_sym14.*7.19036111111111e-3;
t6 = t4+1.0;
t8 = t5+5.805138888888889e-2;
t9 = t7+3.595180555555555e-2;
mt1 = [p2cut1-t9.*(R2cut1_1./9.007199254740992e+15+R2cut1_2.*t2+R2cut1_3.*t3)+t6.*t8.*(-R2cut1_1+(R2cut1_2.*t2)./9.007199254740992e+15+(R2cut1_3.*t3)./9.007199254740992e+15),p2cut2-t9.*(R2cut2_1./9.007199254740992e+15+R2cut2_2.*t2+R2cut2_3.*t3)+t6.*t8.*(-R2cut2_1+(R2cut2_2.*t2)./9.007199254740992e+15+(R2cut2_3.*t3)./9.007199254740992e+15)];
mt2 = [p2cut3-t9.*(R2cut3_1./9.007199254740992e+15+R2cut3_2.*t2+R2cut3_3.*t3)+t6.*t8.*(-R2cut3_1+(R2cut3_2.*t2)./9.007199254740992e+15+(R2cut3_3.*t3)./9.007199254740992e+15)];
out1 = reshape([mt1,mt2],3,1);
