function out1 = LSHO_Position(in1,in2,in3,in4,in5,in6)
%LSHO_POSITION
%    OUT1 = LSHO_POSITION(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-Nov-2021 17:55:33

R5cut1_1 = in6(37);
R5cut1_2 = in6(40);
R5cut1_3 = in6(43);
R5cut2_1 = in6(38);
R5cut2_2 = in6(41);
R5cut2_3 = in6(44);
R5cut3_1 = in6(39);
R5cut3_2 = in6(42);
R5cut3_3 = in6(45);
k_sym7 = in4(7,:);
p5cut1 = in5(13);
p5cut2 = in5(14);
p5cut3 = in5(15);
p_adapt_sym8 = in4(30,:);
p_adapt_sym9 = in4(31,:);
q32 = in3(26,:);
q33 = in3(27,:);
t2 = cos(q32);
t3 = cos(q33);
t4 = sin(q32);
t5 = sin(q33);
t12 = k_sym7./5.0;
t13 = p_adapt_sym8./2.0e+1;
t14 = p_adapt_sym9./2.0e+1;
t19 = k_sym7.*1.015626111111111e-2;
t6 = R5cut1_1.*t2;
t7 = R5cut2_1.*t2;
t8 = R5cut3_1.*t2;
t9 = R5cut1_2.*t4;
t10 = R5cut2_2.*t4;
t11 = R5cut3_2.*t4;
t15 = t12+1.0;
t20 = t13+4.427879166666666e-2;
t21 = t14-5.555689102696078e-2;
t22 = t19+5.078130555555555e-2;
t16 = t6+t9;
t17 = t7+t10;
t18 = t8+t11;
out1 = [p5cut1+t22.*(R5cut1_2.*t2-R5cut1_1.*t4)-t15.*t20.*(R5cut1_3.*t5-t3.*t16)+t15.*t21.*(R5cut1_3.*t3+t5.*t16);p5cut2+t22.*(R5cut2_2.*t2-R5cut2_1.*t4)-t15.*t20.*(R5cut2_3.*t5-t3.*t17)+t15.*t21.*(R5cut2_3.*t3+t5.*t17);p5cut3+t22.*(R5cut3_2.*t2-R5cut3_1.*t4)-t15.*t20.*(R5cut3_3.*t5-t3.*t18)+t15.*t21.*(R5cut3_3.*t3+t5.*t18)];
