function out1 = LTOE_Position(in1,in2,in3)
%LTOE_POSITION
%    OUT1 = LTOE_POSITION(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    25-Nov-2020 09:54:59

R2cut1_1 = in3(10);
R2cut1_2 = in3(13);
R2cut1_3 = in3(16);
R2cut2_1 = in3(11);
R2cut2_2 = in3(14);
R2cut2_3 = in3(17);
R2cut3_1 = in3(12);
R2cut3_2 = in3(15);
R2cut3_3 = in3(18);
p2cut1 = in2(4);
p2cut2 = in2(5);
p2cut3 = in2(6);
q34 = in1(34,:);
t2 = cos(q34);
t3 = sin(q34);
out1 = [R2cut1_1.*1.756666666666667e-1+p2cut1-R2cut1_2.*t2.*4.486111111111113e-2+R2cut1_2.*t3.*4.722222222222222e-3-R2cut1_3.*t2.*4.722222222222222e-3-R2cut1_3.*t3.*4.486111111111113e-2;R2cut2_1.*1.756666666666667e-1+p2cut2-R2cut2_2.*t2.*4.486111111111113e-2+R2cut2_2.*t3.*4.722222222222222e-3-R2cut2_3.*t2.*4.722222222222222e-3-R2cut2_3.*t3.*4.486111111111113e-2;R2cut3_1.*1.756666666666667e-1+p2cut3-R2cut3_2.*t2.*4.486111111111113e-2+R2cut3_2.*t3.*4.722222222222222e-3-R2cut3_3.*t2.*4.722222222222222e-3-R2cut3_3.*t3.*4.486111111111113e-2];
