function out1 = LWRA_Position(in1,in2,in3,in4,in5,in6)
%LWRA_POSITION
%    OUT1 = LWRA_POSITION(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-Nov-2021 17:55:55

R6cut1_1 = in6(46);
R6cut1_2 = in6(49);
R6cut1_3 = in6(52);
R6cut2_1 = in6(47);
R6cut2_2 = in6(50);
R6cut2_3 = in6(53);
R6cut3_1 = in6(48);
R6cut3_2 = in6(51);
R6cut3_3 = in6(54);
k_sym21 = in4(21,:);
p6cut1 = in5(16);
p6cut2 = in5(17);
p6cut3 = in5(18);
q60 = in3(54,:);
t2 = cos(q60);
t3 = sin(q60);
t4 = k_sym21.*(7.0./7.5e+2);
t6 = k_sym21.*5.253888888888889e-2;
t5 = t4+7.0./1.5e+2;
t7 = t6+2.626944444444444e-1;
out1 = [p6cut1-R6cut1_2.*t7-t5.*(R6cut1_1.*t3+R6cut1_3.*t2);p6cut2-R6cut2_2.*t7-t5.*(R6cut2_1.*t3+R6cut2_3.*t2);p6cut3-R6cut3_2.*t7-t5.*(R6cut3_1.*t3+R6cut3_3.*t2)];
