function out1 = LWRB_Position(in1,in2,in3,in4,in5,in6)
%LWRB_POSITION
%    OUT1 = LWRB_POSITION(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-Nov-2021 17:55:55

R6cut1_1 = in6(46);
R6cut1_2 = in6(49);
R6cut1_3 = in6(52);
R6cut2_1 = in6(47);
R6cut2_2 = in6(50);
R6cut2_3 = in6(53);
R6cut3_1 = in6(48);
R6cut3_2 = in6(51);
R6cut3_3 = in6(54);
k_sym21 = in4(21,:);
p6cut1 = in5(16);
p6cut2 = in5(17);
p6cut3 = in5(18);
p_adapt_sym45 = in4(67,:);
q60 = in3(54,:);
t2 = cos(q60);
t3 = sin(q60);
t4 = k_sym21./5.0;
t5 = p_adapt_sym45./2.0e+1;
t7 = k_sym21.*5.833333333333333e-3;
t6 = t4+1.0;
t8 = t7+7.0./2.4e+2;
t9 = t5-2.529722222222222e-1;
out1 = [p6cut1+t8.*(R6cut1_1.*t3+R6cut1_3.*t2)+R6cut1_2.*t6.*t9;p6cut2+t8.*(R6cut2_1.*t3+R6cut2_3.*t2)+R6cut2_2.*t6.*t9;p6cut3+t8.*(R6cut3_1.*t3+R6cut3_3.*t2)+R6cut3_2.*t6.*t9];
