function out1 = LWRB_Position(in1,in2,in3)
%LWRB_POSITION
%    OUT1 = LWRB_POSITION(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    25-Nov-2020 09:55:35

R5cut1_1 = in3(37);
R5cut1_2 = in3(40);
R5cut1_3 = in3(43);
R5cut2_1 = in3(38);
R5cut2_2 = in3(41);
R5cut2_3 = in3(44);
R5cut3_1 = in3(39);
R5cut3_2 = in3(42);
R5cut3_3 = in3(45);
p5cut1 = in2(13);
p5cut2 = in2(14);
p5cut3 = in2(15);
q50 = in1(50,:);
q54 = in1(54,:);
t2 = cos(q50);
t3 = cos(q54);
t4 = sin(q50);
t5 = sin(q54);
out1 = [R5cut1_2.*(-3.162e-1)+p5cut1+R5cut1_1.*t4.*1.803888888888889e-2-R5cut1_2.*t3.*2.510333333333333e-1+R5cut1_3.*t2.*1.803888888888889e-2+t5.*(R5cut1_1.*t2-R5cut1_3.*t4).*2.510333333333333e-1;R5cut2_2.*(-3.162e-1)+p5cut2+R5cut2_1.*t4.*1.803888888888889e-2-R5cut2_2.*t3.*2.510333333333333e-1+R5cut2_3.*t2.*1.803888888888889e-2+t5.*(R5cut2_1.*t2-R5cut2_3.*t4).*2.510333333333333e-1;R5cut3_2.*(-3.162e-1)+p5cut3+R5cut3_1.*t4.*1.803888888888889e-2-R5cut3_2.*t3.*2.510333333333333e-1+R5cut3_3.*t2.*1.803888888888889e-2+t5.*(R5cut3_1.*t2-R5cut3_3.*t4).*2.510333333333333e-1];
