function out1 = RTAR_Position(in1,in2,in3,in4,in5,in6)
%RTAR_POSITION
%    OUT1 = RTAR_POSITION(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-Nov-2021 17:55:43

R3cut1_1 = in6(19);
R3cut1_2 = in6(22);
R3cut1_3 = in6(25);
R3cut2_1 = in6(20);
R3cut2_2 = in6(23);
R3cut2_3 = in6(26);
R3cut3_1 = in6(21);
R3cut3_2 = in6(24);
R3cut3_3 = in6(27);
k_sym11 = in4(11,:);
p3cut1 = in5(7);
p3cut2 = in5(8);
p3cut3 = in5(9);
p_adapt_sym28 = in4(50,:);
p_adapt_sym29 = in4(51,:);
q42 = in3(36,:);
t2 = cos(q42);
t3 = sin(q42);
t4 = k_sym11./5.0;
t5 = p_adapt_sym28./2.0e+1;
t6 = p_adapt_sym29./2.0e+1;
t10 = k_sym11.*9.568222222222222e-3;
t7 = t4+1.0;
t8 = t6+7.0./1.2e+2;
t9 = t5-1.067013888888889e-1;
t11 = t10+4.784111111111111e-2;
mt1 = [p3cut1-t11.*(R3cut1_1./9.007199254740992e+15+R3cut1_2.*t2+R3cut1_3.*t3)+t7.*t9.*(-R3cut1_1+(R3cut1_2.*t2)./9.007199254740992e+15+(R3cut1_3.*t3)./9.007199254740992e+15)-t7.*t8.*(R3cut1_2.*t3-R3cut1_3.*t2),p3cut2-t11.*(R3cut2_1./9.007199254740992e+15+R3cut2_2.*t2+R3cut2_3.*t3)+t7.*t9.*(-R3cut2_1+(R3cut2_2.*t2)./9.007199254740992e+15+(R3cut2_3.*t3)./9.007199254740992e+15)-t7.*t8.*(R3cut2_2.*t3-R3cut2_3.*t2)];
mt2 = [p3cut3-t11.*(R3cut3_1./9.007199254740992e+15+R3cut3_2.*t2+R3cut3_3.*t3)+t7.*t9.*(-R3cut3_1+(R3cut3_2.*t2)./9.007199254740992e+15+(R3cut3_3.*t3)./9.007199254740992e+15)-t7.*t8.*(R3cut3_2.*t3-R3cut3_3.*t2)];
out1 = reshape([mt1,mt2],3,1);
