function out1 = RWRA_Position(in1,in2,in3,in4,in5,in6)
%RWRA_POSITION
%    OUT1 = RWRA_POSITION(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    17-Nov-2021 17:55:51

R9cut1_1 = in6(73);
R9cut1_2 = in6(76);
R9cut1_3 = in6(79);
R9cut2_1 = in6(74);
R9cut2_2 = in6(77);
R9cut2_3 = in6(80);
R9cut3_1 = in6(75);
R9cut3_2 = in6(78);
R9cut3_3 = in6(81);
k_sym17 = in4(17,:);
p9cut1 = in5(25);
p9cut2 = in5(26);
p9cut3 = in5(27);
q53 = in3(47,:);
t2 = cos(q53);
t3 = sin(q53);
t4 = k_sym17.*(7.0./7.5e+2);
t6 = k_sym17.*5.253888888888889e-2;
t5 = t4+7.0./1.5e+2;
t7 = t6+2.626944444444444e-1;
out1 = [p9cut1-R9cut1_2.*t7+t5.*(R9cut1_1.*t3+R9cut1_3.*t2);p9cut2-R9cut2_2.*t7+t5.*(R9cut2_1.*t3+R9cut2_3.*t2);p9cut3-R9cut3_2.*t7+t5.*(R9cut3_1.*t3+R9cut3_3.*t2)];
