Description of filt_data
Home > Functions > AlgoMathsModel > filt_data.m
filt_data
PURPOSE
4-th order Butterworth low pass filter with no phase shift
SYNOPSIS
function [data]=filt_data(data,f,f_mocap)
DESCRIPTION
 4-th order Butterworth low pass filter with no phase shift
   INPUT
   - data: data to filter
   - f: cut-off frequency
   - f_mocap: acquisition frequency
   OUTPUT
   - data: filtered data
________________________________________________________
 Licence
 Toolbox distributed under 3-Clause BSD License
________________________________________________________
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Get_real_markers Extraction of motion data
ExternalForcesPrediction Prediction of ground reaction forces
Cycling Computation of the external forces for a cycling application
DataInC3D Computation of the external forces
InverseKinematicsLM Computation of the inverse kinematics step thanks to a Jacobian matrix
InverseKinematicsOpti Computation of the inverse kinematics step thanks to a sqp optimization method
SUBFUNCTIONS
function [datafilt]=filtrage_data(data,f,f_mocap)
function [y]=filtre(data,f,f_mocap)
SOURCE CODE
function [data]=filt_data(data,f,f_mocap)
% 4-th order Butterworth low pass filter with no phase shift
%
%   INPUT
%   - data: data to filter
%   - f: cut-off frequency
%   - f_mocap: acquisition frequency
%   OUTPUT
%   - data: filtered data
%________________________________________________________
%
% Licence
% Toolbox distributed under 3-Clause BSD License
%________________________________________________________
for i=1:size(data,2)
    data(:,i)=filtrage_data(data(:,i),f,f_mocap);
end
end
function [datafilt]=filtrage_data(data,f,f_mocap)
%% filtre
% data : vector
init=data(1);
data_inter=data-init;
datafilt=filtre(data_inter,f,f_mocap);
datafilt=datafilt+init;
end
function [y]=filtre(data,f,f_mocap)
%% fonction filtre
Wn=f/(f_mocap/2); % f=100Hz (/2) et fréquence d'échantillonnage : 5Hz
% Wn=2/50; % f=100Hz (/2) et fréquence d'échantillonnage : 5Hz
[b,a] = butter(4,Wn,'low');
y=filtfilt(b,a,data);
end