function out1 = RHUM_Position(in1,in2,in3)
%RHUM_POSITION
%    OUT1 = RHUM_POSITION(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    25-Oct-2018 19:15:59

R3cut1_1 = in3(19);
R3cut1_2 = in3(22);
R3cut1_3 = in3(25);
R3cut2_1 = in3(20);
R3cut2_2 = in3(23);
R3cut2_3 = in3(26);
R3cut3_1 = in3(21);
R3cut3_2 = in3(24);
R3cut3_3 = in3(27);
p3cut1 = in2(7);
p3cut2 = in2(8);
p3cut3 = in2(9);
q19 = in1(19,:);
t2 = cos(q19);
t3 = sin(q19);
out1 = [R3cut1_2.*(-3.134949875058856e-1)+p3cut1-R3cut1_1.*t3.*4.681824783540706e-2-R3cut1_3.*t2.*4.681824783540706e-2;R3cut2_2.*(-3.134949875058856e-1)+p3cut2-R3cut2_1.*t3.*4.681824783540706e-2-R3cut2_3.*t2.*4.681824783540706e-2;R3cut3_2.*(-3.134949875058856e-1)+p3cut3-R3cut3_1.*t3.*4.681824783540706e-2-R3cut3_3.*t2.*4.681824783540706e-2];
