function [Muscles]=ArmMusclesPennestri(Muscles,Signe)
% Definition of an arm muscle model
%   This model contains 21 muscles
%
%	Based on:
%	- Pennestrì, E. , Stefanelli, R. , Valentini, P. P. , Vita, L.
%	Virtual musculo-skeletal model for the biomechanical
% analysis of the upper limb, Pennestrì2007

%   INPUT
%   - Muscles: set of muscles (see the Documentation for the structure)
%   - Signe: Signe of the arm model ('R' for right Signe or 'L' for left Signe)
%   OUTPUT
%   - Muscles: new set of muscles (see the Documentation for the structure)
%________________________________________________________
%
% Licence
% Toolbox distributed under GPL 3.0 Licence
%________________________________________________________
%
% Authors : Antoine Muller, Charles Pontonnier, Pierre Puchaud and
% Georges Dumont
%________________________________________________________


if strcmp(Signe,'Right')
    Signe = 'R';
else
    Signe = 'L';
end

s=cell(0);

s=[s;{
    [Signe 'Coracobrachialis'],242.5,0.200,[],[],[],{[Signe 'Humerus_Coracobrachialis_o'];[Signe 'Thorax_Coracobrachialis_i']},{};...
    [Signe 'Deltoid_pos'],259.9,0.170,[],[],[],{[Signe 'Humerus_Deltoid_o'];[Signe 'Thorax_Deltoid_i']},{};...
    [Signe 'LatissimusDorsi'],1059,0.135,[],[],[],{[Signe 'Humerus_LatissimusDorsi_o'];[Signe 'Thorax_LatissimusDorsi_i']},{};...
    [Signe 'PectoralisMajor'],1270,0.190,[],[],[],{[Signe 'Humerus_PectoralisMajor_o'];[Signe 'Thorax_PectoralisMajor_i']},{};...
    [Signe 'Supraspinatus'],487.8,0.090,[],[],[],{[Signe 'Humerus_Supraspinatus_o'];[Signe 'Thorax_Supraspinatus_i']},{};...
    [Signe 'Infraspinatus'],1210,0.105,[],[],[],{[Signe 'Humerus_Infraspinatus_o'];[Signe 'Thorax_Infraspinatus_i']},{};...
    [Signe 'Trapezius'],240,0.1,[],[],[],{[Signe 'Humerus_Trapezius_o'];[Signe 'Thorax_Trapezius_i']},{};...        [Signe 'BicepsBrachii2'],47,0.23,[],[],[],{[Signe 'Humerus_BicepsBrachii2_o'];[Signe 'Thorax_BicepsBrachii2_i']},{};...
    [Signe 'BicepsBrachii2'],435.6,0.23,[],[],[],{[Signe 'Humerus_BicepsBrachii2_o'];[Signe 'Thorax_BicepsBrachii2_i']},{};...  
    [Signe 'TricepsBrachii2'],1120,0.285,[],[],[],{[Signe 'Radius_TricepsBrachii2_o'];[Signe 'Humerus_TricepsBrachii_p1'];[Signe 'Thorax_TricepsBrachii2_i']},{['Wrap' Signe 'HumerusTri']};...
    [Signe 'BicepsBrachii1'],624.3,0.27,[],[],[],{[Signe 'Ulna_BicepsBrachii1_o'];[Signe 'Thorax_BicepsBrachii1_i']},{};...
    [Signe 'Anconeus'],350,0.075,[],[],[],{[Signe 'Humerus_Anconeus_o'];[Signe 'Ulna_Anconeus_i']},{};...
    [Signe 'TricepsBrachii1'],936.3,0.21,[],[],[],{[Signe 'Humerus_TricepsBrachii1_o'];[Signe 'Humerus_TricepsBrachii_p1'];[Signe 'Ulna_TricepsBrachii1_i']},{['Wrap' Signe 'HumerusTri']};...
    [Signe 'CubitalisAnterior'],35,0.255,[],[],[],{[Signe 'Humerus_CubitalisAnterior_o'];[Signe 'Hand_CubitalisAnterior_i']},{};...
    [Signe 'FlexorCarpiUlnaris'],74,0.255,[],[],[],{[Signe 'Humerus_FlexorCarpiUlnaris_o'];[Signe 'Hand_FlexorCarpiUlnaris_i']},{};...
    [Signe 'ExtensorCarpiUlnaris'],93.2,0.210,[],[],[],{[Signe 'Humerus_ExtensorCarpiUlnaris_o'];[Signe 'Hand_ExtensorCarpiUlnaris_i']},{};...
    [Signe 'ExtensorDigitorum'],46,0.225,[],[],[],{[Signe 'Humerus_ExtensorDigitorum_o'];[Signe 'Hand_ExtensorDigitorum_i']},{};...
    [Signe 'FlexorDigitorumSuperior'],45,0.220,[],[],[],{[Signe 'Humerus_FlexorDigitorumSuperior_o'];[Signe 'Hand_FlexorDigitorumSuperior_i']},{};...
    [Signe 'FlexorCarpiRadialis'],74,0.235,[],[],[],{[Signe 'Humerus_FlexorCarpiRadialis_o'];[Signe 'Hand_FlexorCapriRadialis_i']},{};...
    [Signe 'PronatorQuadrus'],78,0.045,[],[],[],{[Signe 'Ulna_PronatorQuadrus_o'];[Signe 'Radius_PronatorQuadrus_i']},{};...
    [Signe 'SupinatorBrevis'],30,0.050,[],[],[],{[Signe 'Ulna_SupinatorBrevis_o'];[Signe 'Radius_SupinatorBrevis_i']},{};...
    [Signe 'AbductorDigitiV'],36,0.140,[],[],[],{[Signe 'Ulna_AbductorDigitiV_o'];[Signe 'Hand_AbductorDigitiV_i']},{};...    
    [Signe 'Brachialis'],987.3,0.105,4,0.0535,0,{[Signe 'Humerus_Brachialis_o'];[Signe 'Radius_Brachialis_i']},{};...
    [Signe 'Brachioradialis'],261.3,0.22,[],[],[],{[Signe 'Humerus_Brachioradialis_o'];[Signe 'Radius_Brachioradialis_i']},{};...
    [Signe 'PronatorTeres'],566.2,0.07,[],[],[],{[Signe 'Humerus_PronatorTeres_o'];[Signe 'Radius_PronatorTeres_i']},{};...
    
    % Fake muscles from (Seth et al., 2016)
    [Signe '_Deltoid_ant'],1218.9,0.0976,[],0.093,0.38397,{[Signe '_humerus_r_DELT1_r-P1'];[Signe '_humerus_r_DELT1_r-P1'];[Signe '_Scapula_DELT1-P3'];[Signe '_clavicle_r_DELT1_r-P4']},{};...{['Wrap' Signe 'HumerusDelt']};... 
    [Signe '_Deltoid_mid'],1103.5,0.1078,[],0.1095,0.2618,{[Signe '_humerus_r_DELT2_r-P1'];[Signe '_Scapula_DELT2-P3'];[Signe '_Scapula_DELT2-P4']},{['Wrap' Signe 'ThoraxGH']};...   
    %     % Conservation du modèle de Holzbaur
% % on conserve les biceps du modèle de Holzbaur sauf qu'on part de la
%     % scapula pour le biceps short et glénoïde pour le biceps long
%     [Signe 'BicepsL'],624.3,0.1157,4,0.2723,0,{[Signe 'Scapula_BicepsL_o'];[Signe 'Scapula_BicepsL_via1'];[Signe 'Humerus_BicepsL_via2'];[Signe 'Humerus_BicepsL_via3'];[Signe 'Humerus_BicepsL_via4'];[Signe 'Humerus_BicepsL_via5'];[Signe 'Humerus_BicepsL_via6'];[Signe 'Humerus_Biceps_via7'];[Signe 'Ulna_Biceps_i']},{};... arm26.osim       
%     [Signe 'BicepsS'],435.56,0.1321,4,0.1923,0,{[Signe 'Scapula_BicepsS_o'];[Signe 'Scapula_BicepsS_via1'];[Signe 'Humerus_BicepsS_via2'];[Signe 'Humerus_BicepsS_via3'];[Signe 'Humerus_Biceps_via7'];[Signe 'Ulna_Biceps_i']},{};... arm26.osim    
%     % on conserve les biceps du modèle de Holzbaur sauf qu'on part de la
%     % scapula pour le triceps long
%        [Signe 'TricepsLg'],798.5,0.134,4,0.143,0.209,{[Signe 'Scapula_Triceps_o'];[Signe 'Humerus_TricepsLg_via1'];[Signe 'Humerus_Triceps_via2'];[Signe 'Humerus_Triceps_via3'];[Signe 'Humerus_Triceps_via4'];[Signe 'Ulna_Triceps_via5'];[Signe 'Ulna_Triceps_i']},{};...       arm26.osim    
%     [Signe 'TricepsLat'],624.3,0.114,4,0.098,0.157,{[Signe 'Humerus_TricepsLat_o'];[Signe 'Humerus_TricepsLat_via1'];[Signe 'Humerus_Triceps_via2'];[Signe 'Humerus_Triceps_via3'];[Signe 'Humerus_Triceps_via4'];[Signe 'Ulna_Triceps_via5'];[Signe 'Ulna_Triceps_i']},{};... arm26.osim   
%     [Signe 'TricepsMed'],624.3,0.114,4,0.098,0.157,{[Signe 'Humerus_TricepsMed_o'];[Signe 'Humerus_TricepsMed_via1'];[Signe 'Humerus_Triceps_via2'];[Signe 'Humerus_Triceps_via3'];[Signe 'Humerus_Triceps_via4'];[Signe 'Ulna_Triceps_via5'];[Signe 'Ulna_Triceps_i']},{};... arm26.osim
        }];


% Structure generation
Muscles=[Muscles;struct('name',{s{:,1}}','f0',{s{:,2}}','l0',{s{:,3}}',...
    'Kt',{s{:,4}}','ls',{s{:,5}}','alpha0',{s{:,6}}','path',{s{:,7}}','wrap',{s{:,8}}')]; %#ok<CCAT1>
end