function [R1cut,p1cut] = f1cut(in1,in2,in3)
%F1CUT
%    [R1CUT,P1CUT] = F1CUT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    25-Oct-2018 19:16:05

q25 = in1(25,:);
q26 = in1(26,:);
q27 = in1(27,:);
q28 = in1(28,:);
q29 = in1(29,:);
t2 = sin(q29);
t3 = cos(q29);
t4 = sin(q28);
t5 = cos(q28);
R1cut = reshape([t3,t2.*t4,-t2.*t5,0.0,t5,t4,t2,-t3.*t4,t3.*t5],[3,3]);
if nargout > 1
    p1cut = [q25;q26;q27];
end
