function [R8cut,p8cut] = f8cut(in1,in2,in3)
%F8CUT
%    [R8CUT,P8CUT] = F8CUT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-Feb-2021 14:51:48

R6cut1_1 = in3(46);
R6cut1_2 = in3(49);
R6cut1_3 = in3(52);
R6cut2_1 = in3(47);
R6cut2_2 = in3(50);
R6cut2_3 = in3(53);
R6cut3_1 = in3(48);
R6cut3_2 = in3(51);
R6cut3_3 = in3(54);
p6cut1 = in2(16);
p6cut2 = in2(17);
p6cut3 = in2(18);
q16 = in1(13,:);
q17 = in1(14,:);
q18 = in1(15,:);
q19 = in1(16,:);
q20 = in1(17,:);
q21 = in1(18,:);
t2 = cos(q16);
t3 = cos(q17);
t4 = cos(q21);
t5 = sin(q16);
t6 = sin(q17);
t7 = sin(q21);
t41 = q18+4.419444444444444e-2;
t8 = R6cut1_1.*t2;
t9 = R6cut1_2.*t2;
t10 = R6cut1_3.*t3;
t11 = R6cut2_1.*t2;
t12 = R6cut2_2.*t2;
t13 = R6cut2_3.*t3;
t14 = R6cut3_1.*t2;
t15 = R6cut3_2.*t2;
t16 = R6cut3_3.*t3;
t17 = R6cut1_1.*t5;
t18 = R6cut1_2.*t5;
t19 = R6cut1_3.*t6;
t20 = R6cut2_1.*t5;
t21 = R6cut2_2.*t5;
t22 = R6cut2_3.*t6;
t23 = R6cut3_1.*t5;
t24 = R6cut3_2.*t5;
t25 = R6cut3_3.*t6;
t26 = -t17;
t27 = -t20;
t28 = -t23;
t29 = t8+t18;
t30 = t11+t21;
t31 = t14+t24;
t32 = t9+t26;
t33 = t12+t27;
t34 = t15+t28;
t35 = t3.*t29;
t36 = t3.*t30;
t37 = t3.*t31;
t38 = t6.*t29;
t39 = t6.*t30;
t40 = t6.*t31;
t42 = -t35;
t43 = -t36;
t44 = -t37;
t45 = t10+t38;
t46 = t13+t39;
t47 = t16+t40;
t48 = t19+t42;
t49 = t22+t43;
t50 = t25+t44;
R8cut = reshape([-t4.*t48-t7.*t45,-t4.*t49-t7.*t46,-t4.*t50-t7.*t47,t32,t33,t34,t4.*t45-t7.*t48,t4.*t46-t7.*t49,t4.*t47-t7.*t50],[3,3]);
if nargout > 1
    p8cut = [p6cut1+t9.*3.741e-2+t10.*4.420587176470588e-2-t17.*3.741e-2+t38.*4.420587176470588e-2+q19.*t32+q20.*t45-t41.*t48;p6cut2+t12.*3.741e-2+t13.*4.420587176470588e-2-t20.*3.741e-2+t39.*4.420587176470588e-2+q19.*t33+q20.*t46-t41.*t49;p6cut3+t15.*3.741e-2+t16.*4.420587176470588e-2-t23.*3.741e-2+t40.*4.420587176470588e-2+q19.*t34+q20.*t47-t41.*t50];
end
