Description of export_fig
export_fig
PURPOSE
EXPORT_FIG Exports figures in a publication-quality format
SYNOPSIS
function [imageData, alpha] = export_fig(varargin) %#ok<*STRCL1>
DESCRIPTION
EXPORT_FIG  Exports figures in a publication-quality format
 Examples:
   imageData = export_fig
   [imageData, alpha] = export_fig
   export_fig filename
   export_fig filename -format1 -format2
   export_fig ... -nocrop
   export_fig ... -c[<val>,<val>,<val>,<val>]
   export_fig ... -transparent
   export_fig ... -native
   export_fig ... -m<val>
   export_fig ... -r<val>
   export_fig ... -a<val>
   export_fig ... -q<val>
   export_fig ... -p<val>
   export_fig ... -d<gs_option>
   export_fig ... -depsc
   export_fig ... -<renderer>
   export_fig ... -<colorspace>
   export_fig ... -append
   export_fig ... -bookmark
   export_fig ... -clipboard
   export_fig ... -update
   export_fig ... -nofontswap
   export_fig ... -font_space <char>
   export_fig ... -linecaps
   export_fig ... -noinvert
   export_fig(..., handle)
 This function saves a figure or single axes to one or more vector and/or
 bitmap file formats, and/or outputs a rasterized version to the workspace,
 with the following properties:
   - Figure/axes reproduced as it appears on screen
   - Cropped borders (optional)
   - Embedded fonts (vector formats)
   - Improved line and grid line styles
   - Anti-aliased graphics (bitmap formats)
   - Render images at native resolution (optional for bitmap formats)
   - Transparent background supported (pdf, eps, png, tiff)
   - Semi-transparent patch objects supported (png, tiff)
   - RGB, CMYK or grayscale output (CMYK only with pdf, eps, tiff)
   - Variable image compression, including lossless (pdf, eps, jpg)
   - Optional rounded line-caps (pdf, eps)
   - Optionally append to file (pdf, tiff)
   - Vector formats: pdf, eps
   - Bitmap formats: png, tiff, jpg, bmp, export to workspace
 This function is especially suited to exporting figures for use in
 publications and presentations, because of the high quality and
 portability of media produced.
 Note that the background color and figure dimensions are reproduced
 (the latter approximately, and ignoring cropping & magnification) in the
 output file. For transparent background (and semi-transparent patch
 objects), use the -transparent option or set the figure 'Color' property
 to 'none'. To make axes transparent set the axes 'Color' property to
 'none'. PDF, EPS, TIF & PNG are the only formats that support a transparent
 background; only TIF & PNG formats support transparency of patch objects.
 The choice of renderer (opengl, zbuffer or painters) has a large impact
 on the quality of output. The default value (opengl for bitmaps, painters
 for vector formats) generally gives good results, but if you aren't
 satisfied then try another renderer.  Notes: 1) For vector formats (EPS,
 PDF), only painters generates vector graphics. 2) For bitmaps, only
 opengl can render transparent patch objects correctly. 3) For bitmaps,
 only painters will correctly scale line dash and dot lengths when
 magnifying or anti-aliasing. 4) Fonts may be substitued with Courier when
 using painters.
 When exporting to vector format (PDF & EPS) and bitmap format using the
 painters renderer, this function requires that ghostscript is installed
 on your system. You can download this from:
   http://www.ghostscript.com
 When exporting to eps it additionally requires pdftops, from the Xpdf
 suite of functions. You can download this from:
   http://www.foolabs.com/xpdf
 Inputs:
   filename - string containing the name (optionally including full or
              relative path) of the file the figure is to be saved as. If
              a path is not specified, the figure is saved in the current
              directory. If no name and no output arguments are specified,
              the default name, 'export_fig_out', is used. If neither a
              file extension nor a format are specified, a ".png" is added
              and the figure saved in that format.
   -format1, -format2, etc. - strings containing the extensions of the
                              file formats the figure is to be saved as.
                              Valid options are: '-pdf', '-eps', '-png',
                              '-tif', '-jpg' and '-bmp'. All combinations
                              of formats are valid.
   -nocrop - option indicating that the borders of the output are not to
             be cropped.
   -c[<val>,<val>,<val>,<val>] - option indicating crop amounts. Must be
             a 4-element vector of numeric values: [top,right,bottom,left]
             where NaN/Inf indicate auto-cropping, 0 means no cropping,
             and any other value mean cropping in pixel amounts.
   -transparent - option indicating that the figure background is to be
                  made transparent (png, pdf, tif and eps output only).
   -m<val> - option where val indicates the factor to magnify the
             on-screen figure pixel dimensions by when generating bitmap
             outputs (does not affect vector formats). Default: '-m1'.
   -r<val> - option val indicates the resolution (in pixels per inch) to
             export bitmap and vector outputs at, keeping the dimensions
             of the on-screen figure. Default: '-r864' (for vector output
             only). Note that the -m option overides the -r option for
             bitmap outputs only.
   -native - option indicating that the output resolution (when outputting
             a bitmap format) should be such that the vertical resolution
             of the first suitable image found in the figure is at the
             native resolution of that image. To specify a particular
             image to use, give it the tag 'export_fig_native'. Notes:
             This overrides any value set with the -m and -r options. It
             also assumes that the image is displayed front-to-parallel
             with the screen. The output resolution is approximate and
             should not be relied upon. Anti-aliasing can have adverse
             effects on image quality (disable with the -a1 option).
   -a1, -a2, -a3, -a4 - option indicating the amount of anti-aliasing to
                        use for bitmap outputs. '-a1' means no anti-
                        aliasing; '-a4' is the maximum amount (default).
   -<renderer> - option to force a particular renderer (painters, opengl or
                 zbuffer). Default value: opengl for bitmap formats or
                 figures with patches and/or transparent annotations;
                 painters for vector formats without patches/transparencies.
   -<colorspace> - option indicating which colorspace color figures should
                   be saved in: RGB (default), CMYK or gray. CMYK is only
                   supported in pdf, eps and tiff output.
   -q<val> - option to vary bitmap image quality (in pdf, eps and jpg
             files only).  Larger val, in the range 0-100, gives higher
             quality/lower compression. val > 100 gives lossless
             compression. Default: '-q95' for jpg, ghostscript prepress
             default for pdf & eps. Note: lossless compression can
             sometimes give a smaller file size than the default lossy
             compression, depending on the type of images.
   -p<val> - option to pad a border of width val to exported files, where
             val is either a relative size with respect to cropped image
             size (i.e. p=0.01 adds a 1% border). For EPS & PDF formats,
             val can also be integer in units of 1/72" points (abs(val)>1).
             val can be positive (padding) or negative (extra cropping).
             If used, the -nocrop flag will be ignored, i.e. the image will
             always be cropped and then padded. Default: 0 (i.e. no padding).
   -append - option indicating that if the file (pdfs only) already
             exists, the figure is to be appended as a new page, instead
             of being overwritten (default).
   -bookmark - option to indicate that a bookmark with the name of the
               figure is to be created in the output file (pdf only).
   -clipboard - option to save output as an image on the system clipboard.
                Note: background transparency is not preserved in clipboard
   -d<gs_option> - option to indicate a ghostscript setting. For example,
                   -dMaxBitmap=0 or -dNoOutputFonts (Ghostscript 9.15+).
   -depsc -  option to use EPS level-3 rather than the default level-2 print
             device. This solves some bugs with Matlab's default -depsc2 device
             such as discolored subplot lines on images (vector formats only).
   -update - option to download and install the latest version of export_fig
   -nofontswap - option to avoid font swapping. Font swapping is automatically
             done in vector formats (only): 11 standard Matlab fonts are
             replaced by the original figure fonts. This option prevents this.
   -font_space <char> - option to set a spacer character for font-names that
             contain spaces, used by EPS/PDF. Default: ''
   -linecaps - option to create rounded line-caps (vector formats only).
   -noinvert - option to avoid setting figure's InvertHardcopy property to
             'off' during output (this solves some problems of empty outputs).
   handle -  The handle of the figure, axes or uipanels (can be an array of
             handles, but the objects must be in the same figure) to be
             saved. Default: gcf.
 Outputs:
   imageData - MxNxC uint8 image array of the exported image.
   alpha     - MxN single array of alphamatte values in the range [0,1],
               for the case when the background is transparent.
   Some helpful examples and tips can be found at:
      https://github.com/altmany/export_fig
   See also PRINT, SAVEAS, ScreenCapture (on the Matlab File Exchange)
CROSS-REFERENCE INFORMATION
This function calls:
copyfig COPYFIG Create a copy of a figure, without changing the figure
crop_borders CROP_BORDERS Crop the borders of an image or stack of images
eps2pdf EPS2PDF Convert an eps file to pdf format using ghostscript
isolate_axes ISOLATE_AXES Isolate the specified axes in a figure on their own
pdf2eps PDF2EPS Convert a pdf file to eps format using pdftops
print2array PRINT2ARRAY Exports a figure to an image array
print2eps PRINT2EPS Prints figures to eps with improved line styles
read_write_entire_textfile READ_WRITE_ENTIRE_TEXTFILE Read or write a whole text file to/from memory
using_hg2 USING_HG2 Determine if the HG2 graphics engine is used
This function is called by:
efw function efw(hf)
exportGifAnim8 %
SUBFUNCTIONS
function options = default_options()
function [fig, options] = parse_args(nout, fig, varargin)
function value = str2char(value)
function A = downsize(A, factor)
function A = rgb2grey(A)
function A = check_greyscale(A)
function eps_remove_background(fname, count)
function b = isvector(options)
function b = isbitmap(options)
function A = make_cell(A)
function add_bookmark(fname, bookmark_text)
function set_tick_mode(Hlims, ax)
function change_rgb_to_cmyk(fname)
SOURCE CODE
function [imageData, alpha] = export_fig(varargin) %#ok<*STRCL1>
%EXPORT_FIG  Exports figures in a publication-quality format
%
% Examples:
%   imageData = export_fig
%   [imageData, alpha] = export_fig
%   export_fig filename
%   export_fig filename -format1 -format2
%   export_fig ... -nocrop
%   export_fig ... -c[<val>,<val>,<val>,<val>]
%   export_fig ... -transparent
%   export_fig ... -native
%   export_fig ... -m<val>
%   export_fig ... -r<val>
%   export_fig ... -a<val>
%   export_fig ... -q<val>
%   export_fig ... -p<val>
%   export_fig ... -d<gs_option>
%   export_fig ... -depsc
%   export_fig ... -<renderer>
%   export_fig ... -<colorspace>
%   export_fig ... -append
%   export_fig ... -bookmark
%   export_fig ... -clipboard
%   export_fig ... -update
%   export_fig ... -nofontswap
%   export_fig ... -font_space <char>
%   export_fig ... -linecaps
%   export_fig ... -noinvert
%   export_fig(..., handle)
%
% This function saves a figure or single axes to one or more vector and/or
% bitmap file formats, and/or outputs a rasterized version to the workspace,
% with the following properties:
%   - Figure/axes reproduced as it appears on screen
%   - Cropped borders (optional)
%   - Embedded fonts (vector formats)
%   - Improved line and grid line styles
%   - Anti-aliased graphics (bitmap formats)
%   - Render images at native resolution (optional for bitmap formats)
%   - Transparent background supported (pdf, eps, png, tiff)
%   - Semi-transparent patch objects supported (png, tiff)
%   - RGB, CMYK or grayscale output (CMYK only with pdf, eps, tiff)
%   - Variable image compression, including lossless (pdf, eps, jpg)
%   - Optional rounded line-caps (pdf, eps)
%   - Optionally append to file (pdf, tiff)
%   - Vector formats: pdf, eps
%   - Bitmap formats: png, tiff, jpg, bmp, export to workspace
%
% This function is especially suited to exporting figures for use in
% publications and presentations, because of the high quality and
% portability of media produced.
%
% Note that the background color and figure dimensions are reproduced
% (the latter approximately, and ignoring cropping & magnification) in the
% output file. For transparent background (and semi-transparent patch
% objects), use the -transparent option or set the figure 'Color' property
% to 'none'. To make axes transparent set the axes 'Color' property to
% 'none'. PDF, EPS, TIF & PNG are the only formats that support a transparent
% background; only TIF & PNG formats support transparency of patch objects.
%
% The choice of renderer (opengl, zbuffer or painters) has a large impact
% on the quality of output. The default value (opengl for bitmaps, painters
% for vector formats) generally gives good results, but if you aren't
% satisfied then try another renderer.  Notes: 1) For vector formats (EPS,
% PDF), only painters generates vector graphics. 2) For bitmaps, only
% opengl can render transparent patch objects correctly. 3) For bitmaps,
% only painters will correctly scale line dash and dot lengths when
% magnifying or anti-aliasing. 4) Fonts may be substitued with Courier when
% using painters.
%
% When exporting to vector format (PDF & EPS) and bitmap format using the
% painters renderer, this function requires that ghostscript is installed
% on your system. You can download this from:
%   http://www.ghostscript.com
% When exporting to eps it additionally requires pdftops, from the Xpdf
% suite of functions. You can download this from:
%   http://www.foolabs.com/xpdf
%
% Inputs:
%   filename - string containing the name (optionally including full or
%              relative path) of the file the figure is to be saved as. If
%              a path is not specified, the figure is saved in the current
%              directory. If no name and no output arguments are specified,
%              the default name, 'export_fig_out', is used. If neither a
%              file extension nor a format are specified, a ".png" is added
%              and the figure saved in that format.
%   -format1, -format2, etc. - strings containing the extensions of the
%                              file formats the figure is to be saved as.
%                              Valid options are: '-pdf', '-eps', '-png',
%                              '-tif', '-jpg' and '-bmp'. All combinations
%                              of formats are valid.
%   -nocrop - option indicating that the borders of the output are not to
%             be cropped.
%   -c[<val>,<val>,<val>,<val>] - option indicating crop amounts. Must be
%             a 4-element vector of numeric values: [top,right,bottom,left]
%             where NaN/Inf indicate auto-cropping, 0 means no cropping,
%             and any other value mean cropping in pixel amounts.
%   -transparent - option indicating that the figure background is to be
%                  made transparent (png, pdf, tif and eps output only).
%   -m<val> - option where val indicates the factor to magnify the
%             on-screen figure pixel dimensions by when generating bitmap
%             outputs (does not affect vector formats). Default: '-m1'.
%   -r<val> - option val indicates the resolution (in pixels per inch) to
%             export bitmap and vector outputs at, keeping the dimensions
%             of the on-screen figure. Default: '-r864' (for vector output
%             only). Note that the -m option overides the -r option for
%             bitmap outputs only.
%   -native - option indicating that the output resolution (when outputting
%             a bitmap format) should be such that the vertical resolution
%             of the first suitable image found in the figure is at the
%             native resolution of that image. To specify a particular
%             image to use, give it the tag 'export_fig_native'. Notes:
%             This overrides any value set with the -m and -r options. It
%             also assumes that the image is displayed front-to-parallel
%             with the screen. The output resolution is approximate and
%             should not be relied upon. Anti-aliasing can have adverse
%             effects on image quality (disable with the -a1 option).
%   -a1, -a2, -a3, -a4 - option indicating the amount of anti-aliasing to
%                        use for bitmap outputs. '-a1' means no anti-
%                        aliasing; '-a4' is the maximum amount (default).
%   -<renderer> - option to force a particular renderer (painters, opengl or
%                 zbuffer). Default value: opengl for bitmap formats or
%                 figures with patches and/or transparent annotations;
%                 painters for vector formats without patches/transparencies.
%   -<colorspace> - option indicating which colorspace color figures should
%                   be saved in: RGB (default), CMYK or gray. CMYK is only
%                   supported in pdf, eps and tiff output.
%   -q<val> - option to vary bitmap image quality (in pdf, eps and jpg
%             files only).  Larger val, in the range 0-100, gives higher
%             quality/lower compression. val > 100 gives lossless
%             compression. Default: '-q95' for jpg, ghostscript prepress
%             default for pdf & eps. Note: lossless compression can
%             sometimes give a smaller file size than the default lossy
%             compression, depending on the type of images.
%   -p<val> - option to pad a border of width val to exported files, where
%             val is either a relative size with respect to cropped image
%             size (i.e. p=0.01 adds a 1% border). For EPS & PDF formats,
%             val can also be integer in units of 1/72" points (abs(val)>1).
%             val can be positive (padding) or negative (extra cropping).
%             If used, the -nocrop flag will be ignored, i.e. the image will
%             always be cropped and then padded. Default: 0 (i.e. no padding).
%   -append - option indicating that if the file (pdfs only) already
%             exists, the figure is to be appended as a new page, instead
%             of being overwritten (default).
%   -bookmark - option to indicate that a bookmark with the name of the
%               figure is to be created in the output file (pdf only).
%   -clipboard - option to save output as an image on the system clipboard.
%                Note: background transparency is not preserved in clipboard
%   -d<gs_option> - option to indicate a ghostscript setting. For example,
%                   -dMaxBitmap=0 or -dNoOutputFonts (Ghostscript 9.15+).
%   -depsc -  option to use EPS level-3 rather than the default level-2 print
%             device. This solves some bugs with Matlab's default -depsc2 device
%             such as discolored subplot lines on images (vector formats only).
%   -update - option to download and install the latest version of export_fig
%   -nofontswap - option to avoid font swapping. Font swapping is automatically
%             done in vector formats (only): 11 standard Matlab fonts are
%             replaced by the original figure fonts. This option prevents this.
%   -font_space <char> - option to set a spacer character for font-names that
%             contain spaces, used by EPS/PDF. Default: ''
%   -linecaps - option to create rounded line-caps (vector formats only).
%   -noinvert - option to avoid setting figure's InvertHardcopy property to
%             'off' during output (this solves some problems of empty outputs).
%   handle -  The handle of the figure, axes or uipanels (can be an array of
%             handles, but the objects must be in the same figure) to be
%             saved. Default: gcf.
%
% Outputs:
%   imageData - MxNxC uint8 image array of the exported image.
%   alpha     - MxN single array of alphamatte values in the range [0,1],
%               for the case when the background is transparent.
%
%   Some helpful examples and tips can be found at:
%      https://github.com/altmany/export_fig
%
%   See also PRINT, SAVEAS, ScreenCapture (on the Matlab File Exchange)
%{
% Copyright (C) Oliver Woodford 2008-2014, Yair Altman 2015-
% The idea of using ghostscript is inspired by Peder Axensten's SAVEFIG
% (fex id: 10889) which is itself inspired by EPS2PDF (fex id: 5782).
% The idea for using pdftops came from the MATLAB newsgroup (id: 168171).
% The idea of editing the EPS file to change line styles comes from Jiro
% Doke's FIXPSLINESTYLE (fex id: 17928).
% The idea of changing dash length with line width came from comments on
% fex id: 5743, but the implementation is mine :)
% The idea of anti-aliasing bitmaps came from Anders Brun's MYAA (fex id:
% 20979).
% The idea of appending figures in pdfs came from Matt C in comments on the
% FEX (id: 23629)
% Thanks to Roland Martin for pointing out the colour MATLAB
% bug/feature with colorbar axes and transparent backgrounds.
% Thanks also to Andrew Matthews for describing a bug to do with the figure
% size changing in -nodisplay mode. I couldn't reproduce it, but included a
% fix anyway.
% Thanks to Tammy Threadgill for reporting a bug where an axes is not
% isolated from gui objects.
%}
%{
% 23/02/12: Ensure that axes limits don't change during printing
% 14/03/12: Fix bug in fixing the axes limits (thanks to Tobias Lamour for reporting it).
% 02/05/12: Incorporate patch of Petr Nechaev (many thanks), enabling bookmarking of figures in pdf files.
% 09/05/12: Incorporate patch of Arcelia Arrieta (many thanks), to keep tick marks fixed.
% 12/12/12: Add support for isolating uipanels. Thanks to michael for suggesting it.
% 25/09/13: Add support for changing resolution in vector formats. Thanks to Jan Jaap Meijer for suggesting it.
% 07/05/14: Add support for '~' at start of path. Thanks to Sally Warner for suggesting it.
% 24/02/15: Fix Matlab R2014b bug (issue #34): plot markers are not displayed when ZLimMode='manual'
% 25/02/15: Fix issue #4 (using HG2 on R2014a and earlier)
% 25/02/15: Fix issue #21 (bold TeX axes labels/titles in R2014b)
% 26/02/15: If temp dir is not writable, use the user-specified folder for temporary EPS/PDF files (Javier Paredes)
% 27/02/15: Modified repository URL from github.com/ojwoodford to /altmany
%           Indented main function
%           Added top-level try-catch block to display useful workarounds
% 28/02/15: Enable users to specify optional ghostscript options (issue #36)
% 06/03/15: Improved image padding & cropping thanks to Oscar Hartogensis
% 26/03/15: Fixed issue #49 (bug with transparent grayscale images); fixed out-of-memory issue
% 26/03/15: Fixed issue #42: non-normalized annotations on HG1
% 26/03/15: Fixed issue #46: Ghostscript crash if figure units <> pixels
% 27/03/15: Fixed issue #39: bad export of transparent annotations/patches
% 28/03/15: Fixed issue #50: error on some Matlab versions with the fix for issue #42
% 29/03/15: Fixed issue #33: bugs in Matlab's print() function with -cmyk
% 29/03/15: Improved processing of input args (accept space between param name & value, related to issue #51)
% 30/03/15: When exporting *.fig files, then saveas *.fig if figure is open, otherwise export the specified fig file
% 30/03/15: Fixed edge case bug introduced yesterday (commit #ae1755bd2e11dc4e99b95a7681f6e211b3fa9358)
% 09/04/15: Consolidated header comment sections; initialize output vars only if requested (nargout>0)
% 14/04/15: Workaround for issue #45: lines in image subplots are exported in invalid color
% 15/04/15: Fixed edge-case in parsing input parameters; fixed help section to show the -depsc option (issue #45)
% 21/04/15: Bug fix: Ghostscript croaks on % chars in output PDF file (reported by Sven on FEX page, 15-Jul-2014)
% 22/04/15: Bug fix: Pdftops croaks on relative paths (reported by Tintin Milou on FEX page, 19-Jan-2015)
% 04/05/15: Merged fix #63 (Kevin Mattheus Moerman): prevent tick-label changes during export
% 07/05/15: Partial fix for issue #65: PDF export used painters rather than opengl renderer (thanks Nguyenr)
% 08/05/15: Fixed issue #65: bad PDF append since commit #e9f3cdf 21/04/15 (thanks Robert Nguyen)
% 12/05/15: Fixed issue #67: exponent labels cropped in export, since fix #63 (04/05/15)
% 28/05/15: Fixed issue #69: set non-bold label font only if the string contains symbols (\beta etc.), followup to issue #21
% 29/05/15: Added informative error message in case user requested SVG output (issue #72)
% 09/06/15: Fixed issue #58: -transparent removed anti-aliasing when exporting to PNG
% 19/06/15: Added -update option to download and install the latest version of export_fig
% 07/07/15: Added -nofontswap option to avoid font-swapping in EPS/PDF
% 16/07/15: Fixed problem with anti-aliasing on old Matlab releases
% 11/09/15: Fixed issue #103: magnification must never become negative; also fixed reported error msg in parsing input params
% 26/09/15: Alert if trying to export transparent patches/areas to non-PNG outputs (issue #108)
% 04/10/15: Do not suggest workarounds for certain errors that have already been handled previously
% 01/11/15: Fixed issue #112: use same renderer in print2eps as export_fig (thanks to Jesús Pestana Puerta)
% 10/11/15: Custom GS installation webpage for MacOS. Thanks to Andy Hueni via FEX
% 19/11/15: Fixed clipboard export in R2015b (thanks to Dan K via FEX)
% 21/02/16: Added -c option for indicating specific crop amounts (idea by Cedric Noordam on FEX)
% 08/05/16: Added message about possible error reason when groot.Units~=pixels (issue #149)
% 17/05/16: Fixed case of image YData containing more than 2 elements (issue #151)
% 08/08/16: Enabled exporting transparency to TIF, in addition to PNG/PDF (issue #168)
% 11/12/16: Added alert in case of error creating output PDF/EPS file (issue #179)
% 13/12/16: Minor fix to the commit for issue #179 from 2 days ago
% 22/03/17: Fixed issue #187: only set manual ticks when no exponent is present
% 09/04/17: Added -linecaps option (idea by Baron Finer, issue #192)
% 15/09/17: Fixed issue #205: incorrect tick-labels when Ticks number don't match the TickLabels number
% 15/09/17: Fixed issue #210: initialize alpha map to ones instead of zeros when -transparent is not used
% 18/09/17: Added -font_space option to replace font-name spaces in EPS/PDF (workaround for issue #194)
% 18/09/17: Added -noinvert option to solve some export problems with some graphic cards (workaround for issue #197)
% 08/11/17: Fixed issue #220: axes exponent is removed in HG1 when TickMode is 'manual' (internal Matlab bug)
% 08/11/17: Fixed issue #221: alert if the requested folder does not exist
% 19/11/17: Workaround for issue #207: alert when trying to use transparent bgcolor with -opengl
% 29/11/17: Workaround for issue #206: warn if exporting PDF/EPS for a figure that contains an image
% 11/12/17: Fixed issue #230: use OpenGL renderer when exported image contains transparency (also see issue #206)
% 30/01/18: Updated SVG message to point to https://github.com/kupiqu/plot2svg and display user-selected filename if available
% 27/02/18: Fixed issue #236: axes exponent cropped from output if on right-hand axes
% 29/05/18: Fixed issue #245: process "string" inputs just like 'char' inputs
%}
    if nargout
        [imageData, alpha] = deal([]);
    end
    hadError = false;
    displaySuggestedWorkarounds = true;
    % Ensure the figure is rendered correctly _now_ so that properties like axes limits are up-to-date
    drawnow;
    pause(0.05);  % this solves timing issues with Java Swing's EDT (http://undocumentedmatlab.com/blog/solving-a-matlab-hang-problem)
    % Parse the input arguments
    fig = get(0, 'CurrentFigure');
    [fig, options] = parse_args(nargout, fig, varargin{:});
    % Ensure that we have a figure handle
    if isequal(fig,-1)
        return;  % silent bail-out
    elseif isempty(fig)
        error('No figure found');
    end
    % Isolate the subplot, if it is one
    cls = all(ismember(get(fig, 'Type'), {'axes', 'uipanel'}));
    if cls
        % Given handles of one or more axes, so isolate them from the rest
        fig = isolate_axes(fig);
    else
        % Check we have a figure
        if ~isequal(get(fig, 'Type'), 'figure')
            error('Handle must be that of a figure, axes or uipanel');
        end
        % Get the old InvertHardcopy mode
        old_mode = get(fig, 'InvertHardcopy');
    end
    % Hack the font units where necessary (due to a font rendering bug in print?).
    % This may not work perfectly in all cases.
    % Also it can change the figure layout if reverted, so use a copy.
    magnify = options.magnify * options.aa_factor;
    if isbitmap(options) && magnify ~= 1
        fontu = findall(fig, 'FontUnits', 'normalized');
        if ~isempty(fontu)
            % Some normalized font units found
            if ~cls
                fig = copyfig(fig);
                set(fig, 'Visible', 'off');
                fontu = findall(fig, 'FontUnits', 'normalized');
                cls = true;
            end
            set(fontu, 'FontUnits', 'points');
        end
    end
    try
        % MATLAB "feature": axes limits and tick marks can change when printing
        Hlims = findall(fig, 'Type', 'axes');
        if ~cls
            % Record the old axes limit and tick modes
            Xlims = make_cell(get(Hlims, 'XLimMode'));
            Ylims = make_cell(get(Hlims, 'YLimMode'));
            Zlims = make_cell(get(Hlims, 'ZLimMode'));
            Xtick = make_cell(get(Hlims, 'XTickMode'));
            Ytick = make_cell(get(Hlims, 'YTickMode'));
            Ztick = make_cell(get(Hlims, 'ZTickMode'));
            Xlabel = make_cell(get(Hlims, 'XTickLabelMode'));
            Ylabel = make_cell(get(Hlims, 'YTickLabelMode'));
            Zlabel = make_cell(get(Hlims, 'ZTickLabelMode'));
        end
        % Set all axes limit and tick modes to manual, so the limits and ticks can't change
        % Fix Matlab R2014b bug (issue #34): plot markers are not displayed when ZLimMode='manual'
        set(Hlims, 'XLimMode', 'manual', 'YLimMode', 'manual');
        set_tick_mode(Hlims, 'X');
        set_tick_mode(Hlims, 'Y');
        if ~using_hg2(fig)
            set(Hlims,'ZLimMode', 'manual');
            set_tick_mode(Hlims, 'Z');
        end
    catch
        % ignore - fix issue #4 (using HG2 on R2014a and earlier)
    end
    % Fix issue #21 (bold TeX axes labels/titles in R2014b when exporting to EPS/PDF)
    try
        if using_hg2(fig) && isvector(options)
            % Set the FontWeight of axes labels/titles to 'normal'
            % Fix issue #69: set non-bold font only if the string contains symbols (\beta etc.)
            texLabels = findall(fig, 'type','text', 'FontWeight','bold');
            symbolIdx = ~cellfun('isempty',strfind({texLabels.String},'\'));
            set(texLabels(symbolIdx), 'FontWeight','normal');
        end
    catch
        % ignore
    end
    % Fix issue #42: non-normalized annotations on HG1 (internal Matlab bug)
    annotationHandles = [];
    try
        if ~using_hg2(fig)
            annotationHandles = findall(fig,'Type','hggroup','-and','-property','Units','-and','-not','Units','norm');
            try  % suggested by Jesús Pestana Puerta (jespestana) 30/9/2015
                originalUnits = get(annotationHandles,'Units');
                set(annotationHandles,'Units','norm');
            catch
            end
        end
    catch
        % should never happen, but ignore in any case - issue #50
    end
    % Fix issue #46: Ghostscript crash if figure units <> pixels
    oldFigUnits = get(fig,'Units');
    set(fig,'Units','pixels');
    % Set to print exactly what is there
    if options.invert_hardcopy
        set(fig, 'InvertHardcopy', 'off');
    end
    % Set the renderer
    switch options.renderer
        case 1
            renderer = '-opengl';
        case 2
            renderer = '-zbuffer';
        case 3
            renderer = '-painters';
        otherwise
            renderer = '-opengl'; % Default for bitmaps
    end
    hImages = findall(fig,'type','image');
    % Handle transparent patches
    hasTransparency = ~isempty(findall(fig,'-property','FaceAlpha','-and','-not','FaceAlpha',1));
    hasPatches      = ~isempty(findall(fig,'type','patch'));
    if hasTransparency
        % Alert if trying to export transparent patches/areas to non-supported outputs (issue #108)
        % http://www.mathworks.com/matlabcentral/answers/265265-can-export_fig-or-else-draw-vector-graphics-with-transparent-surfaces
        % TODO - use transparency when exporting to PDF by not passing via print2eps
        msg = 'export_fig currently supports transparent patches/areas only in PNG output. ';
        if options.pdf
            warning('export_fig:transparency', '%s\nTo export transparent patches/areas to PDF, use the print command:\n print(gcf, ''-dpdf'', ''%s.pdf'');', msg, options.name);
        elseif ~options.png && ~options.tif  % issue #168
            warning('export_fig:transparency', '%s\nTo export the transparency correctly, try using the ScreenCapture utility on the Matlab File Exchange: http://bit.ly/1QFrBip', msg);
        end
    elseif ~isempty(hImages)
        % Fix for issue #230: use OpenGL renderer when exported image contains transparency
        for idx = 1 : numel(hImages)
            cdata = get(hImages(idx),'CData');
            if any(isnan(cdata(:)))
                hasTransparency = true;
                break
            end
        end
    end
    try
        % Do the bitmap formats first
        if isbitmap(options)
            if abs(options.bb_padding) > 1
                displaySuggestedWorkarounds = false;
                error('For bitmap output (png,jpg,tif,bmp) the padding value (-p) must be between -1<p<1')
            end
            % Get the background colour
            if options.transparent && (options.png || options.alpha)
                % Get out an alpha channel
                % MATLAB "feature": black colorbar axes can change to white and vice versa!
                hCB = findall(fig, 'Type','axes', 'Tag','Colorbar');
                if isempty(hCB)
                    yCol = [];
                    xCol = [];
                else
                    yCol = get(hCB, 'YColor');
                    xCol = get(hCB, 'XColor');
                    if iscell(yCol)
                        yCol = cell2mat(yCol);
                        xCol = cell2mat(xCol);
                    end
                    yCol = sum(yCol, 2);
                    xCol = sum(xCol, 2);
                end
                % MATLAB "feature": apparently figure size can change when changing
                % colour in -nodisplay mode
                pos = get(fig, 'Position');
                % Set the background colour to black, and set size in case it was
                % changed internally
                tcol = get(fig, 'Color');
                set(fig, 'Color', 'k', 'Position', pos);
                % Correct the colorbar axes colours
                set(hCB(yCol==0), 'YColor', [0 0 0]);
                set(hCB(xCol==0), 'XColor', [0 0 0]);
                % The following code might cause out-of-memory errors
                try
                    % Print large version to array
                    B = print2array(fig, magnify, renderer);
                    % Downscale the image
                    B = downsize(single(B), options.aa_factor);
                catch
                    % This is more conservative in memory, but kills transparency (issue #58)
                    B = single(print2array(fig, magnify/options.aa_factor, renderer));
                end
                % Set background to white (and set size)
                set(fig, 'Color', 'w', 'Position', pos);
                % Correct the colorbar axes colours
                set(hCB(yCol==3), 'YColor', [1 1 1]);
                set(hCB(xCol==3), 'XColor', [1 1 1]);
                % The following code might cause out-of-memory errors
                try
                    % Print large version to array
                    A = print2array(fig, magnify, renderer);
                    % Downscale the image
                    A = downsize(single(A), options.aa_factor);
                catch
                    % This is more conservative in memory, but kills transparency (issue #58)
                    A = single(print2array(fig, magnify/options.aa_factor, renderer));
                end
                % Set the background colour (and size) back to normal
                set(fig, 'Color', tcol, 'Position', pos);
                % Compute the alpha map
                alpha = round(sum(B - A, 3)) / (255 * 3) + 1;
                A = alpha;
                A(A==0) = 1;
                A = B ./ A(:,:,[1 1 1]);
                clear B
                % Convert to greyscale
                if options.colourspace == 2
                    A = rgb2grey(A);
                end
                A = uint8(A);
                % Crop the background
                if options.crop
                    %[alpha, v] = crop_borders(alpha, 0, 1, options.crop_amounts);
                    %A = A(v(1):v(2),v(3):v(4),:);
                    [alpha, vA, vB] = crop_borders(alpha, 0, options.bb_padding, options.crop_amounts);
                    if ~any(isnan(vB)) % positive padding
                        B = repmat(uint8(zeros(1,1,size(A,3))),size(alpha));
                        B(vB(1):vB(2), vB(3):vB(4), :) = A(vA(1):vA(2), vA(3):vA(4), :); % ADDED BY OH
                        A = B;
                    else  % negative padding
                        A = A(vA(1):vA(2), vA(3):vA(4), :);
                    end
                end
                if options.png
                    % Compute the resolution
                    res = options.magnify * get(0, 'ScreenPixelsPerInch') / 25.4e-3;
                    % Save the png
                    imwrite(A, [options.name '.png'], 'Alpha', double(alpha), 'ResolutionUnit', 'meter', 'XResolution', res, 'YResolution', res);
                    % Clear the png bit
                    options.png = false;
                end
                % Return only one channel for greyscale
                if isbitmap(options)
                    A = check_greyscale(A);
                end
                if options.alpha
                    % Store the image
                    imageData = A;
                    % Clear the alpha bit
                    options.alpha = false;
                end
                % Get the non-alpha image
                if isbitmap(options)
                    alph = alpha(:,:,ones(1, size(A, 3)));
                    A = uint8(single(A) .* alph + 255 * (1 - alph));
                    clear alph
                end
                if options.im
                    % Store the new image
                    imageData = A;
                end
            else
                % Print large version to array
                if options.transparent
                    % MATLAB "feature": apparently figure size can change when changing
                    % colour in -nodisplay mode
                    pos = get(fig, 'Position');
                    tcol = get(fig, 'Color');
                    set(fig, 'Color', 'w', 'Position', pos);
                    A = print2array(fig, magnify, renderer);
                    set(fig, 'Color', tcol, 'Position', pos);
                    tcol = 255;
                else
                    [A, tcol] = print2array(fig, magnify, renderer);
                end
                % Crop the background
                if options.crop
                    A = crop_borders(A, tcol, options.bb_padding, options.crop_amounts);
                end
                % Downscale the image
                A = downsize(A, options.aa_factor);
                if options.colourspace == 2
                    % Convert to greyscale
                    A = rgb2grey(A);
                else
                    % Return only one channel for greyscale
                    A = check_greyscale(A);
                end
                % Outputs
                if options.im
                    imageData = A;
                end
                if options.alpha
                    imageData = A;
                    alpha = ones(size(A, 1), size(A, 2), 'single');
                end
            end
            % Save the images
            if options.png
                res = options.magnify * get(0, 'ScreenPixelsPerInch') / 25.4e-3;
                imwrite(A, [options.name '.png'], 'ResolutionUnit', 'meter', 'XResolution', res, 'YResolution', res);
            end
            if options.bmp
                imwrite(A, [options.name '.bmp']);
            end
            % Save jpeg with given quality
            if options.jpg
                quality = options.quality;
                if isempty(quality)
                    quality = 95;
                end
                if quality > 100
                    imwrite(A, [options.name '.jpg'], 'Mode', 'lossless');
                else
                    imwrite(A, [options.name '.jpg'], 'Quality', quality);
                end
            end
            % Save tif images in cmyk if wanted (and possible)
            if options.tif
                if options.colourspace == 1 && size(A, 3) == 3
                    A = double(255 - A);
                    K = min(A, [], 3);
                    K_ = 255 ./ max(255 - K, 1);
                    C = (A(:,:,1) - K) .* K_;
                    M = (A(:,:,2) - K) .* K_;
                    Y = (A(:,:,3) - K) .* K_;
                    A = uint8(cat(3, C, M, Y, K));
                    clear C M Y K K_
                end
                append_mode = {'overwrite', 'append'};
                imwrite(A, [options.name '.tif'], 'Resolution', options.magnify*get(0, 'ScreenPixelsPerInch'), 'WriteMode', append_mode{options.append+1});
            end
        end
        % Now do the vector formats
        if isvector(options)
            % Set the default renderer to painters
            if ~options.renderer
                if hasTransparency || hasPatches
                    % This is *MUCH* slower, but more accurate for patches and transparent annotations (issue #39)
                    renderer = '-opengl';
                else
                    renderer = '-painters';
                end
            end
            options.rendererStr = renderer;  % fix for issue #112
            % Generate some filenames
            tmp_nam = [tempname '.eps'];
            try
                % Ensure that the temp dir is writable (Javier Paredes 30/1/15)
                fid = fopen(tmp_nam,'w');
                fwrite(fid,1);
                fclose(fid);
                delete(tmp_nam);
                isTempDirOk = true;
            catch
                % Temp dir is not writable, so use the user-specified folder
                [dummy,fname,fext] = fileparts(tmp_nam); %#ok<ASGLU>
                fpath = fileparts(options.name);
                tmp_nam = fullfile(fpath,[fname fext]);
                isTempDirOk = false;
            end
            if isTempDirOk
                pdf_nam_tmp = [tempname '.pdf'];
            else
                pdf_nam_tmp = fullfile(fpath,[fname '.pdf']);
            end
            if options.pdf
                pdf_nam = [options.name '.pdf'];
                try copyfile(pdf_nam, pdf_nam_tmp, 'f'); catch, end  % fix for issue #65
            else
                pdf_nam = pdf_nam_tmp;
            end
            % Generate the options for print
            p2eArgs = {renderer, sprintf('-r%d', options.resolution)};
            if options.colourspace == 1  % CMYK
                % Issue #33: due to internal bugs in Matlab's print() function, we can't use its -cmyk option
                %p2eArgs{end+1} = '-cmyk';
            end
            if ~options.crop
                % Issue #56: due to internal bugs in Matlab's print() function, we can't use its internal cropping mechanism,
                % therefore we always use '-loose' (in print2eps.m) and do our own cropping (in crop_borders)
                %p2eArgs{end+1} = '-loose';
            end
            if any(strcmpi(varargin,'-depsc'))
                % Issue #45: lines in image subplots are exported in invalid color.
                % The workaround is to use the -depsc parameter instead of the default -depsc2
                p2eArgs{end+1} = '-depsc';
            end
            try
                % Remove background if requested (issue #207)
                if options.transparent %&& ~isequal(get(fig, 'Color'), 'none')
                    if options.renderer == 1  % OpenGL
                        warning('export_fig:openglTransparentBG', '-opengl sometimes fails to produce transparent backgrounds; try -painters instead');
                    else
                        originalBgColor = get(fig, 'Color');
                        set(fig,'Color','none');
                    end
                end
                % Generate an eps
                print2eps(tmp_nam, fig, options, p2eArgs{:});
                % {
                % Remove the background, if desired
                if options.transparent %&& ~isequal(get(fig, 'Color'), 'none')
                    eps_remove_background(tmp_nam, 1 + using_hg2(fig));
                end
                %}
                % Restore the figure's previous background color (if modified)
                try set(fig,'Color',originalBgColor); drawnow; catch, end
                % Fix colorspace to CMYK, if requested (workaround for issue #33)
                if options.colourspace == 1  % CMYK
                    % Issue #33: due to internal bugs in Matlab's print() function, we can't use its -cmyk option
                    change_rgb_to_cmyk(tmp_nam);
                end
                % Add a bookmark to the PDF if desired
                if options.bookmark
                    fig_nam = get(fig, 'Name');
                    if isempty(fig_nam)
                        warning('export_fig:EmptyBookmark', 'Bookmark requested for figure with no name. Bookmark will be empty.');
                    end
                    add_bookmark(tmp_nam, fig_nam);
                end
                % Generate a pdf
                eps2pdf(tmp_nam, pdf_nam_tmp, 1, options.append, options.colourspace==2, options.quality, options.gs_options);
                % Ghostscript croaks on % chars in the output PDF file, so use tempname and then rename the file
                try
                    % Rename the file (except if it is already the same)
                    % Abbie K's comment on the commit for issue #179 (#commitcomment-20173476)
                    if ~isequal(pdf_nam_tmp, pdf_nam)
                        movefile(pdf_nam_tmp, pdf_nam, 'f');
                    end
                catch
                    % Alert in case of error creating output PDF/EPS file (issue #179)
                    if exist(pdf_nam_tmp, 'file')
                        error(['Could not create ' pdf_nam ' - perhaps the folder does not exist, or you do not have write permissions']);
                    else
                        error('Could not generate the intermediary EPS file.');
                    end
                end
            catch ex
                % Delete the eps
                delete(tmp_nam);
                rethrow(ex);
            end
            % Delete the eps
            delete(tmp_nam);
            if options.eps || options.linecaps
                try
                    % Generate an eps from the pdf
                    % since pdftops can't handle relative paths (e.g., '..\'), use a temp file
                    eps_nam_tmp = strrep(pdf_nam_tmp,'.pdf','.eps');
                    pdf2eps(pdf_nam, eps_nam_tmp);
                    % Issue #192: enable rounded line-caps
                    if options.linecaps
                        fstrm = read_write_entire_textfile(eps_nam_tmp);
                        fstrm = regexprep(fstrm, '[02] J', '1 J');
                        read_write_entire_textfile(eps_nam_tmp, fstrm);
                        if options.pdf
                            eps2pdf(eps_nam_tmp, pdf_nam, 1, options.append, options.colourspace==2, options.quality, options.gs_options);
                        end
                    end
                    if options.eps
                        movefile(eps_nam_tmp, [options.name '.eps'], 'f');
                    else  % if options.pdf
                        try delete(eps_nam_tmp); catch, end
                    end
                catch ex
                    if ~options.pdf
                        % Delete the pdf
                        delete(pdf_nam);
                    end
                    try delete(eps_nam_tmp); catch, end
                    rethrow(ex);
                end
                if ~options.pdf
                    % Delete the pdf
                    delete(pdf_nam);
                end
            end
            % Issue #206: warn if the figure contains an image
            if ~isempty(hImages) && strcmpi(renderer,'-opengl')  % see addendum to issue #206
                warnMsg = ['exporting images to PDF/EPS may result in blurry images on some viewers. ' ...
                           'If so, try to change viewer, or increase the image''s CData resolution, or use -opengl renderer, or export via the print function. ' ...
                           'See <a href="matlab:web(''https://github.com/altmany/export_fig/issues/206'',''-browser'');">issue #206</a> for details.'];
                warning('export_fig:pdf_eps:blurry_image', warnMsg);
            end
        end
        % Revert the figure or close it (if requested)
        if cls || options.closeFig
            % Close the created figure
            close(fig);
        else
            % Reset the hardcopy mode
            set(fig, 'InvertHardcopy', old_mode);
            % Reset the axes limit and tick modes
            for a = 1:numel(Hlims)
                try
                    set(Hlims(a), 'XLimMode', Xlims{a}, 'YLimMode', Ylims{a}, 'ZLimMode', Zlims{a},...
                                  'XTickMode', Xtick{a}, 'YTickMode', Ytick{a}, 'ZTickMode', Ztick{a},...
                                  'XTickLabelMode', Xlabel{a}, 'YTickLabelMode', Ylabel{a}, 'ZTickLabelMode', Zlabel{a});
                catch
                    % ignore - fix issue #4 (using HG2 on R2014a and earlier)
                end
            end
            % Revert the tex-labels font weights
            try set(texLabels, 'FontWeight','bold'); catch, end
            % Revert annotation units
            for handleIdx = 1 : numel(annotationHandles)
                try
                    oldUnits = originalUnits{handleIdx};
                catch
                    oldUnits = originalUnits;
                end
                try set(annotationHandles(handleIdx),'Units',oldUnits); catch, end
            end
            % Revert figure units
            set(fig,'Units',oldFigUnits);
        end
        % Output to clipboard (if requested)
        if options.clipboard
            % Delete the output file if unchanged from the default name ('export_fig_out.png')
            if strcmpi(options.name,'export_fig_out')
                try
                    fileInfo = dir('export_fig_out.png');
                    if ~isempty(fileInfo)
                        timediff = now - fileInfo.datenum;
                        ONE_SEC = 1/24/60/60;
                        if timediff < ONE_SEC
                            delete('export_fig_out.png');
                        end
                    end
                catch
                    % never mind...
                end
            end
            % Save the image in the system clipboard
            % credit: Jiro Doke's IMCLIPBOARD: http://www.mathworks.com/matlabcentral/fileexchange/28708-imclipboard
            try
                error(javachk('awt', 'export_fig -clipboard output'));
            catch
                warning('export_fig:clipboardJava', 'export_fig -clipboard output failed: requires Java to work');
                return;
            end
            try
                % Import necessary Java classes
                import java.awt.Toolkit
                import java.awt.image.BufferedImage
                import java.awt.datatransfer.DataFlavor
                % Get System Clipboard object (java.awt.Toolkit)
                cb = Toolkit.getDefaultToolkit.getSystemClipboard();
                % Add java class (ImageSelection) to the path
                if ~exist('ImageSelection', 'class')
                    javaaddpath(fileparts(which(mfilename)), '-end');
                end
                % Get image size
                ht = size(imageData, 1);
                wd = size(imageData, 2);
                % Convert to Blue-Green-Red format
                try
                    imageData2 = imageData(:, :, [3 2 1]);
                catch
                    % Probably gray-scaled image (2D, without the 3rd [RGB] dimension)
                    imageData2 = imageData(:, :, [1 1 1]);
                end
                % Convert to 3xWxH format
                imageData2 = permute(imageData2, [3, 2, 1]);
                % Append Alpha data (unused - transparency is not supported in clipboard copy)
                alphaData2 = uint8(permute(255*alpha,[3,2,1])); %=255*ones(1,wd,ht,'uint8')
                imageData2 = cat(1, imageData2, alphaData2);
                % Create image buffer
                imBuffer = BufferedImage(wd, ht, BufferedImage.TYPE_INT_RGB);
                imBuffer.setRGB(0, 0, wd, ht, typecast(imageData2(:), 'int32'), 0, wd);
                % Create ImageSelection object from the image buffer
                imSelection = ImageSelection(imBuffer);
                % Set clipboard content to the image
                cb.setContents(imSelection, []);
            catch
                warning('export_fig:clipboardFailed', 'export_fig -clipboard output failed: %s', lasterr); %#ok<LERR>
            end
        end
        % Don't output the data to console unless requested
        if ~nargout
            clear imageData alpha
        end
    catch err
        % Display possible workarounds before the error message
        if displaySuggestedWorkarounds && ~strcmpi(err.message,'export_fig error')
            if ~hadError,  fprintf(2, 'export_fig error. ');  end
            fprintf(2, 'Please ensure:\n');
            fprintf(2, '  that you are using the <a href="https://github.com/altmany/export_fig/archive/master.zip">latest version</a> of export_fig\n');
            if ismac
                fprintf(2, '  and that you have <a href="http://pages.uoregon.edu/koch">Ghostscript</a> installed\n');
            else
                fprintf(2, '  and that you have <a href="http://www.ghostscript.com">Ghostscript</a> installed\n');
            end
            try
                if options.eps
                    fprintf(2, '  and that you have <a href="http://www.foolabs.com/xpdf">pdftops</a> installed\n');
                end
            catch
                % ignore - probably an error in parse_args
            end
            fprintf(2, '  and that you do not have <a href="matlab:which export_fig -all">multiple versions</a> of export_fig installed by mistake\n');
            fprintf(2, '  and that you did not made a mistake in the <a href="matlab:help export_fig">expected input arguments</a>\n');
            try
                % Alert per issue #149
                if ~strncmpi(get(0,'Units'),'pixel',5)
                    fprintf(2, '  or try to set groot''s Units property back to its default value of ''pixels'' (<a href="matlab:web(''https://github.com/altmany/export_fig/issues/149'',''-browser'');">details</a>)\n');
                end
            catch
                % ignore - maybe an old MAtlab release
            end
            fprintf(2, '\nIf the problem persists, then please <a href="https://github.com/altmany/export_fig/issues">report a new issue</a>.\n\n');
        end
        rethrow(err)
    end
end
function options = default_options()
    % Default options used by export_fig
    options = struct(...
        'name',         'export_fig_out', ...
        'crop',         true, ...
        'crop_amounts', nan(1,4), ...  % auto-crop all 4 image sides
        'transparent',  false, ...
        'renderer',     0, ...         % 0: default, 1: OpenGL, 2: ZBuffer, 3: Painters
        'pdf',          false, ...
        'eps',          false, ...
        'png',          false, ...
        'tif',          false, ...
        'jpg',          false, ...
        'bmp',          false, ...
        'clipboard',    false, ...
        'colourspace',  0, ...         % 0: RGB/gray, 1: CMYK, 2: gray
        'append',       false, ...
        'im',           false, ...
        'alpha',        false, ...
        'aa_factor',    0, ...
        'bb_padding',   0, ...
        'magnify',      [], ...
        'resolution',   [], ...
        'bookmark',     false, ...
        'closeFig',     false, ...
        'quality',      [], ...
        'update',       false, ...
        'fontswap',     true, ...
        'font_space',   '', ...
        'linecaps',     false, ...
        'invert_hardcopy', true, ...
        'gs_options',   {{}});
end
function [fig, options] = parse_args(nout, fig, varargin)
    % Parse the input arguments
    % Convert strings => chars
    varargin = cellfun(@str2char,varargin,'un',false);
    % Set the defaults
    native = false; % Set resolution to native of an image
    options = default_options();
    options.im =    (nout == 1);  % user requested imageData output
    options.alpha = (nout == 2);  % user requested alpha output
    % Go through the other arguments
    skipNext = false;
    for a = 1:nargin-2
        if skipNext
            skipNext = false;
            continue;
        end
        if all(ishandle(varargin{a}))
            fig = varargin{a};
        elseif ischar(varargin{a}) && ~isempty(varargin{a})
            if varargin{a}(1) == '-'
                switch lower(varargin{a}(2:end))
                    case 'nocrop'
                        options.crop = false;
                        options.crop_amounts = [0,0,0,0];
                    case {'trans', 'transparent'}
                        options.transparent = true;
                    case 'opengl'
                        options.renderer = 1;
                    case 'zbuffer'
                        options.renderer = 2;
                    case 'painters'
                        options.renderer = 3;
                    case 'pdf'
                        options.pdf = true;
                    case 'eps'
                        options.eps = true;
                    case 'png'
                        options.png = true;
                    case {'tif', 'tiff'}
                        options.tif = true;
                    case {'jpg', 'jpeg'}
                        options.jpg = true;
                    case 'bmp'
                        options.bmp = true;
                    case 'rgb'
                        options.colourspace = 0;
                    case 'cmyk'
1000                         options.colourspace = 1;
1001                     case {'gray', 'grey'}
1002                         options.colourspace = 2;
1003                     case {'a1', 'a2', 'a3', 'a4'}
1004                         options.aa_factor = str2double(varargin{a}(3));
1005                     case 'append'
1006                         options.append = true;
1007                     case 'bookmark'
1008                         options.bookmark = true;
1009                     case 'native'
1010                         native = true;
1011                     case 'clipboard'
1012                         options.clipboard = true;
1013                         options.im = true;
1014                         options.alpha = true;
1015                     case 'svg'
1016                         filename = strrep(options.name,'export_fig_out','filename');
1017                         msg = ['SVG output is not supported by export_fig. Use one of the following alternatives:\n' ...
1018                                '  1. saveas(gcf,''' filename '.svg'')\n' ...
1019                                '  2. plot2svg utility: https://github.com/kupiqu/plot2svg\n' ...  % Note: replaced defunct https://github.com/jschwizer99/plot2svg with up-to-date fork on https://github.com/kupiqu/plot2svg
1020                                '  3. export_fig to EPS/PDF, then convert to SVG using generic (non-Matlab) tools\n'];
1021                         error(sprintf(msg)); %#ok<SPERR>
1022                     case 'update'
1023                         % Download the latest version of export_fig into the export_fig folder
1024                         try
1025                             zipFileName = 'https://github.com/altmany/export_fig/archive/master.zip';
1026                             folderName = fileparts(which(mfilename('fullpath')));
1027                             targetFileName = fullfile(folderName, datestr(now,'yyyy-mm-dd.zip'));
1028                             urlwrite(zipFileName,targetFileName);
1029                         catch
1030                             error('Could not download %s into %s\n',zipFileName,targetFileName);
1031                         end
1032
1033                         % Unzip the downloaded zip file in the export_fig folder
1034                         try
1035                             unzip(targetFileName,folderName);
1036                         catch
1037                             error('Could not unzip %s\n',targetFileName);
1038                         end
1039                     case 'nofontswap'
1040                         options.fontswap = false;
1041                     case 'font_space'
1042                         options.font_space = varargin{a+1};
1043                         skipNext = true;
1044                     case 'linecaps'
1045                         options.linecaps = true;
1046                     case 'noinvert'
1047                         options.invert_hardcopy = false;
1048                     otherwise
1049                         try
1050                             wasError = false;
1051                             if strcmpi(varargin{a}(1:2),'-d')
1052                                 varargin{a}(2) = 'd';  % ensure lowercase 'd'
1053                                 options.gs_options{end+1} = varargin{a};
1054                             elseif strcmpi(varargin{a}(1:2),'-c')
1055                                 if numel(varargin{a})==2
1056                                     skipNext = true;
1057                                     vals = str2num(varargin{a+1}); %#ok<ST2NM>
1058                                 else
1059                                     vals = str2num(varargin{a}(3:end)); %#ok<ST2NM>
1060                                 end
1061                                 if numel(vals)~=4
1062                                     wasError = true;
1063                                     error('option -c cannot be parsed: must be a 4-element numeric vector');
1064                                 end
1065                                 options.crop_amounts = vals;
1066                                 options.crop = true;
1067                             else  % scalar parameter value
1068                                 val = str2double(regexp(varargin{a}, '(?<=-(m|M|r|R|q|Q|p|P))-?\d*.?\d+', 'match'));
1069                                 if isempty(val) || isnan(val)
1070                                     % Issue #51: improved processing of input args (accept space between param name & value)
1071                                     val = str2double(varargin{a+1});
1072                                     if isscalar(val) && ~isnan(val)
1073                                         skipNext = true;
1074                                     end
1075                                 end
1076                                 if ~isscalar(val) || isnan(val)
1077                                     wasError = true;
1078                                     error('option %s is not recognised or cannot be parsed', varargin{a});
1079                                 end
1080                                 switch lower(varargin{a}(2))
1081                                     case 'm'
1082                                         % Magnification may never be negative
1083                                         if val <= 0
1084                                             wasError = true;
1085                                             error('Bad magnification value: %g (must be positive)', val);
1086                                         end
1087                                         options.magnify = val;
1088                                     case 'r'
1089                                         options.resolution = val;
1090                                     case 'q'
1091                                         options.quality = max(val, 0);
1092                                     case 'p'
1093                                         options.bb_padding = val;
1094                                 end
1095                             end
1096                         catch err
1097                             % We might have reached here by raising an intentional error
1098                             if wasError  % intentional raise
1099                                 rethrow(err)
1100                             else  % unintentional
1101                                 error(['Unrecognized export_fig input option: ''' varargin{a} '''']);
1102                             end
1103                         end
1104                 end
1105             else
1106                 [p, options.name, ext] = fileparts(varargin{a});
1107                 if ~isempty(p)
1108                     % Issue #221: alert if the requested folder does not exist
1109                     if ~exist(p,'dir'),  error(['Folder ' p ' does not exist!']);  end
1110                     options.name = [p filesep options.name];
1111                 end
1112                 switch lower(ext)
1113                     case {'.tif', '.tiff'}
1114                         options.tif = true;
1115                     case {'.jpg', '.jpeg'}
1116                         options.jpg = true;
1117                     case '.png'
1118                         options.png = true;
1119                     case '.bmp'
1120                         options.bmp = true;
1121                     case '.eps'
1122                         options.eps = true;
1123                     case '.pdf'
1124                         options.pdf = true;
1125                     case '.fig'
1126                         % If no open figure, then load the specified .fig file and continue
1127                         if isempty(fig)
1128                             fig = openfig(varargin{a},'invisible');
1129                             varargin{a} = fig;
1130                             options.closeFig = true;
1131                         else
1132                             % save the current figure as the specified .fig file and exit
1133                             saveas(fig(1),varargin{a});
1134                             fig = -1;
1135                             return
1136                         end
1137                     case '.svg'
1138                         filename = strrep(options.name,'export_fig_out','filename');
1139                         msg = ['SVG output is not supported by export_fig. Use one of the following alternatives:\n' ...
1140                                '  1. saveas(gcf,''' filename '.svg'')\n' ...
1141                                '  2. plot2svg utility: https://github.com/kupiqu/plot2svg\n' ...  % Note: replaced defunct https://github.com/jschwizer99/plot2svg with up-to-date fork on https://github.com/kupiqu/plot2svg
1142                                '  3. export_fig to EPS/PDF, then convert to SVG using generic (non-Matlab) tools\n'];
1143                         error(sprintf(msg)); %#ok<SPERR>
1144                     otherwise
1145                         options.name = varargin{a};
1146                 end
1147             end
1148         end
1149     end
1150
1151     % Quick bail-out if no figure found
1152     if isempty(fig),  return;  end
1153
1154     % Do border padding with repsect to a cropped image
1155     if options.bb_padding
1156         options.crop = true;
1157     end
1158
1159     % Set default anti-aliasing now we know the renderer
1160     if options.aa_factor == 0
1161         try isAA = strcmp(get(ancestor(fig, 'figure'), 'GraphicsSmoothing'), 'on'); catch, isAA = false; end
1162         options.aa_factor = 1 + 2 * (~(using_hg2(fig) && isAA) | (options.renderer == 3));
1163     end
1164
1165     % Convert user dir '~' to full path
1166     if numel(options.name) > 2 && options.name(1) == '~' && (options.name(2) == '/' || options.name(2) == '\')
1167         options.name = fullfile(char(java.lang.System.getProperty('user.home')), options.name(2:end));
1168     end
1169
1170     % Compute the magnification and resolution
1171     if isempty(options.magnify)
1172         if isempty(options.resolution)
1173             options.magnify = 1;
1174             options.resolution = 864;
1175         else
1176             options.magnify = options.resolution ./ get(0, 'ScreenPixelsPerInch');
1177         end
1178     elseif isempty(options.resolution)
1179         options.resolution = 864;
1180     end
1181
1182     % Set the default format
1183     if ~isvector(options) && ~isbitmap(options)
1184         options.png = true;
1185     end
1186
1187     % Check whether transparent background is wanted (old way)
1188     if isequal(get(ancestor(fig(1), 'figure'), 'Color'), 'none')
1189         options.transparent = true;
1190     end
1191
1192     % If requested, set the resolution to the native vertical resolution of the
1193     % first suitable image found
1194     if native && isbitmap(options)
1195         % Find a suitable image
1196         list = findall(fig, 'Type','image', 'Tag','export_fig_native');
1197         if isempty(list)
1198             list = findall(fig, 'Type','image', 'Visible','on');
1199         end
1200         for hIm = list(:)'
1201             % Check height is >= 2
1202             height = size(get(hIm, 'CData'), 1);
1203             if height < 2
1204                 continue
1205             end
1206             % Account for the image filling only part of the axes, or vice versa
1207             yl = get(hIm, 'YData');
1208             if isscalar(yl)
1209                 yl = [yl(1)-0.5 yl(1)+height+0.5];
1210             else
1211                 yl = [min(yl), max(yl)];  % fix issue #151 (case of yl containing more than 2 elements)
1212                 if ~diff(yl)
1213                     continue
1214                 end
1215                 yl = yl + [-0.5 0.5] * (diff(yl) / (height - 1));
1216             end
1217             hAx = get(hIm, 'Parent');
1218             yl2 = get(hAx, 'YLim');
1219             % Find the pixel height of the axes
1220             oldUnits = get(hAx, 'Units');
1221             set(hAx, 'Units', 'pixels');
1222             pos = get(hAx, 'Position');
1223             set(hAx, 'Units', oldUnits);
1224             if ~pos(4)
1225                 continue
1226             end
1227             % Found a suitable image
1228             % Account for stretch-to-fill being disabled
1229             pbar = get(hAx, 'PlotBoxAspectRatio');
1230             pos = min(pos(4), pbar(2)*pos(3)/pbar(1));
1231             % Set the magnification to give native resolution
1232             options.magnify = abs((height * diff(yl2)) / (pos * diff(yl)));  % magnification must never be negative: issue #103
1233             break
1234         end
1235     end
1236 end
1237
1238 % Convert a possible string => char (issue #245)
1239 function value = str2char(value)
1240     if isa(value,'string')
1241         value = char(value);
1242     end
1243 end
1244
1245 function A = downsize(A, factor)
1246     % Downsample an image
1247     if factor == 1
1248         % Nothing to do
1249         return
1250     end
1251     try
1252         % Faster, but requires image processing toolbox
1253         A = imresize(A, 1/factor, 'bilinear');
1254     catch
1255         % No image processing toolbox - resize manually
1256         % Lowpass filter - use Gaussian as is separable, so faster
1257         % Compute the 1d Gaussian filter
1258         filt = (-factor-1:factor+1) / (factor * 0.6);
1259         filt = exp(-filt .* filt);
1260         % Normalize the filter
1261         filt = single(filt / sum(filt));
1262         % Filter the image
1263         padding = floor(numel(filt) / 2);
1264         for a = 1:size(A, 3)
1265             A(:,:,a) = conv2(filt, filt', single(A([ones(1, padding) 1:end repmat(end, 1, padding)],[ones(1, padding) 1:end repmat(end, 1, padding)],a)), 'valid');
1266         end
1267         % Subsample
1268         A = A(1+floor(mod(end-1, factor)/2):factor:end,1+floor(mod(end-1, factor)/2):factor:end,:);
1269     end
1270 end
1271
1272 function A = rgb2grey(A)
1273     A = cast(reshape(reshape(single(A), [], 3) * single([0.299; 0.587; 0.114]), size(A, 1), size(A, 2)), class(A)); % #ok<ZEROLIKE>
1274 end
1275
1276 function A = check_greyscale(A)
1277     % Check if the image is greyscale
1278     if size(A, 3) == 3 && ...
1279             all(reshape(A(:,:,1) == A(:,:,2), [], 1)) && ...
1280             all(reshape(A(:,:,2) == A(:,:,3), [], 1))
1281         A = A(:,:,1); % Save only one channel for 8-bit output
1282     end
1283 end
1284
1285 function eps_remove_background(fname, count)
1286     % Remove the background of an eps file
1287     % Open the file
1288     fh = fopen(fname, 'r+');
1289     if fh == -1
1290         error('Not able to open file %s.', fname);
1291     end
1292     % Read the file line by line
1293     while count
1294         % Get the next line
1295         l = fgets(fh);
1296         if isequal(l, -1)
1297             break; % Quit, no rectangle found
1298         end
1299         % Check if the line contains the background rectangle
1300         if isequal(regexp(l, ' *0 +0 +\d+ +\d+ +r[fe] *[\n\r]+', 'start'), 1)
1301             % Set the line to whitespace and quit
1302             l(1:regexp(l, '[\n\r]', 'start', 'once')-1) = ' ';
1303             fseek(fh, -numel(l), 0);
1304             fprintf(fh, l);
1305             % Reduce the count
1306             count = count - 1;
1307         end
1308     end
1309     % Close the file
1310     fclose(fh);
1311 end
1312
1313 function b = isvector(options)
1314     b = options.pdf || options.eps;
1315 end
1316
1317 function b = isbitmap(options)
1318     b = options.png || options.tif || options.jpg || options.bmp || options.im || options.alpha;
1319 end
1320
1321 % Helper function
1322 function A = make_cell(A)
1323     if ~iscell(A)
1324         A = {A};
1325     end
1326 end
1327
1328 function add_bookmark(fname, bookmark_text)
1329     % Adds a bookmark to the temporary EPS file after %%EndPageSetup
1330     % Read in the file
1331     fh = fopen(fname, 'r');
1332     if fh == -1
1333         error('File %s not found.', fname);
1334     end
1335     try
1336         fstrm = fread(fh, '*char')';
1337     catch ex
1338         fclose(fh);
1339         rethrow(ex);
1340     end
1341     fclose(fh);
1342
1343     % Include standard pdfmark prolog to maximize compatibility
1344     fstrm = strrep(fstrm, '%%BeginProlog', sprintf('%%%%BeginProlog\n/pdfmark where {pop} {userdict /pdfmark /cleartomark load put} ifelse'));
1345     % Add page bookmark
1346     fstrm = strrep(fstrm, '%%EndPageSetup', sprintf('%%%%EndPageSetup\n[ /Title (%s) /OUT pdfmark',bookmark_text));
1347
1348     % Write out the updated file
1349     fh = fopen(fname, 'w');
1350     if fh == -1
1351         error('Unable to open %s for writing.', fname);
1352     end
1353     try
1354         fwrite(fh, fstrm, 'char*1');
1355     catch ex
1356         fclose(fh);
1357         rethrow(ex);
1358     end
1359     fclose(fh);
1360 end
1361
1362 function set_tick_mode(Hlims, ax)
1363     % Set the tick mode of linear axes to manual
1364     % Leave log axes alone as these are tricky
1365     M = get(Hlims, [ax 'Scale']);
1366     if ~iscell(M)
1367         M = {M};
1368     end
1369     %idx = cellfun(@(c) strcmp(c, 'linear'), M);
1370     idx = find(strcmp(M,'linear'));
1371     %set(Hlims(idx), [ax 'TickMode'], 'manual');  % issue #187
1372     %set(Hlims(idx), [ax 'TickLabelMode'], 'manual');  % this hides exponent label in HG2!
1373     for idx2 = 1 : numel(idx)
1374         try
1375             % Fix for issue #187 - only set manual ticks when no exponent is present
1376             hAxes = Hlims(idx(idx2));
1377             props = {[ax 'TickMode'],'manual', [ax 'TickLabelMode'],'manual'};
1378             tickVals = get(hAxes,[ax 'Tick']);
1379             tickStrs = get(hAxes,[ax 'TickLabel']);
1380             try % Fix issue #236
1381                 exponents = [hAxes.([ax 'Axis']).SecondaryLabel];
1382             catch
1383                 exponents = [hAxes.([ax 'Ruler']).SecondaryLabel];
1384             end
1385             if isempty([exponents.String])
1386                 % Fix for issue #205 - only set manual ticks when the Ticks number match the TickLabels number
1387                 if numel(tickVals) == numel(tickStrs)
1388                     set(hAxes, props{:});  % no exponent and matching ticks, so update both ticks and tick labels to manual
1389                 end
1390             end
1391         catch  % probably HG1
1392             % Fix for issue #220 - exponent is removed in HG1 when TickMode is 'manual' (internal Matlab bug)
1393             if isequal(tickVals, str2num(tickStrs)') %#ok<ST2NM>
1394                 set(hAxes, props{:});  % revert back to old behavior
1395             end
1396         end
1397     end
1398 end
1399
1400 function change_rgb_to_cmyk(fname)  % convert RGB => CMYK within an EPS file
1401     % Do post-processing on the eps file
1402     try
1403         % Read the EPS file into memory
1404         fstrm = read_write_entire_textfile(fname);
1405
1406         % Replace all gray-scale colors
1407         fstrm = regexprep(fstrm, '\n([\d.]+) +GC\n', '\n0 0 0 ${num2str(1-str2num($1))} CC\n');
1408
1409         % Replace all RGB colors
1410         fstrm = regexprep(fstrm, '\n[0.]+ +[0.]+ +[0.]+ +RC\n', '\n0 0 0 1 CC\n');  % pure black
1411         fstrm = regexprep(fstrm, '\n([\d.]+) +([\d.]+) +([\d.]+) +RC\n', '\n${sprintf(''%.4g '',[1-[str2num($1),str2num($2),str2num($3)]/max([str2num($1),str2num($2),str2num($3)]),1-max([str2num($1),str2num($2),str2num($3)])])} CC\n');
1412
1413         % Overwrite the file with the modified contents
1414         read_write_entire_textfile(fname, fstrm);
1415     catch
1416         % never mind - leave as is...
1417     end
1418 end